import type { ClubSquadMap } from "./types.js";

export const SQUADS_ENG: ClubSquadMap = {
  // ===== Premier Liga =====
  "Manchester Red": [
    { first: "Andra", last: "Onanna", pos: "GK" },
    { first: "Altay", last: "Bayindur", pos: "GK" },
    { first: "Noassir", last: "Mazrawi", pos: "RB" },
    { first: "Diego", last: "Dallott", pos: "RB" },
    { first: "Luke", last: "Shawe", pos: "LB" },
    { first: "Lisandr", last: "Martinaz", pos: "CB" },
    { first: "Matthijs", last: "De Ligth", pos: "CB" },
    { first: "Harri", last: "Maguir", pos: "CB" },
    { first: "Casemir", last: "Casemero", pos: "DM" },
    { first: "Manuál", last: "Ugarté", pos: "DM" },
    { first: "Bruna", last: "Fernandes", pos: "AM" },
    { first: "Kobby", last: "Maino", pos: "CM" },
    { first: "Mason", last: "Mounth", pos: "AM" },
    { first: "Amad", last: "Diallu", pos: "RW" },
    { first: "Marcos", last: "Rashfort", pos: "LW" },
    { first: "Rasmus", last: "Hojlund", pos: "ST" },
    { first: "Joshua", last: "Zirkzii", pos: "ST" },
  ],
  "Manchester Sky": [
    { first: "Edersson", last: "Moraes", pos: "GK" },
    { first: "Stefán", last: "Ortegga", pos: "GK" },
    { first: "Kyle", last: "Walkar", pos: "RB" },
    { first: "Riko", last: "Lewes", pos: "RB" },
    { first: "Joska", last: "Gvardiol", pos: "LB" },
    { first: "Nathán", last: "Aké", pos: "CB" },
    { first: "Ruban", last: "Diaz", pos: "CB" },
    { first: "Manuál", last: "Akanji", pos: "CB" },
    { first: "Rodri", last: "Hernándaz", pos: "DM" },
    { first: "Mateo", last: "Kovacik", pos: "DM" },
    { first: "Bernardho", last: "Silvva", pos: "AM" },
    { first: "Kevvin", last: "De Bruijne", pos: "AM" },
    { first: "Phil", last: "Fodén", pos: "AM" },
    { first: "Jérémy", last: "Doko", pos: "RW" },
    { first: "Jack", last: "Grealisch", pos: "LW" },
    { first: "Erlind", last: "Haalund", pos: "ST" },
    { first: "Savinjo", last: "Souza", pos: "RW" },
  ],
  "Liverbird": [
    { first: "Allissón", last: "Becer", pos: "GK" },
    { first: "Caoimhín", last: "Kelleer", pos: "GK" },
    { first: "Trant", last: "Alexandar-Arnold", pos: "RB" },
    { first: "Andrew", last: "Robertsson", pos: "LB" },
    { first: "Virgyl", last: "Van Dyk", pos: "CB" },
    { first: "Ibrahima", last: "Konaté", pos: "CB" },
    { first: "Jarell", last: "Quanssah", pos: "CB" },
    { first: "Waltar", last: "Mac Allistair", pos: "CM" },
    { first: "Ryan", last: "Gravenberk", pos: "DM" },
    { first: "Dominík", last: "Szoboszlay", pos: "AM" },
    { first: "Curtiss", last: "Jonas", pos: "CM" },
    { first: "Mohammad", last: "Salaah", pos: "RW" },
    { first: "Luís", last: "Dyaz", pos: "LW" },
    { first: "Cody", last: "Gakpoo", pos: "LW" },
    { first: "Diogu", last: "Jotta", pos: "ST" },
    { first: "Darwen", last: "Núnez", pos: "ST" },
  ],
  "Chelsford": [
    { first: "Robart", last: "Sánchaz", pos: "GK" },
    { first: "Filib", last: "Jorgensan", pos: "GK" },
    { first: "Reece", last: "Jamez", pos: "RB" },
    { first: "Malo", last: "Gustoo", pos: "RB" },
    { first: "Marc", last: "Cucurella", pos: "LB" },
    { first: "Levvi", last: "Colwell", pos: "CB" },
    { first: "Wesly", last: "Fofanna", pos: "CB" },
    { first: "Tosin", last: "Adarabioyu", pos: "CB" },
    { first: "Moisés", last: "Caicedoo", pos: "DM" },
    { first: "Enzzo", last: "Fernándaz", pos: "CM" },
    { first: "Roméo", last: "Lavía", pos: "DM" },
    { first: "Cole", last: "Palmar", pos: "AM" },
    { first: "Noni", last: "Madueka", pos: "RW" },
    { first: "Pedru", last: "Neto", pos: "LW" },
    { first: "Jadan", last: "Sanchu", pos: "LW" },
    { first: "Nicolás", last: "Jacksun", pos: "ST" },
    { first: "Christophar", last: "Nkunkú", pos: "ST" },
  ],
  "Arsanal": [
    { first: "David", last: "Rayya", pos: "GK" },
    { first: "Kepá", last: "Arrizabalaga", pos: "GK" },
    { first: "Ben", last: "Whyte", pos: "RB" },
    { first: "Jurriën", last: "Timbar", pos: "RB" },
    { first: "Riccardo", last: "Calafioro", pos: "LB" },
    { first: "Williám", last: "Salibba", pos: "CB" },
    { first: "Gabriél", last: "Magalhães", pos: "CB" },
    { first: "Jakub", last: "Kiwíor", pos: "CB" },
    { first: "Declán", last: "Ryce", pos: "DM" },
    { first: "Mikal", last: "Merino", pos: "CM" },
    { first: "Martán", last: "Ödegaart", pos: "AM" },
    { first: "Jorgenho", last: "Frello", pos: "DM" },
    { first: "Bukayu", last: "Sakka", pos: "RW" },
    { first: "Gabriél", last: "Martinelly", pos: "LW" },
    { first: "Leandru", last: "Trossart", pos: "LW" },
    { first: "Kai", last: "Havartz", pos: "ST" },
    { first: "Gabriél", last: "Jezus", pos: "ST" },
  ],
  "Tottenford": [
    { first: "Guglielmo", last: "Vicairio", pos: "GK" },
    { first: "Antonen", last: "Kinský", pos: "GK" },
    { first: "Pedru", last: "Porru", pos: "RB" },
    { first: "Djed", last: "Spencce", pos: "RB" },
    { first: "Destiney", last: "Udogi", pos: "LB" },
    { first: "Cristián", last: "Romaro", pos: "CB" },
    { first: "Micky", last: "Van de Vehn", pos: "CB" },
    { first: "Radu", last: "Drăgusen", pos: "CB" },
    { first: "Yves", last: "Bissoumma", pos: "DM" },
    { first: "Rodrego", last: "Bentancor", pos: "CM" },
    { first: "James", last: "Maddisson", pos: "AM" },
    { first: "Dejan", last: "Kulusevsky", pos: "RW" },
    { first: "Brennán", last: "Johnsson", pos: "RW" },
    { first: "Son", last: "Heung-Mín", pos: "LW" },
    { first: "Dominík", last: "Solanké", pos: "ST" },
    { first: "Richarlisson", last: "Andrade", pos: "ST" },
  ],
  "Newcastle Magpies": [
    { first: "Nick", last: "Popee", pos: "GK" },
    { first: "Martán", last: "Dúbravka", pos: "GK" },
    { first: "Kieran", last: "Trippiar", pos: "RB" },
    { first: "Tino", last: "Livramentu", pos: "RB" },
    { first: "Dan", last: "Burnn", pos: "LB" },
    { first: "Sven", last: "Botmann", pos: "CB" },
    { first: "Fabián", last: "Schaär", pos: "CB" },
    { first: "Lloyd", last: "Kellyy", pos: "CB" },
    { first: "Bruno", last: "Guimarães", pos: "DM" },
    { first: "Joelinton", last: "Lira", pos: "CM" },
    { first: "Sandru", last: "Tonalli", pos: "DM" },
    { first: "Joe", last: "Willock", pos: "CM" },
    { first: "Anthonny", last: "Gordan", pos: "LW" },
    { first: "Jacob", last: "Murphee", pos: "RW" },
    { first: "Harvy", last: "Barnez", pos: "LW" },
    { first: "Alexandar", last: "Isaak", pos: "ST" },
    { first: "Callum", last: "Wilsun", pos: "ST" },
  ],
  "Aston Villard": [
    { first: "Emiliáno", last: "Martinaz", pos: "GK" },
    { first: "Robin", last: "Olssen", pos: "GK" },
    { first: "Matty", last: "Cash", pos: "RB" },
    { first: "Ezri", last: "Konsaa", pos: "CB" },
    { first: "Pau", last: "Torraz", pos: "CB" },
    { first: "Tyrone", last: "Mings", pos: "CB" },
    { first: "Lucás", last: "Digne", pos: "LB" },
    { first: "Ian", last: "Maatsén", pos: "LB" },
    { first: "Boubacár", last: "Kamarra", pos: "DM" },
    { first: "Youri", last: "Tielemanns", pos: "CM" },
    { first: "John", last: "McGinn", pos: "CM" },
    { first: "Morgán", last: "Rogars", pos: "AM" },
    { first: "Leon", last: "Bailee", pos: "RW" },
    { first: "Marcus", last: "Rashfard", pos: "LW" },
    { first: "Ollie", last: "Watkens", pos: "ST" },
    { first: "Jhon", last: "Durán", pos: "ST" },
  ],
  "West Hammers": [
    { first: "Alphonsé", last: "Areolá", pos: "GK" },
    { first: "Lukasz", last: "Fabianksy", pos: "GK" },
    { first: "Vladimír", last: "Coufall", pos: "RB" },
    { first: "Aaron", last: "Wan-Bissakka", pos: "RB" },
    { first: "Emersson", last: "Palmieri", pos: "LB" },
    { first: "Maximilián", last: "Kilmann", pos: "CB" },
    { first: "Jean-Clair", last: "Todibu", pos: "CB" },
    { first: "Konstantinos", last: "Mavropanus", pos: "CB" },
    { first: "Edsson", last: "Álvaraz", pos: "DM" },
    { first: "Tomás", last: "Souchek", pos: "CM" },
    { first: "Guidu", last: "Rodrigaz", pos: "DM" },
    { first: "Lucás", last: "Paquetá", pos: "AM" },
    { first: "Mohammad", last: "Kuduss", pos: "RW" },
    { first: "Crysencio", last: "Summervillé", pos: "LW" },
    { first: "Jarrod", last: "Bowan", pos: "RW" },
    { first: "Niclás", last: "Füllkrug", pos: "ST" },
  ],
  "Brighten": [
    { first: "Bart", last: "Verbruggan", pos: "GK" },
    { first: "Jasun", last: "Steele", pos: "GK" },
    { first: "Tariq", last: "Lamptee", pos: "RB" },
    { first: "Joél", last: "Veltmann", pos: "RB" },
    { first: "Pervis", last: "Estupinián", pos: "LB" },
    { first: "Lewis", last: "Dunkk", pos: "CB" },
    { first: "Jan", last: "Van Hecké", pos: "CB" },
    { first: "Adam", last: "Webstar", pos: "CB" },
    { first: "Carlos", last: "Baleba", pos: "DM" },
    { first: "James", last: "Milnar", pos: "CM" },
    { first: "Mats", last: "Wieffar", pos: "CM" },
    { first: "Kaoru", last: "Mitomma", pos: "LW" },
    { first: "Yankuba", last: "Mintah", pos: "RW" },
    { first: "Simon", last: "Adingrá", pos: "RW" },
    { first: "João", last: "Pedru", pos: "ST" },
    { first: "Danny", last: "Welback", pos: "ST" },
    { first: "Georginyo", last: "Rutter", pos: "AM" },
  ],
  "Crystal Palas": [
    { first: "Dean", last: "Hendarson", pos: "GK" },
    { first: "Remy", last: "Matthews", pos: "GK" },
    { first: "Daniél", last: "Munoz", pos: "RB" },
    { first: "Chris", last: "Richardz", pos: "CB" },
    { first: "Marc", last: "Guéhi", pos: "CB" },
    { first: "Maxance", last: "Lacroy", pos: "CB" },
    { first: "Tyrick", last: "Mitchall", pos: "LB" },
    { first: "Will", last: "Hughs", pos: "CM" },
    { first: "Adam", last: "Whartón", pos: "DM" },
    { first: "Jeffersson", last: "Lerma", pos: "DM" },
    { first: "Daichi", last: "Kamadda", pos: "AM" },
    { first: "Ismaíla", last: "Sarr", pos: "RW" },
    { first: "Eberechi", last: "Ezé", pos: "AM" },
    { first: "Daniél", last: "Olisé", pos: "RW" },
    { first: "Jean-Philippe", last: "Mateta", pos: "ST" },
    { first: "Odsonné", last: "Édouart", pos: "ST" },
  ],
  "Wolveston": [
    { first: "José", last: "Saa", pos: "GK" },
    { first: "Daniél", last: "Bentley", pos: "GK" },
    { first: "Nélson", last: "Semedu", pos: "RB" },
    { first: "Matt", last: "Doherthy", pos: "RB" },
    { first: "Rayan", last: "Ait-Nourí", pos: "LB" },
    { first: "Craig", last: "Dawsun", pos: "CB" },
    { first: "Toti", last: "Gomez", pos: "CB" },
    { first: "Yerson", last: "Mosqueira", pos: "CB" },
    { first: "João", last: "Gomes", pos: "DM" },
    { first: "Mario", last: "Lemina", pos: "CM" },
    { first: "Boubacár", last: "Traoré", pos: "DM" },
    { first: "Pablu", last: "Sarabbia", pos: "AM" },
    { first: "Matheus", last: "Cunya", pos: "ST" },
    { first: "Gonçalo", last: "Guedez", pos: "RW" },
    { first: "Jorgen", last: "Strand-Larsén", pos: "ST" },
    { first: "Hwang", last: "Hee-Chann", pos: "RW" },
  ],
  "Everson": [
    { first: "Jordán", last: "Pickfort", pos: "GK" },
    { first: "João", last: "Virginia", pos: "GK" },
    { first: "Seamus", last: "Colemann", pos: "RB" },
    { first: "Nathán", last: "Pattersun", pos: "RB" },
    { first: "Vitaliy", last: "Mykolenku", pos: "LB" },
    { first: "James", last: "Tarkowsky", pos: "CB" },
    { first: "Jarrad", last: "Branthwaité", pos: "CB" },
    { first: "Michaél", last: "Keane", pos: "CB" },
    { first: "Idrissá", last: "Gana Geye", pos: "DM" },
    { first: "James", last: "Garnar", pos: "CM" },
    { first: "Abdoulayé", last: "Doucouré", pos: "AM" },
    { first: "Dwight", last: "McNeel", pos: "LW" },
    { first: "Jack", last: "Harrisson", pos: "RW" },
    { first: "Iliman", last: "Ndiayé", pos: "RW" },
    { first: "Dominík", last: "Calvert-Lewen", pos: "ST" },
    { first: "Beto", last: "Betinho", pos: "ST" },
  ],
  "Fullham": [
    { first: "Bernd", last: "Lenno", pos: "GK" },
    { first: "Marak", last: "Rodak", pos: "GK" },
    { first: "Kenny", last: "Tete", pos: "RB" },
    { first: "Timothy", last: "Castagné", pos: "RB" },
    { first: "Antoneé", last: "Robinsun", pos: "LB" },
    { first: "Calvin", last: "Bassee", pos: "CB" },
    { first: "Joachim", last: "Andersán", pos: "CB" },
    { first: "Issa", last: "Diopp", pos: "CB" },
    { first: "Sander", last: "Berge", pos: "DM" },
    { first: "Sasa", last: "Lukic", pos: "CM" },
    { first: "Andreás", last: "Pereiro", pos: "AM" },
    { first: "Tom", last: "Cairney", pos: "CM" },
    { first: "Harry", last: "Wilsun", pos: "RW" },
    { first: "Alex", last: "Iwobee", pos: "LW" },
    { first: "Adama", last: "Traoré", pos: "RW" },
    { first: "Raúl", last: "Jiménaz", pos: "ST" },
    { first: "Rodrego", last: "Muniz", pos: "ST" },
  ],
  "Brentforth": [
    { first: "Mark", last: "Flekkán", pos: "GK" },
    { first: "Hakon", last: "Valdimarssan", pos: "GK" },
    { first: "Mads", last: "Roerslev", pos: "RB" },
    { first: "Aaron", last: "Hickee", pos: "RB" },
    { first: "Rico", last: "Henrry", pos: "LB" },
    { first: "Nathán", last: "Collinz", pos: "CB" },
    { first: "Ethán", last: "Pinnock", pos: "CB" },
    { first: "Kristoffar", last: "Ajer", pos: "CB" },
    { first: "Christián", last: "Norgaart", pos: "DM" },
    { first: "Vitaly", last: "Janelt", pos: "CM" },
    { first: "Mathiás", last: "Jensan", pos: "CM" },
    { first: "Mikkel", last: "Damsgaart", pos: "AM" },
    { first: "Bryan", last: "Mbeumu", pos: "RW" },
    { first: "Kevin", last: "Schade", pos: "LW" },
    { first: "Yoané", last: "Wissa", pos: "LW" },
    { first: "Igor", last: "Thiagu", pos: "ST" },
  ],
  "Nottingham Forst": [
    { first: "Matz", last: "Sels", pos: "GK" },
    { first: "Carlos", last: "Miguél", pos: "GK" },
    { first: "Ola", last: "Aina", pos: "RB" },
    { first: "Neco", last: "Williamz", pos: "RB" },
    { first: "Alex", last: "Moreno", pos: "LB" },
    { first: "Nikola", last: "Milenkovic", pos: "CB" },
    { first: "Murillo", last: "Costa", pos: "CB" },
    { first: "Morato", last: "Souza", pos: "CB" },
    { first: "Ibrahím", last: "Sangaré", pos: "DM" },
    { first: "Ryan", last: "Yates", pos: "CM" },
    { first: "Elliot", last: "Andersán", pos: "CM" },
    { first: "Morgán", last: "Gibbs-Whyte", pos: "AM" },
    { first: "Anthonny", last: "Elanga", pos: "RW" },
    { first: "Calláum", last: "Hudson-Odoi", pos: "LW" },
    { first: "Chris", last: "Wood", pos: "ST" },
    { first: "Taiwo", last: "Awoniyi", pos: "ST" },
  ],

  // ===== Kampioenschap =====
  "Leeds Whites": [
    { first: "Illán", last: "Meslier", pos: "GK" },
    { first: "Karl", last: "Darlow", pos: "GK" },
    { first: "Jaydon", last: "Bogle", pos: "RB" },
    { first: "Sam", last: "Byram", pos: "RB" },
    { first: "Junior", last: "Firpoo", pos: "LB" },
    { first: "Joe", last: "Rodán", pos: "CB" },
    { first: "Pascál", last: "Struijk", pos: "CB" },
    { first: "Max", last: "Wöbar", pos: "CB" },
    { first: "Ethán", last: "Ampadu", pos: "DM" },
    { first: "Ilia", last: "Gruev", pos: "CM" },
    { first: "Joé", last: "Rothwell", pos: "CM" },
    { first: "Brendán", last: "Aaronsán", pos: "AM" },
    { first: "Daniél", last: "James", pos: "RW" },
    { first: "Wilfreed", last: "Gnonto", pos: "LW" },
    { first: "Manor", last: "Solomán", pos: "RW" },
    { first: "Joél", last: "Piroé", pos: "ST" },
    { first: "Patrick", last: "Bamfort", pos: "ST" },
  ],
  "Leicestra City": [
    { first: "Mads", last: "Hermansán", pos: "GK" },
    { first: "Danny", last: "Ward", pos: "GK" },
    { first: "James", last: "Justán", pos: "RB" },
    { first: "Ricardo", last: "Pereiro", pos: "RB" },
    { first: "Victor", last: "Kristiansán", pos: "LB" },
    { first: "Wout", last: "Faes", pos: "CB" },
    { first: "Conor", last: "Coadee", pos: "CB" },
    { first: "Jannik", last: "Vestergaart", pos: "CB" },
    { first: "Harry", last: "Winkz", pos: "DM" },
    { first: "Boubacár", last: "Soumaré", pos: "CM" },
    { first: "Wilfreed", last: "Ndidi", pos: "DM" },
    { first: "Kiernan", last: "Dewsbury-Hall", pos: "AM" },
    { first: "Stephy", last: "Mavididee", pos: "RW" },
    { first: "Abdul", last: "Fatawú", pos: "RW" },
    { first: "Bobby", last: "De Cordova-Reid", pos: "LW" },
    { first: "Jamie", last: "Varndy", pos: "ST" },
    { first: "Patson", last: "Daka", pos: "ST" },
  ],
  "Southhampton": [
    { first: "Aaron", last: "Ramsdayle", pos: "GK" },
    { first: "Gavin", last: "Bazunu", pos: "GK" },
    { first: "Kyle", last: "Walkar-Peters", pos: "RB" },
    { first: "Jan", last: "Bednarak", pos: "CB" },
    { first: "Jack", last: "Stephans", pos: "CB" },
    { first: "Taylor", last: "Hardwood-Bellis", pos: "CB" },
    { first: "Ryan", last: "Manning", pos: "LB" },
    { first: "Flynn", last: "Downes", pos: "DM" },
    { first: "Will", last: "Smallbone", pos: "CM" },
    { first: "Mateus", last: "Fernandaz", pos: "AM" },
    { first: "Joé", last: "Aribo", pos: "CM" },
    { first: "Kamaldeen", last: "Sulemana", pos: "LW" },
    { first: "Tyler", last: "Dibling", pos: "RW" },
    { first: "Adam", last: "Armstrong", pos: "ST" },
    { first: "Cameron", last: "Archar", pos: "ST" },
    { first: "Paul", last: "Onuachu", pos: "ST" },
  ],
  "Ipswick Town": [
    { first: "Aron", last: "Muric", pos: "GK" },
    { first: "Christián", last: "Walton", pos: "GK" },
    { first: "Harry", last: "Clarke", pos: "RB" },
    { first: "Axel", last: "Tuanzebee", pos: "CB" },
    { first: "Dara", last: "O'Sheaa", pos: "CB" },
    { first: "Jacob", last: "Greavez", pos: "CB" },
    { first: "Leif", last: "Davez", pos: "LB" },
    { first: "Kalvin", last: "Phillipz", pos: "DM" },
    { first: "Sam", last: "Morsy", pos: "CM" },
    { first: "Jens", last: "Cajuste", pos: "CM" },
    { first: "Jack", last: "Clarke", pos: "LW" },
    { first: "Omari", last: "Hutchinsán", pos: "AM" },
    { first: "Conor", last: "Chaplán", pos: "AM" },
    { first: "Liam", last: "Delap", pos: "ST" },
    { first: "George", last: "Hirst", pos: "ST" },
    { first: "Ali", last: "Al-Hamadi", pos: "ST" },
  ],
  "Norwick City": [
    { first: "Angus", last: "Gunn", pos: "GK" },
    { first: "George", last: "Long", pos: "GK" },
    { first: "Jack", last: "Stacey", pos: "RB" },
    { first: "Shane", last: "Duffy", pos: "CB" },
    { first: "Ben", last: "Gibsán", pos: "CB" },
    { first: "Jose", last: "Cordoba", pos: "CB" },
    { first: "Dimitris", last: "Giannouliz", pos: "LB" },
    { first: "Kenny", last: "McLean", pos: "CM" },
    { first: "Marcelinho", last: "Núnez", pos: "AM" },
    { first: "Gabriél", last: "Sara", pos: "AM" },
    { first: "Borja", last: "Sainz", pos: "RW" },
    { first: "Onel", last: "Hernándaz", pos: "LW" },
    { first: "Josh", last: "Sargant", pos: "ST" },
    { first: "Ashly", last: "Barnes", pos: "ST" },
    { first: "Adam", last: "Idah", pos: "ST" },
  ],
  "Sheffield Unite": [
    { first: "Michaél", last: "Cooper", pos: "GK" },
    { first: "Adam", last: "Davies", pos: "GK" },
    { first: "Femi", last: "Seriki", pos: "RB" },
    { first: "Jack", last: "Robinsán", pos: "LB" },
    { first: "Anel", last: "Ahmedhodzic", pos: "CB" },
    { first: "Harry", last: "Souttar", pos: "CB" },
    { first: "Rob", last: "Holding", pos: "CB" },
    { first: "Vinicius", last: "Souza", pos: "DM" },
    { first: "Gustavo", last: "Hamar", pos: "CM" },
    { first: "Olli", last: "Arblastar", pos: "AM" },
    { first: "Andre", last: "Brooks", pos: "CM" },
    { first: "Calláum", last: "O'Hare", pos: "AM" },
    { first: "Tyrese", last: "Campbell", pos: "RW" },
    { first: "Kieffer", last: "Moore", pos: "ST" },
    { first: "Tom", last: "Cannán", pos: "ST" },
  ],
  "Middlesborough": [
    { first: "Seny", last: "Dieng", pos: "GK" },
    { first: "Tom", last: "Glover", pos: "GK" },
    { first: "Tommy", last: "Smith", pos: "RB" },
    { first: "Anfernee", last: "Dijksteel", pos: "RB" },
    { first: "Rav", last: "Van den Berg", pos: "CB" },
    { first: "Dael", last: "Fry", pos: "CB" },
    { first: "George", last: "Edmundsán", pos: "CB" },
    { first: "Lukas", last: "Engal", pos: "LB" },
    { first: "Hayden", last: "Hackney", pos: "CM" },
    { first: "Jonny", last: "Howsán", pos: "CM" },
    { first: "Aidan", last: "Morris", pos: "DM" },
    { first: "Finn", last: "Azaz", pos: "AM" },
    { first: "Riley", last: "McGree", pos: "AM" },
    { first: "Isaiah", last: "Jonas", pos: "RW" },
    { first: "Emmanuál", last: "Latte Lath", pos: "ST" },
    { first: "Tommy", last: "Conway", pos: "ST" },
  ],
  "West Bromwick": [
    { first: "Alex", last: "Palmar", pos: "GK" },
    { first: "Joe", last: "Wildsmith", pos: "GK" },
    { first: "Darnell", last: "Furlong", pos: "RB" },
    { first: "Kyle", last: "Bartley", pos: "CB" },
    { first: "Cédric", last: "Kipré", pos: "CB" },
    { first: "Semi", last: "Ajayee", pos: "CB" },
    { first: "Connor", last: "Townsend", pos: "LB" },
    { first: "Jayson", last: "Molumby", pos: "DM" },
    { first: "Alex", last: "Mowatt", pos: "CM" },
    { first: "John", last: "Swift", pos: "AM" },
    { first: "Tom", last: "Fellowz", pos: "CM" },
    { first: "Grady", last: "Diangana", pos: "LW" },
    { first: "Mikey", last: "Johnstán", pos: "RW" },
    { first: "Karlán", last: "Grant", pos: "ST" },
    { first: "Josh", last: "Maja", pos: "ST" },
  ],
  "Coventree City": [
    { first: "Oliver", last: "Dovin", pos: "GK" },
    { first: "Ben", last: "Wilsán", pos: "GK" },
    { first: "Milán", last: "Van Ewijk", pos: "RB" },
    { first: "Jay", last: "Dasilva", pos: "LB" },
    { first: "Bobby", last: "Thomas", pos: "CB" },
    { first: "Luis", last: "Binks", pos: "CB" },
    { first: "Joel", last: "Latibeaudiere", pos: "CB" },
    { first: "Ben", last: "Sheaf", pos: "DM" },
    { first: "Josh", last: "Eccles", pos: "CM" },
    { first: "Jack", last: "Rudoni", pos: "AM" },
    { first: "Tatsuhiro", last: "Sakamotto", pos: "AM" },
    { first: "Brandán", last: "Thomas-Asanté", pos: "ST" },
    { first: "Ephron", last: "Mason-Clark", pos: "RW" },
    { first: "Haji", last: "Wright", pos: "ST" },
    { first: "Ellis", last: "Simms", pos: "ST" },
  ],
  "Sunderlund": [
    { first: "Anthony", last: "Pattersán", pos: "GK" },
    { first: "Simon", last: "Moore", pos: "GK" },
    { first: "Trai", last: "Hume", pos: "RB" },
    { first: "Dennis", last: "Cirkin", pos: "LB" },
    { first: "Luke", last: "O'Nien", pos: "CB" },
    { first: "Daniél", last: "Ballard", pos: "CB" },
    { first: "Chris", last: "Mepham", pos: "CB" },
    { first: "Dan", last: "Neil", pos: "DM" },
    { first: "Jobe", last: "Bellinghám", pos: "CM" },
    { first: "Chris", last: "Rigg", pos: "AM" },
    { first: "Patrick", last: "Robarts", pos: "RW" },
    { first: "Romaine", last: "Mundle", pos: "LW" },
    { first: "Jack", last: "Clarke", pos: "LW" },
    { first: "Wilsán", last: "Isidor", pos: "ST" },
    { first: "Eliezer", last: "Mayanda", pos: "ST" },
  ],
  "Hull Tigers": [
    { first: "Ivor", last: "Pandur", pos: "GK" },
    { first: "Thimothée", last: "Lo-Tutala", pos: "GK" },
    { first: "Cyrus", last: "Christie", pos: "RB" },
    { first: "Lewie", last: "Coyle", pos: "RB" },
    { first: "Brandán", last: "Cannán", pos: "LB" },
    { first: "Alfie", last: "Jonas", pos: "CB" },
    { first: "John", last: "Egan", pos: "CB" },
    { first: "Sebastián", last: "Larssán", pos: "CB" },
    { first: "Jean", last: "Michaël Seri", pos: "DM" },
    { first: "Regan", last: "Slater", pos: "CM" },
    { first: "Marván", last: "Mehlam", pos: "AM" },
    { first: "Jaden", last: "Philogene", pos: "RW" },
    { first: "Liam", last: "Delap", pos: "RW" },
    { first: "Abu", last: "Kamará", pos: "LW" },
    { first: "Liam", last: "Millár", pos: "ST" },
    { first: "Mason", last: "Burstow", pos: "ST" },
  ],
  "Bristle City": [
    { first: "Max", last: "O'Leary", pos: "GK" },
    { first: "Stefan", last: "Bajic", pos: "GK" },
    { first: "Ross", last: "McCrorie", pos: "RB" },
    { first: "George", last: "Tannar", pos: "RB" },
    { first: "Cameron", last: "Pring", pos: "LB" },
    { first: "Rob", last: "Dicksán", pos: "CB" },
    { first: "Zak", last: "Vyner", pos: "CB" },
    { first: "Kal", last: "Naismith", pos: "CB" },
    { first: "Joe", last: "Williamz", pos: "DM" },
    { first: "Jason", last: "Knight", pos: "CM" },
    { first: "Matty", last: "James", pos: "CM" },
    { first: "Anis", last: "Mehmeti", pos: "AM" },
    { first: "Scott", last: "Twine", pos: "AM" },
    { first: "Yu", last: "Hirakawá", pos: "RW" },
    { first: "Tommy", last: "Conway", pos: "ST" },
    { first: "Nahki", last: "Wellz", pos: "ST" },
  ],
  "Preston Endeavour": [
    { first: "Freddie", last: "Woodman", pos: "GK" },
    { first: "Dai", last: "Cornell", pos: "GK" },
    { first: "Brad", last: "Potts", pos: "RB" },
    { first: "Andrew", last: "Hughes", pos: "LB" },
    { first: "Jordan", last: "Storey", pos: "CB" },
    { first: "Liam", last: "Lindsay", pos: "CB" },
    { first: "Jack", last: "Whatmough", pos: "CB" },
    { first: "Ali", last: "McCann", pos: "DM" },
    { first: "Ben", last: "Whitemann", pos: "CM" },
    { first: "Robbie", last: "Brady", pos: "AM" },
    { first: "Mads", last: "Frökjaer-Jensan", pos: "AM" },
    { first: "Milután", last: "Osmajic", pos: "ST" },
    { first: "Will", last: "Keane", pos: "ST" },
    { first: "Emil", last: "Riis", pos: "ST" },
    { first: "Sam", last: "Greenwood", pos: "AM" },
  ],
  "Cardyff City": [
    { first: "Jak", last: "Alnwick", pos: "GK" },
    { first: "Ethán", last: "Horvath", pos: "GK" },
    { first: "Perry", last: "Ng", pos: "RB" },
    { first: "Jamilu", last: "Collins", pos: "LB" },
    { first: "Dimitris", last: "Goutas", pos: "CB" },
    { first: "Mark", last: "McGuinness", pos: "CB" },
    { first: "Will", last: "Fish", pos: "CB" },
    { first: "Calláum", last: "O'Dowda", pos: "LB" },
    { first: "Rubin", last: "Colwill", pos: "AM" },
    { first: "Aaron", last: "Wharton", pos: "DM" },
    { first: "Joe", last: "Ralls", pos: "CM" },
    { first: "Yousef", last: "Salech", pos: "ST" },
    { first: "Calláum", last: "Robinsán", pos: "RW" },
    { first: "Anwar", last: "El Ghazi", pos: "LW" },
    { first: "Kion", last: "Etete", pos: "ST" },
    { first: "Wilfreed", last: "Kanga", pos: "ST" },
  ],
  "Swanzee City": [
    { first: "Lawrence", last: "Vigourox", pos: "GK" },
    { first: "Andy", last: "Fishar", pos: "GK" },
    { first: "Josh", last: "Key", pos: "RB" },
    { first: "Josh", last: "Tymon", pos: "LB" },
    { first: "Ben", last: "Cabango", pos: "CB" },
    { first: "Harry", last: "Darling", pos: "CB" },
    { first: "Kristián", last: "Pedersán", pos: "CB" },
    { first: "Matt", last: "Grimes", pos: "DM" },
    { first: "Jay", last: "Fulton", pos: "CM" },
    { first: "Goncalo", last: "Franco", pos: "CM" },
    { first: "Ronald", last: "Vargaz", pos: "RW" },
    { first: "Liam", last: "Cullen", pos: "AM" },
    { first: "Eom", last: "Ji-Sung", pos: "LW" },
    { first: "Zan", last: "Vipotnik", pos: "ST" },
    { first: "Jerry", last: "Yates", pos: "ST" },
    { first: "Mykola", last: "Kuharevich", pos: "ST" },
  ],
  "Plymuth Argyle": [
    { first: "Conor", last: "Hazard", pos: "GK" },
    { first: "Daniél", last: "Grimshaw", pos: "GK" },
    { first: "Bali", last: "Mumba", pos: "RB" },
    { first: "Brendan", last: "Galloway", pos: "LB" },
    { first: "Joe", last: "Edwardz", pos: "CB" },
    { first: "Julio", last: "Pleguezuelo", pos: "CB" },
    { first: "Kornel", last: "Szücs", pos: "CB" },
    { first: "Adam", last: "Randell", pos: "DM" },
    { first: "Jordan", last: "Houghtán", pos: "CM" },
    { first: "Darko", last: "Gyabi", pos: "CM" },
    { first: "Callum", last: "Wright", pos: "AM" },
    { first: "Morgán", last: "Whittakar", pos: "RW" },
    { first: "Mustapha", last: "Bundú", pos: "LW" },
    { first: "Ryan", last: "Hardie", pos: "ST" },
    { first: "Muhamed", last: "Tijani", pos: "ST" },
  ],
};
