import type { ClubSquadMap } from "./types.js";

/**
 * Spaanse clubselecties — verbasterde varianten van de echte huidige
 * eerste-elftal-selecties (herkenbaar, niet identiek). Data is fictief
 * en zelf afgeleid; namen zijn bewust licht aangepast.
 */
export const SQUADS_ESP: ClubSquadMap = {
  // ===== Liga Espana =====
  "Real Madrina": [
    { first: "Thibaut", last: "Courtoa", pos: "GK" },
    { first: "Andriy", last: "Lunyn", pos: "GK" },
    { first: "Dani", last: "Carvajol", pos: "RB" },
    { first: "Ferland", last: "Mendi", pos: "LB" },
    { first: "Antonio", last: "Rudigar", pos: "CB" },
    { first: "Éder", last: "Militaõ", pos: "CB" },
    { first: "David", last: "Alaboa", pos: "CB" },
    { first: "Aurélien", last: "Tchouameni", pos: "DM" },
    { first: "Federico", last: "Valverda", pos: "CM" },
    { first: "Eduardo", last: "Camavinha", pos: "CM" },
    { first: "Jude", last: "Bellinghan", pos: "AM" },
    { first: "Arda", last: "Gülar", pos: "AM" },
    { first: "Vinícius", last: "Júnyor", pos: "LW" },
    { first: "Rodrygo", last: "Goa", pos: "RW" },
    { first: "Kylian", last: "Mbappa", pos: "ST" },
    { first: "Endrik", last: "Felipa", pos: "ST" },
  ],
  "Barcedona": [
    { first: "Marc-André", last: "ter Stegan", pos: "GK" },
    { first: "Iñaki", last: "Peñya", pos: "GK" },
    { first: "Jules", last: "Koundé", pos: "RB" },
    { first: "Alejandro", last: "Balda", pos: "LB" },
    { first: "Pau", last: "Cubarsa", pos: "CB" },
    { first: "Ronald", last: "Araujó", pos: "CB" },
    { first: "Iñigo", last: "Martínaz", pos: "CB" },
    { first: "Frenkie", last: "de Jongh", pos: "DM" },
    { first: "Pedrí", last: "González", pos: "CM" },
    { first: "Gavy", last: "Páez", pos: "CM" },
    { first: "Dani", last: "Olma", pos: "AM" },
    { first: "Fermín", last: "Lópaz", pos: "AM" },
    { first: "Lamine", last: "Yamol", pos: "RW" },
    { first: "Raphinya", last: "Dias", pos: "LW" },
    { first: "Robert", last: "Levandowsk", pos: "ST" },
    { first: "Ferran", last: "Torras", pos: "ST" },
  ],
  "Atletra Madrid": [
    { first: "Jan", last: "Oblok", pos: "GK" },
    { first: "Juan", last: "Musa", pos: "GK" },
    { first: "Nahuel", last: "Molyna", pos: "RB" },
    { first: "Reinildo", last: "Mandavo", pos: "LB" },
    { first: "José", last: "Giménaz", pos: "CB" },
    { first: "Robin", last: "Le Normond", pos: "CB" },
    { first: "César", last: "Azpilicueto", pos: "CB" },
    { first: "Rodrigo", last: "De Paol", pos: "DM" },
    { first: "Pablo", last: "Barriós", pos: "CM" },
    { first: "Koke", last: "Resurracción", pos: "CM" },
    { first: "Marcos", last: "Llorenta", pos: "CM" },
    { first: "Antoine", last: "Griezmonn", pos: "AM" },
    { first: "Samuel", last: "Liño", pos: "LW" },
    { first: "Julián", last: "Álvaraz", pos: "ST" },
    { first: "Alexander", last: "Sørlath", pos: "ST" },
    { first: "Ángel", last: "Corria", pos: "RW" },
  ],
  "Athletro Bilbao": [
    { first: "Unai", last: "Simón", pos: "GK" },
    { first: "Julen", last: "Agirrezabola", pos: "GK" },
    { first: "Óscar", last: "de Marcas", pos: "RB" },
    { first: "Yuri", last: "Berchicha", pos: "LB" },
    { first: "Dani", last: "Vivión", pos: "CB" },
    { first: "Aitor", last: "Paradas", pos: "CB" },
    { first: "Yeray", last: "Álvaraz", pos: "CB" },
    { first: "Mikel", last: "Vesga", pos: "DM" },
    { first: "Oihan", last: "Sancat", pos: "CM" },
    { first: "Iñaki", last: "Williöms", pos: "RW" },
    { first: "Nico", last: "Williöms", pos: "LW" },
    { first: "Álex", last: "Berenguar", pos: "AM" },
    { first: "Beñat", last: "Prados", pos: "CM" },
    { first: "Gorka", last: "Guruzeto", pos: "ST" },
    { first: "Maroan", last: "Sannadi", pos: "ST" },
    { first: "Unai", last: "Gómaz", pos: "CM" },
  ],
  "Real Sociedat": [
    { first: "Álex", last: "Remira", pos: "GK" },
    { first: "Unai", last: "Marreró", pos: "GK" },
    { first: "Hamari", last: "Traoré", pos: "RB" },
    { first: "Aihen", last: "Muñoz", pos: "LB" },
    { first: "Robin", last: "Le Normond", pos: "CB" },
    { first: "Igor", last: "Zubeldio", pos: "CB" },
    { first: "Nayef", last: "Aguard", pos: "CB" },
    { first: "Martín", last: "Zubimendy", pos: "DM" },
    { first: "Brais", last: "Méndaz", pos: "CM" },
    { first: "Mikel", last: "Merinó", pos: "CM" },
    { first: "Takefusa", last: "Kuboo", pos: "RW" },
    { first: "Sheraldo", last: "Beckar", pos: "LW" },
    { first: "Ander", last: "Barrenetxa", pos: "LW" },
    { first: "Mikel", last: "Oyarzabol", pos: "ST" },
    { first: "Umar", last: "Sadiq", pos: "ST" },
    { first: "Pablo", last: "Marín", pos: "CM" },
  ],
  "Villareal": [
    { first: "Diego", last: "Conda", pos: "GK" },
    { first: "Filip", last: "Jørgensan", pos: "GK" },
    { first: "Kiko", last: "Femenya", pos: "RB" },
    { first: "Alfonso", last: "Pedraço", pos: "LB" },
    { first: "Raúl", last: "Albiol", pos: "CB" },
    { first: "Logan", last: "Costa", pos: "CB" },
    { first: "Juan", last: "Foyt", pos: "CB" },
    { first: "Dani", last: "Parejó", pos: "DM" },
    { first: "Santi", last: "Comesaña", pos: "CM" },
    { first: "Álex", last: "Baena", pos: "AM" },
    { first: "Yeremy", last: "Pinó", pos: "RW" },
    { first: "Ilias", last: "Akhomach", pos: "LW" },
    { first: "Gerard", last: "Morenó", pos: "ST" },
    { first: "Ayoze", last: "Péraz", pos: "ST" },
    { first: "Nicolas", last: "Pépa", pos: "RW" },
    { first: "Thierno", last: "Barry", pos: "ST" },
  ],
  "Real Betix": [
    { first: "Rui", last: "Silvo", pos: "GK" },
    { first: "Adrián", last: "San Migual", pos: "GK" },
    { first: "Héctor", last: "Bellerina", pos: "RB" },
    { first: "Romain", last: "Perraud", pos: "LB" },
    { first: "Marc", last: "Bartro", pos: "CB" },
    { first: "Diego", last: "Llorenta", pos: "CB" },
    { first: "Natan", last: "de Souza", pos: "CB" },
    { first: "Guido", last: "Rodrígaz", pos: "DM" },
    { first: "Johnny", last: "Cardosa", pos: "DM" },
    { first: "Isco", last: "Alarcón", pos: "AM" },
    { first: "Giovani", last: "Lo Celsa", pos: "AM" },
    { first: "Pablo", last: "Fornols", pos: "CM" },
    { first: "Abde", last: "Ezzalzouli", pos: "LW" },
    { first: "Vitor", last: "Roqua", pos: "ST" },
    { first: "Cédric", last: "Bakambu", pos: "ST" },
    { first: "Cucho", last: "Hernándaz", pos: "ST" },
  ],
  "Sevilya FC": [
    { first: "Ørjan", last: "Nylond", pos: "GK" },
    { first: "Álvaro", last: "Fernándaz", pos: "GK" },
    { first: "Juanlu", last: "Sánchaz", pos: "RB" },
    { first: "Adrià", last: "Pedrosa", pos: "LB" },
    { first: "Loïc", last: "Badé", pos: "CB" },
    { first: "Kike", last: "Salas", pos: "CB" },
    { first: "Marcão", last: "Teixeira", pos: "CB" },
    { first: "Nemanja", last: "Gudely", pos: "DM" },
    { first: "Lucien", last: "Agoumé", pos: "CM" },
    { first: "Saúl", last: "Ñíguaz", pos: "CM" },
    { first: "Djibril", last: "Sow", pos: "CM" },
    { first: "Stanis", last: "Idumbo", pos: "RW" },
    { first: "Dodi", last: "Lukébakió", pos: "RW" },
    { first: "Jesús", last: "Navos", pos: "RB" },
    { first: "Isaac", last: "Romaro", pos: "ST" },
    { first: "Akor", last: "Adoms", pos: "ST" },
  ],
  "Valenza": [
    { first: "Giorgi", last: "Mamardashvíli", pos: "GK" },
    { first: "Jaume", last: "Doménach", pos: "GK" },
    { first: "Thierry", last: "Correia", pos: "RB" },
    { first: "José", last: "Gayà", pos: "LB" },
    { first: "Cristhian", last: "Mosquara", pos: "CB" },
    { first: "Mouctar", last: "Diakhaby", pos: "CB" },
    { first: "César", last: "Tárrega", pos: "CB" },
    { first: "Pepelu", last: "Gómaz", pos: "DM" },
    { first: "Javi", last: "Guerra", pos: "CM" },
    { first: "Enzo", last: "Barrenecha", pos: "CM" },
    { first: "André", last: "Almeido", pos: "CM" },
    { first: "Diego", last: "Lópaz", pos: "RW" },
    { first: "Fran", last: "Péraz", pos: "LW" },
    { first: "Hugo", last: "Duro", pos: "ST" },
    { first: "Rafa", last: "Mir", pos: "ST" },
    { first: "Luis", last: "Riojo", pos: "LW" },
  ],
  "Girono": [
    { first: "Paulo", last: "Gazzanigo", pos: "GK" },
    { first: "Ricard", last: "Sánchaz", pos: "GK" },
    { first: "Arnau", last: "Martínaz", pos: "RB" },
    { first: "Miguel", last: "Gutiérraz", pos: "LB" },
    { first: "Daley", last: "Blynd", pos: "CB" },
    { first: "David", last: "Lópaz", pos: "CB" },
    { first: "Ladislav", last: "Krejčy", pos: "CB" },
    { first: "Yangel", last: "Herrara", pos: "DM" },
    { first: "Iván", last: "Martín", pos: "CM" },
    { first: "Aleix", last: "García", pos: "CM" },
    { first: "Yáser", last: "Asprilo", pos: "AM" },
    { first: "Bryan", last: "Gil", pos: "RW" },
    { first: "Viktor", last: "Tsygankoa", pos: "LW" },
    { first: "Cristhian", last: "Stuani", pos: "ST" },
    { first: "Abel", last: "Ruiz", pos: "ST" },
    { first: "Bojan", last: "Miovsky", pos: "ST" },
  ],
  "Celto Vigo": [
    { first: "Vicente", last: "Guaita", pos: "GK" },
    { first: "Iván", last: "Villor", pos: "GK" },
    { first: "Óscar", last: "Mingueza", pos: "RB" },
    { first: "Carl", last: "Starfelt", pos: "CB" },
    { first: "Marcos", last: "Alonso", pos: "LB" },
    { first: "Joseph", last: "Aidoa", pos: "CB" },
    { first: "Manu", last: "Fernándaz", pos: "LB" },
    { first: "Fran", last: "Beltrón", pos: "DM" },
    { first: "Ilaix", last: "Moribo", pos: "CM" },
    { first: "Hugo", last: "Sotelo", pos: "CM" },
    { first: "Luca", last: "de la Torra", pos: "CM" },
    { first: "Borja", last: "Iglesios", pos: "ST" },
    { first: "Iago", last: "Aspos", pos: "ST" },
    { first: "Williot", last: "Swedberg", pos: "LW" },
    { first: "Jonathan", last: "Bamba", pos: "RW" },
    { first: "Óscar", last: "Mardanes", pos: "RW" },
  ],
  "Osasoena": [
    { first: "Sergio", last: "Herrara", pos: "GK" },
    { first: "Aitor", last: "Fernándaz", pos: "GK" },
    { first: "Jesús", last: "Areso", pos: "RB" },
    { first: "Juan", last: "Cruz", pos: "LB" },
    { first: "Alejandro", last: "Catena", pos: "CB" },
    { first: "Unai", last: "García", pos: "CB" },
    { first: "Enzo", last: "Boyomo", pos: "CB" },
    { first: "Lucas", last: "Torró", pos: "DM" },
    { first: "Jon", last: "Moncayolo", pos: "CM" },
    { first: "Aimar", last: "Oroz", pos: "AM" },
    { first: "Moi", last: "Gómaz", pos: "CM" },
    { first: "Rubén", last: "García", pos: "AM" },
    { first: "Bryan", last: "Zaragoza", pos: "RW" },
    { first: "Ante", last: "Budimir", pos: "ST" },
    { first: "Raúl", last: "García de Haro", pos: "ST" },
    { first: "Abel", last: "Bretonas", pos: "LW" },
  ],
  "Getafa": [
    { first: "David", last: "Soria", pos: "GK" },
    { first: "Jiří", last: "Letáček", pos: "GK" },
    { first: "Damián", last: "Suáraz", pos: "RB" },
    { first: "Diego", last: "Rico", pos: "LB" },
    { first: "Domingos", last: "Duarta", pos: "CB" },
    { first: "Omar", last: "Aldarete", pos: "CB" },
    { first: "Juan", last: "Iglesios", pos: "CB" },
    { first: "Luis", last: "Milla", pos: "DM" },
    { first: "Mauro", last: "Arambarri", pos: "CM" },
    { first: "Carles", last: "Pérez", pos: "RW" },
    { first: "Yellu", last: "Santiago", pos: "AM" },
    { first: "Christantus", last: "Uche", pos: "RW" },
    { first: "Álex", last: "Sola", pos: "RB" },
    { first: "Borja", last: "Mayoral", pos: "ST" },
    { first: "Mason", last: "Greenwoot", pos: "LW" },
    { first: "Coba", last: "da Costa", pos: "ST" },
  ],
  "Rayo Vallecana": [
    { first: "Augusto", last: "Batalla", pos: "GK" },
    { first: "Dani", last: "Cárdenos", pos: "GK" },
    { first: "Andrei", last: "Rațiu", pos: "RB" },
    { first: "Pep", last: "Chavarría", pos: "LB" },
    { first: "Florian", last: "Lejeuna", pos: "CB" },
    { first: "Aridane", last: "Hernándaz", pos: "CB" },
    { first: "Abdul", last: "Mumin", pos: "CB" },
    { first: "Pathé", last: "Ciss", pos: "DM" },
    { first: "Óscar", last: "Valentín", pos: "DM" },
    { first: "Unai", last: "Lópaz", pos: "CM" },
    { first: "Isi", last: "Palazón", pos: "RW" },
    { first: "Álvaro", last: "García", pos: "LW" },
    { first: "Sergio", last: "Camella", pos: "AM" },
    { first: "Jorge", last: "de Frutos", pos: "RW" },
    { first: "Randy", last: "Nteka", pos: "ST" },
    { first: "Raúl", last: "de Tomás", pos: "ST" },
  ],
  "Mallorco": [
    { first: "Dominik", last: "Greif", pos: "GK" },
    { first: "Leo", last: "Romàn", pos: "GK" },
    { first: "Pablo", last: "Maffeo", pos: "RB" },
    { first: "Johan", last: "Mojica", pos: "LB" },
    { first: "Antonio", last: "Raíllo", pos: "CB" },
    { first: "Martin", last: "Valjent", pos: "CB" },
    { first: "Marash", last: "Kumbulla", pos: "CB" },
    { first: "Sergi", last: "Darder", pos: "CM" },
    { first: "Antonio", last: "Sánchaz", pos: "DM" },
    { first: "Manu", last: "Moriana", pos: "CM" },
    { first: "Samú", last: "Costa", pos: "DM" },
    { first: "Dani", last: "Rodrígaz", pos: "AM" },
    { first: "Mateo", last: "Jaume", pos: "RW" },
    { first: "Vedat", last: "Muriqi", pos: "ST" },
    { first: "Cyle", last: "Larin", pos: "ST" },
    { first: "Abdón", last: "Prats", pos: "ST" },
  ],
  "Leganez": [
    { first: "Marko", last: "Dmitrović", pos: "GK" },
    { first: "Juan", last: "Soriano", pos: "GK" },
    { first: "Valentin", last: "Rosier", pos: "RB" },
    { first: "Jorge", last: "Sáenz", pos: "CB" },
    { first: "Sergio", last: "Gonzálaz", pos: "CB" },
    { first: "Matija", last: "Nastasić", pos: "CB" },
    { first: "Renato", last: "Tapia", pos: "DM" },
    { first: "Seydouba", last: "Cissé", pos: "DM" },
    { first: "Yvan", last: "Neyou", pos: "CM" },
    { first: "Darko", last: "Brašanac", pos: "CM" },
    { first: "Juan", last: "Cruz", pos: "LW" },
    { first: "Munir", last: "El Haddady", pos: "RW" },
    { first: "Óscar", last: "Rodrígaz", pos: "AM" },
    { first: "Dani", last: "Raba", pos: "LW" },
    { first: "Miguel", last: "de la Fuenta", pos: "ST" },
    { first: "Juan", last: "Diego", pos: "ST" },
  ],

  // ===== Liga Esp 2 =====
  "Esponyol": [
    { first: "Joan", last: "García", pos: "GK" },
    { first: "Fernando", last: "Pacheca", pos: "GK" },
    { first: "Omar", last: "El Hilali", pos: "RB" },
    { first: "Brian", last: "Olivàn", pos: "LB" },
    { first: "Leandro", last: "Cabrera", pos: "CB" },
    { first: "Sergi", last: "Gómaz", pos: "CB" },
    { first: "Fernando", last: "Calero", pos: "CB" },
    { first: "Pol", last: "Lozana", pos: "DM" },
    { first: "Edu", last: "Expósita", pos: "CM" },
    { first: "Javi", last: "Puado", pos: "AM" },
    { first: "Jofre", last: "Carreras", pos: "RW" },
    { first: "Pere", last: "Milla", pos: "LW" },
    { first: "Álvaro", last: "Aguada", pos: "CM" },
    { first: "Roberto", last: "Fernándaz", pos: "ST" },
    { first: "Alejo", last: "Véliz", pos: "ST" },
    { first: "Irvin", last: "Cardona", pos: "ST" },
  ],
  "Real Vallodolid": [
    { first: "Karl", last: "Hein", pos: "GK" },
    { first: "André", last: "Ferreira", pos: "GK" },
    { first: "Luis", last: "Pérez", pos: "RB" },
    { first: "David", last: "Torras", pos: "LB" },
    { first: "Javi", last: "Sánchaz", pos: "CB" },
    { first: "Cenk", last: "Özkaçar", pos: "CB" },
    { first: "Eray", last: "Cömert", pos: "CB" },
    { first: "Kike", last: "Pérez", pos: "DM" },
    { first: "Mario", last: "Martín", pos: "CM" },
    { first: "Stipe", last: "Biuk", pos: "RW" },
    { first: "Amath", last: "Ndiaya", pos: "LW" },
    { first: "Iván", last: "Sánchaz", pos: "AM" },
    { first: "Raúl", last: "Moro", pos: "RW" },
    { first: "Marcos", last: "André", pos: "ST" },
    { first: "Juanmi", last: "Latasa", pos: "ST" },
    { first: "Gonzalo", last: "Almenara", pos: "ST" },
  ],
  "Deportiva Coruna": [
    { first: "Germán", last: "Parreño", pos: "GK" },
    { first: "Daniel", last: "Bachmonn", pos: "GK" },
    { first: "Ximo", last: "Navarra", pos: "RB" },
    { first: "José", last: "Gragera", pos: "LB" },
    { first: "Pablo", last: "Martínaz", pos: "CB" },
    { first: "Dani", last: "Barcia", pos: "CB" },
    { first: "Loïc", last: "Williöms", pos: "CB" },
    { first: "Mario", last: "Soriana", pos: "DM" },
    { first: "Charlie", last: "Patiño", pos: "CM" },
    { first: "Mella", last: "Yeremay", pos: "RW" },
    { first: "Diego", last: "Villares", pos: "CM" },
    { first: "David", last: "Mella", pos: "RW" },
    { first: "Lucas", last: "Pérez", pos: "ST" },
    { first: "Davit", last: "Zoubir", pos: "LW" },
    { first: "Mfulu", last: "Gauthier", pos: "DM" },
    { first: "Hugo", last: "Rama", pos: "AM" },
  ],
  "Sporting Gijonn": [
    { first: "Rubén", last: "Yáñaz", pos: "GK" },
    { first: "Christian", last: "Joel", pos: "GK" },
    { first: "Kevin", last: "Vázquaz", pos: "RB" },
    { first: "Guille", last: "Rosas", pos: "RB" },
    { first: "Jonathan", last: "Dubasin", pos: "LB" },
    { first: "Nacho", last: "Méndaz", pos: "CB" },
    { first: "Pablo", last: "Insua", pos: "CB" },
    { first: "Nacho", last: "Martín", pos: "DM" },
    { first: "Dani", last: "Queipo", pos: "CM" },
    { first: "Gaspar", last: "Campos", pos: "RW" },
    { first: "Juan", last: "Otero", pos: "LW" },
    { first: "Hassan", last: "Yamal", pos: "AM" },
    { first: "Corredera", last: "Pelayo", pos: "CM" },
    { first: "Juan", last: "Berrocal", pos: "CB" },
    { first: "Dejan", last: "Stojkovíc", pos: "ST" },
    { first: "Otero", last: "Caicedo", pos: "ST" },
  ],
  "Real Zaragosa": [
    { first: "Andrés", last: "Fernándaz", pos: "GK" },
    { first: "Adrián", last: "Rodrígaz", pos: "GK" },
    { first: "Jair", last: "Amador", pos: "CB" },
    { first: "Saidu", last: "Sow", pos: "CB" },
    { first: "Carlos", last: "Pomares", pos: "LB" },
    { first: "Tasende", last: "Borja", pos: "RB" },
    { first: "Francho", last: "Serrano", pos: "DM" },
    { first: "Marcos", last: "Cuenca", pos: "CM" },
    { first: "Pau", last: "Sans", pos: "CM" },
    { first: "Iván", last: "Azón", pos: "ST" },
    { first: "Sebas", last: "Moyano", pos: "RW" },
    { first: "Bazdar", last: "Samed", pos: "ST" },
    { first: "Soberón", last: "Adrián", pos: "ST" },
    { first: "Raúl", last: "Guti", pos: "AM" },
    { first: "Toni", last: "Moya", pos: "CM" },
    { first: "Lluís", last: "López", pos: "CB" },
  ],
  "Levanta": [
    { first: "Andrés", last: "Fernándaz", pos: "GK" },
    { first: "Pablo", last: "Cuñat", pos: "GK" },
    { first: "Jeremy", last: "Toljón", pos: "RB" },
    { first: "Diego", last: "Pampín", pos: "LB" },
    { first: "Unai", last: "Elgezabol", pos: "CB" },
    { first: "Matías", last: "Moreno", pos: "CB" },
    { first: "Óscar", last: "Clemente", pos: "CB" },
    { first: "Vicente", last: "Iborra", pos: "DM" },
    { first: "Pablo", last: "Martínaz", pos: "CM" },
    { first: "Carlos", last: "Álvaraz", pos: "AM" },
    { first: "José", last: "Morales", pos: "LW" },
    { first: "Brugué", last: "Carlos", pos: "RW" },
    { first: "Roger", last: "Brugué", pos: "RW" },
    { first: "Jorge", last: "de Frutos", pos: "LW" },
    { first: "Iván", last: "Romero", pos: "ST" },
    { first: "Wisdom", last: "Mike", pos: "ST" },
  ],
  "Almeria UD": [
    { first: "Andrés", last: "Fernándaz", pos: "GK" },
    { first: "Fernando", last: "Martínaz", pos: "GK" },
    { first: "Marc", last: "Pubill", pos: "RB" },
    { first: "Alex", last: "Centelles", pos: "LB" },
    { first: "Edgar", last: "Gonzálaz", pos: "CB" },
    { first: "Chumi", last: "Díaz", pos: "CB" },
    { first: "Kaiky", last: "Fernandas", pos: "CB" },
    { first: "Lucas", last: "Robertona", pos: "DM" },
    { first: "Melero", last: "Lópaz", pos: "CM" },
    { first: "Gui", last: "Guedes", pos: "CM" },
    { first: "Luis", last: "Suáraz", pos: "RW" },
    { first: "Arnau", last: "Puigmal", pos: "AM" },
    { first: "Dion", last: "Lopy", pos: "DM" },
    { first: "Leo", last: "Baptistão", pos: "ST" },
    { first: "Adrián", last: "Embarba", pos: "LW" },
    { first: "Sergio", last: "Arribas", pos: "ST" },
  ],
  "Granado CF": [
    { first: "Luca", last: "Zidana", pos: "GK" },
    { first: "Ander", last: "Astralaga", pos: "GK" },
    { first: "Óscar", last: "Naasei", pos: "RB" },
    { first: "Manu", last: "Lama", pos: "LB" },
    { first: "Miguel", last: "Rubio", pos: "CB" },
    { first: "Diego", last: "Hormigo", pos: "CB" },
    { first: "Loïc", last: "Williöms", pos: "CB" },
    { first: "Sergio", last: "Ruiz", pos: "DM" },
    { first: "Gonzalo", last: "Villar", pos: "CM" },
    { first: "Pablo", last: "Insua", pos: "CB" },
    { first: "Faye", last: "Pape Mor", pos: "CM" },
    { first: "Bouldini", last: "Myrto", pos: "ST" },
    { first: "Stoichkov", last: "Jorge", pos: "RW" },
    { first: "Jesús", last: "Bouldini", pos: "ST" },
    { first: "Lucas", last: "Boyé", pos: "ST" },
    { first: "Manu", last: "Trigueros", pos: "AM" },
  ],
  "Cadyz": [
    { first: "David", last: "Gil", pos: "GK" },
    { first: "Víctor", last: "Aznar", pos: "GK" },
    { first: "Iza", last: "Carcelén", pos: "RB" },
    { first: "Javi", last: "Hernándaz", pos: "LB" },
    { first: "Fali", last: "Jiménaz", pos: "CB" },
    { first: "Víctor", last: "Chust", pos: "CB" },
    { first: "Jorge", last: "Moreno", pos: "CB" },
    { first: "Rubén", last: "Alcaraz", pos: "DM" },
    { first: "José", last: "Mari", pos: "CM" },
    { first: "Iván", last: "Alejo", pos: "RW" },
    { first: "Brian", last: "Ocampo", pos: "LW" },
    { first: "Suso", last: "Fernándaz", pos: "AM" },
    { first: "Álex", last: "Fernándaz", pos: "CM" },
    { first: "Chris", last: "Ramos", pos: "ST" },
    { first: "Roger", last: "Martí", pos: "ST" },
    { first: "Ontiveros", last: "Javier", pos: "LW" },
  ],
  "Malaga CF": [
    { first: "Alfonso", last: "Herrero", pos: "GK" },
    { first: "Carlos", last: "López", pos: "GK" },
    { first: "Carlos", last: "Puga", pos: "RB" },
    { first: "Víctor", last: "Gollán", pos: "LB" },
    { first: "Einar", last: "Galilea", pos: "CB" },
    { first: "Murillo", last: "Nélson", pos: "CB" },
    { first: "Javi", last: "Montero", pos: "CB" },
    { first: "Luca", last: "Sangalli", pos: "DM" },
    { first: "Dani", last: "Lorenzo", pos: "CM" },
    { first: "Juanpe", last: "Rengifa", pos: "CM" },
    { first: "Kevin", last: "Medina", pos: "LW" },
    { first: "Larrubia", last: "Antoñito", pos: "RW" },
    { first: "Dioni", last: "Arroyo", pos: "ST" },
    { first: "Roberto", last: "Fernándaz", pos: "ST" },
    { first: "Chupete", last: "David", pos: "ST" },
    { first: "Ramón", last: "Enríquaz", pos: "AM" },
  ],
  "Racing Santandar": [
    { first: "Jokin", last: "Ezkieta", pos: "GK" },
    { first: "Pedro", last: "López", pos: "GK" },
    { first: "Álvaro", last: "Mantilla", pos: "RB" },
    { first: "Javi", last: "Castro", pos: "LB" },
    { first: "Germán", last: "Sánchaz", pos: "CB" },
    { first: "Manu", last: "Hernandó", pos: "CB" },
    { first: "Saúl", last: "García", pos: "LB" },
    { first: "Aldasoro", last: "Iñigo", pos: "DM" },
    { first: "Mario", last: "García", pos: "CM" },
    { first: "Jeremy", last: "Arévalo", pos: "ST" },
    { first: "Andrés", last: "Martín", pos: "RW" },
    { first: "Iñigo", last: "Vicente", pos: "AM" },
    { first: "Juan", last: "Carlos Arana", pos: "LW" },
    { first: "Asier", last: "Villalibre", pos: "ST" },
    { first: "Karrikaburu", last: "Jon", pos: "ST" },
    { first: "Pablo", last: "Rodrígaz", pos: "CM" },
  ],
  "Oviedra": [
    { first: "Aarón", last: "Escandell", pos: "GK" },
    { first: "Leo", last: "Román", pos: "GK" },
    { first: "Lucas", last: "Ahijón", pos: "RB" },
    { first: "Rahim", last: "Alhassana", pos: "LB" },
    { first: "Dani", last: "Calvo", pos: "CB" },
    { first: "David", last: "Costas", pos: "CB" },
    { first: "Oier", last: "Luengo", pos: "CB" },
    { first: "Sebas", last: "Moyano", pos: "DM" },
    { first: "Colombatto", last: "Santiago", pos: "CM" },
    { first: "Jaime", last: "Seoana", pos: "CM" },
    { first: "Borja", last: "Sánchaz", pos: "AM" },
    { first: "Cazorla", last: "Santi", pos: "AM" },
    { first: "Álex", last: "Cardero", pos: "RW" },
    { first: "Borja", last: "Bastón", pos: "ST" },
    { first: "Fede", last: "Viñas", pos: "ST" },
    { first: "Haissem", last: "Hassana", pos: "LW" },
  ],
  "Huesco": [
    { first: "Dani", last: "Jiménaz", pos: "GK" },
    { first: "Sergio", last: "Herrera", pos: "GK" },
    { first: "Jorge", last: "Pulido", pos: "CB" },
    { first: "Gerard", last: "Valentín", pos: "RB" },
    { first: "Pablo", last: "Maffeo", pos: "RB" },
    { first: "Jordi", last: "Martín", pos: "LB" },
    { first: "Andrei", last: "Rațiu", pos: "CB" },
    { first: "Sergio", last: "Pulido", pos: "DM" },
    { first: "Joaquín", last: "Muñoz", pos: "CM" },
    { first: "Dani", last: "Ojeda", pos: "AM" },
    { first: "Óscar", last: "Sielva", pos: "CM" },
    { first: "Kortajarena", last: "Iker", pos: "RW" },
    { first: "Soko", last: "Adekanya", pos: "ST" },
    { first: "Enol", last: "Rodrígaz", pos: "LW" },
    { first: "Dani", last: "Luna", pos: "ST" },
    { first: "Obeng", last: "Samuel", pos: "ST" },
  ],
  "Elcha CF": [
    { first: "Matías", last: "Dituro", pos: "GK" },
    { first: "Iñaki", last: "Peña", pos: "GK" },
    { first: "Héctor", last: "Fort", pos: "RB" },
    { first: "John", last: "Donald", pos: "LB" },
    { first: "Pedro", last: "Bigas", pos: "CB" },
    { first: "Víctor", last: "Chust", pos: "CB" },
    { first: "Adrià", last: "Pedrosa", pos: "LB" },
    { first: "Aleix", last: "Febas", pos: "DM" },
    { first: "Marc", last: "Aguada", pos: "CM" },
    { first: "Josan", last: "Ferrández", pos: "RW" },
    { first: "Rodrigo", last: "Mendoza", pos: "CM" },
    { first: "André", last: "Silva", pos: "AM" },
    { first: "Mourad", last: "El Ghezouani", pos: "LW" },
    { first: "Fede", last: "Redondo", pos: "ST" },
    { first: "Rafa", last: "Mir", pos: "ST" },
    { first: "Álvaro", last: "Rodríguaz", pos: "ST" },
  ],
  "Burgas CF": [
    { first: "Ramón", last: "Vázquaz", pos: "GK" },
    { first: "Mikel", last: "Saizar", pos: "GK" },
    { first: "Iván", last: "Chapela", pos: "RB" },
    { first: "Florian", last: "Miguel", pos: "RB" },
    { first: "Grego", last: "Sierra", pos: "CB" },
    { first: "Mario", last: "González", pos: "CB" },
    { first: "Aitor", last: "Córdoba", pos: "CB" },
    { first: "David", last: "González", pos: "LB" },
    { first: "Mateo", last: "Mejía", pos: "DM" },
    { first: "Iñigo", last: "Córdoba", pos: "AM" },
    { first: "Fermín", last: "Sánchaz", pos: "CM" },
    { first: "Curro", last: "Sánchaz", pos: "RW" },
    { first: "Borja", last: "González", pos: "LW" },
    { first: "Fer", last: "Niño", pos: "ST" },
    { first: "Iván", last: "Morante", pos: "ST" },
    { first: "Dani", last: "Ojeda", pos: "AM" },
  ],
  "Eldenze": [
    { first: "Edgar", last: "Badía", pos: "GK" },
    { first: "Simón", last: "Moreno", pos: "GK" },
    { first: "Marcos", last: "Mauro", pos: "CB" },
    { first: "Sergio", last: "Hernándaz", pos: "RB" },
    { first: "Diego", last: "González", pos: "CB" },
    { first: "Jair", last: "Amador", pos: "CB" },
    { first: "Fran", last: "Gámez", pos: "LB" },
    { first: "Toni", last: "Gabarra", pos: "DM" },
    { first: "Adri", last: "Gené", pos: "CM" },
    { first: "Nono", last: "Fernándaz", pos: "AM" },
    { first: "Sergio", last: "Ortuño", pos: "CM" },
    { first: "Juanto", last: "Ortuño", pos: "RW" },
    { first: "Sékou", last: "Gassama", pos: "LW" },
    { first: "Bryan", last: "Carrasco", pos: "AM" },
    { first: "David", last: "Timor", pos: "ST" },
    { first: "Owusu", last: "Kwame", pos: "ST" },
  ],
};
