import type { ClubSquadMap } from "./types.js";

export const SQUADS_FRA: ClubSquadMap = {
  // ===================== Ligue Un =====================
  "Paris Saint-Germond": [
    { first: "Gianluígi", last: "Donaruma", pos: "GK" },
    { first: "Matveí", last: "Safonné", pos: "GK" },
    { first: "Achráf", last: "Hakími", pos: "RB" },
    { first: "Núno", last: "Mendès", pos: "LB" },
    { first: "Marquínos", last: "Correa", pos: "CB" },
    { first: "Willián", last: "Pacho", pos: "CB" },
    { first: "Lúcas", last: "Beralto", pos: "CB" },
    { first: "Vitínya", last: "Ferreíra", pos: "DM" },
    { first: "Joáo", last: "Neves", pos: "CM" },
    { first: "Fabián", last: "Ruíz", pos: "CM" },
    { first: "Warren", last: "Zaïre-Emory", pos: "CM" },
    { first: "Ousmáne", last: "Dembély", pos: "RW" },
    { first: "Khvícha", last: "Kvaratskhella", pos: "LW" },
    { first: "Bradley", last: "Barcóla", pos: "LW" },
    { first: "Désiré", last: "Doué", pos: "AM" },
    { first: "Gonçálo", last: "Ramos", pos: "ST" },
  ],
  "Olympia Marseyu": [
    { first: "Gerónimo", last: "Rullí", pos: "GK" },
    { first: "Jeffrey", last: "de Lange", pos: "GK" },
    { first: "Amir", last: "Murilló", pos: "RB" },
    { first: "Quentín", last: "Merlín", pos: "LB" },
    { first: "Leonardó", last: "Balerdo", pos: "CB" },
    { first: "Geoffrey", last: "Kondogbí", pos: "CB" },
    { first: "Derek", last: "Cornelló", pos: "DM" },
    { first: "Pierre-Émile", last: "Hojberg", pos: "DM" },
    { first: "Adrién", last: "Rabíot", pos: "CM" },
    { first: "Valentín", last: "Rongiér", pos: "CM" },
    { first: "Mason", last: "Greenwald", pos: "RW" },
    { first: "Amíne", last: "Gouírí", pos: "AM" },
    { first: "Luís", last: "Henríque", pos: "LW" },
    { first: "Neal", last: "Maupý", pos: "ST" },
    { first: "Faríss", last: "Moumbagná", pos: "ST" },
    { first: "Robínio", last: "Vas", pos: "RW" },
  ],
  "Olympia Lyonne": [
    { first: "Lúcas", last: "Pérri", pos: "GK" },
    { first: "Rémy", last: "Descamp", pos: "GK" },
    { first: "Saël", last: "Kumbedó", pos: "RB" },
    { first: "Nicolás", last: "Tagliáfico", pos: "LB" },
    { first: "Móussa", last: "Niakhaté", pos: "CB" },
    { first: "Dúje", last: "Caleta-Cara", pos: "CB" },
    { first: "Clínton", last: "Mata", pos: "CB" },
    { first: "Corentín", last: "Tolissó", pos: "DM" },
    { first: "Tanner", last: "Tessmán", pos: "CM" },
    { first: "Némo", last: "Gusto", pos: "RB" },
    { first: "Maxénce", last: "Caquerot", pos: "AM" },
    { first: "Rayan", last: "Cherkí", pos: "AM" },
    { first: "Malick", last: "Fofaná", pos: "RW" },
    { first: "Georges", last: "Mikautadzé", pos: "ST" },
    { first: "Alexandre", last: "Lacazét", pos: "ST" },
    { first: "Ernest", last: "Nuamó", pos: "LW" },
  ],
  "Monacco": [
    { first: "Radosláw", last: "Majécki", pos: "GK" },
    { first: "Philipp", last: "Köhn", pos: "GK" },
    { first: "Vandersón", last: "Lima", pos: "RB" },
    { first: "Caió", last: "Henríque", pos: "LB" },
    { first: "Thilo", last: "Kehrér", pos: "CB" },
    { first: "Wilfried", last: "Singó", pos: "CB" },
    { first: "Mohámed", last: "Salisú", pos: "CB" },
    { first: "Denís", last: "Zakaría", pos: "DM" },
    { first: "Lamine", last: "Camará", pos: "CM" },
    { first: "Aleksándr", last: "Golovín", pos: "AM" },
    { first: "Maghnes", last: "Akliouché", pos: "AM" },
    { first: "Takumi", last: "Minamíno", pos: "AM" },
    { first: "Eliesse", last: "Ben Seghír", pos: "RW" },
    { first: "Folarín", last: "Balogún", pos: "ST" },
    { first: "Breel", last: "Emboló", pos: "ST" },
    { first: "George", last: "Iléniky", pos: "ST" },
  ],
  "Lille OSV": [
    { first: "Lúcas", last: "Chevaliér", pos: "GK" },
    { first: "Vito", last: "Mannóne", pos: "GK" },
    { first: "Thomás", last: "Meuniér", pos: "RB" },
    { first: "Ismaily", last: "Gonçalves", pos: "LB" },
    { first: "Bafodé", last: "Diakité", pos: "CB" },
    { first: "Aïssa", last: "Mandí", pos: "CB" },
    { first: "Alexsándro", last: "Ribéiro", pos: "CB" },
    { first: "Benjamín", last: "André", pos: "DM" },
    { first: "Angel", last: "Gomes", pos: "CM" },
    { first: "Ngal", last: "Ayyoub", pos: "CM" },
    { first: "Hákon", last: "Haraldssón", pos: "AM" },
    { first: "Edon", last: "Zhegróva", pos: "RW" },
    { first: "Matías", last: "Fernández-Pardo", pos: "LW" },
    { first: "Osáme", last: "Sahraouí", pos: "LW" },
    { first: "Jonathán", last: "David", pos: "ST" },
    { first: "Mohámed", last: "Bayó", pos: "ST" },
  ],
  "Rennais": [
    { first: "Brice", last: "Samba", pos: "GK" },
    { first: "Gauthier", last: "Galón", pos: "GK" },
    { first: "Lorénz", last: "Assignón", pos: "RB" },
    { first: "Adrién", last: "Truffert", pos: "LB" },
    { first: "Christophér", last: "Wooh", pos: "CB" },
    { first: "Mikayil", last: "Faye", pos: "CB" },
    { first: "Brendan", last: "Chardonnét", pos: "CB" },
    { first: "Azor", last: "Matusíwa", pos: "DM" },
    { first: "Djaoui", last: "Cissé", pos: "CM" },
    { first: "Ludovíc", last: "Blas", pos: "AM" },
    { first: "Albert", last: "Grönbaek", pos: "AM" },
    { first: "Kalimuendó", last: "Muinga", pos: "ST" },
    { first: "Estebán", last: "Lepaúl", pos: "ST" },
    { first: "Henrík", last: "Meister", pos: "ST" },
    { first: "Jordán", last: "James", pos: "CM" },
    { first: "Seko", last: "Fofaná", pos: "DM" },
  ],
  "Nicea": [
    { first: "Marcín", last: "Bulka", pos: "GK" },
    { first: "Yehvann", last: "Diouf", pos: "GK" },
    { first: "Jordán", last: "Lotomba", pos: "RB" },
    { first: "Melvín", last: "Bard", pos: "LB" },
    { first: "Dante", last: "Bonfím", pos: "CB" },
    { first: "Jean-Clair", last: "Todibó", pos: "CB" },
    { first: "Antoíne", last: "Mendý", pos: "CB" },
    { first: "Hicham", last: "Boudaouí", pos: "DM" },
    { first: "Morgan", last: "Sansón", pos: "CM" },
    { first: "Pablo", last: "Rosário", pos: "CM" },
    { first: "Tom", last: "Louchét", pos: "AM" },
    { first: "Jérémie", last: "Boga", pos: "RW" },
    { first: "Sofiane", last: "Diop", pos: "AM" },
    { first: "Gaëtan", last: "Laborde", pos: "ST" },
    { first: "Evann", last: "Guessánd", pos: "ST" },
    { first: "Mohámed-Ali", last: "Cho", pos: "LW" },
  ],
  "Lens Sang et Or": [
    { first: "Brice", last: "Samboa", pos: "GK" },
    { first: "Robin", last: "Risser", pos: "GK" },
    { first: "Jonathán", last: "Gradít", pos: "RB" },
    { first: "Deivíd", last: "Costa", pos: "LB" },
    { first: "Kévin", last: "Danso", pos: "CB" },
    { first: "Facúndo", last: "Medína", pos: "CB" },
    { first: "Malang", last: "Sarr", pos: "CB" },
    { first: "Andy", last: "Diouf", pos: "DM" },
    { first: "Adrién", last: "Thomassón", pos: "CM" },
    { first: "Neil", last: "El Aynaouí", pos: "CM" },
    { first: "Angelo", last: "Fulgíni", pos: "AM" },
    { first: "Florián", last: "Sotóca", pos: "RW" },
    { first: "Wesley", last: "Saïd", pos: "LW" },
    { first: "Przemyslaw", last: "Frankowsk", pos: "RB" },
    { first: "M'Bala", last: "Nzola", pos: "ST" },
    { first: "Rémy", last: "Labeaú", pos: "ST" },
  ],
  "Strasburg": [
    { first: "Mike", last: "Pendérs", pos: "GK" },
    { first: "Djordje", last: "Petróvic", pos: "GK" },
    { first: "Guéla", last: "Doué", pos: "RB" },
    { first: "Mamadóu", last: "Sarr", pos: "CB" },
    { first: "Saïdou", last: "Sow", pos: "CB" },
    { first: "Abakár", last: "Sylla", pos: "CB" },
    { first: "Marvín", last: "Senayá", pos: "RB" },
    { first: "Habib", last: "Diarrá", pos: "CM" },
    { first: "Ismaël", last: "Doukouré", pos: "DM" },
    { first: "Dilane", last: "Bakwá", pos: "RW" },
    { first: "Sebastián", last: "Nanasí", pos: "AM" },
    { first: "Andrey", last: "Santos", pos: "CM" },
    { first: "Caleb", last: "Wiley", pos: "LB" },
    { first: "Emanuel", last: "Emegha", pos: "ST" },
    { first: "Félix", last: "Lemaréchal", pos: "AM" },
    { first: "Diego", last: "Moreíra", pos: "LW" },
  ],
  "Nantais": [
    { first: "Anthony", last: "Lopés", pos: "GK" },
    { first: "Patrik", last: "Carlgrén", pos: "GK" },
    { first: "Jean-Charles", last: "Castelletó", pos: "CB" },
    { first: "Nicolás", last: "Pallois", pos: "CB" },
    { first: "Tylel", last: "Tatí", pos: "CB" },
    { first: "Johann", last: "Lepenant", pos: "DM" },
    { first: "Junior", last: "Mwanga", pos: "DM" },
    { first: "Moses", last: "Simón", pos: "RW" },
    { first: "Mostafá", last: "Mohamád", pos: "AM" },
    { first: "Florént", last: "Mollet", pos: "AM" },
    { first: "Sorba", last: "Thomás", pos: "RW" },
    { first: "Matthis", last: "Abline", pos: "ST" },
    { first: "Mathéo", last: "Pellenard", pos: "LB" },
    { first: "Bahereba", last: "Guirassý", pos: "LW" },
    { first: "Herba", last: "Guirassý", pos: "ST" },
    { first: "Kelvín", last: "Amián", pos: "RB" },
  ],
  "Montpelliar": [
    { first: "Benjamín", last: "Lecomt", pos: "GK" },
    { first: "Dimitry", last: "Bertaúd", pos: "GK" },
    { first: "Issiagá", last: "Sylla", pos: "LB" },
    { first: "Kiki", last: "Kouyatée", pos: "CB" },
    { first: "Théo", last: "Sainté-Luce", pos: "CB" },
    { first: "Enzó", last: "Tchato", pos: "RB" },
    { first: "Falaye", last: "Sacko", pos: "RB" },
    { first: "Joris", last: "Chotard", pos: "DM" },
    { first: "Jordan", last: "Ferrí", pos: "CM" },
    { first: "Téji", last: "Savaniér", pos: "AM" },
    { first: "Khalil", last: "Fayad", pos: "AM" },
    { first: "Becir", last: "Omeragíc", pos: "CB" },
    { first: "Arnaúd", last: "Nordín", pos: "RW" },
    { first: "Musa", last: "Al-Taamarí", pos: "RW" },
    { first: "Akor", last: "Adams", pos: "ST" },
    { first: "Wahbí", last: "Khazrí", pos: "AM" },
  ],
  "Brestois": [
    { first: "Marco", last: "Bizót", pos: "GK" },
    { first: "Grégoire", last: "Coudert", pos: "GK" },
    { first: "Kenny", last: "Lala", pos: "RB" },
    { first: "Bradley", last: "Locko", pos: "LB" },
    { first: "Brendan", last: "Chardonné", pos: "CB" },
    { first: "Lilian", last: "Brassiér", pos: "CB" },
    { first: "Soumaíla", last: "Coulibály", pos: "CB" },
    { first: "Pierre", last: "Lees-Melóu", pos: "CM" },
    { first: "Hugo", last: "Magnetti", pos: "DM" },
    { first: "Mahdí", last: "Camará", pos: "DM" },
    { first: "Romaín", last: "Del Castillo", pos: "AM" },
    { first: "Kamory", last: "Doumbiá", pos: "AM" },
    { first: "Ludovíc", last: "Ajorqué", pos: "ST" },
    { first: "Abdállah", last: "Sima", pos: "RW" },
    { first: "Jérémy", last: "Le Douaron", pos: "ST" },
    { first: "Mama", last: "Baldé", pos: "LW" },
  ],
  "Toulose": [
    { first: "Guillaume", last: "Restés", pos: "GK" },
    { first: "Alban", last: "Lafónt", pos: "GK" },
    { first: "Rasmus", last: "Nicolaisén", pos: "CB" },
    { first: "Kévin", last: "Keben-Mbappé", pos: "CB" },
    { first: "Charlie", last: "Cresswéll", pos: "CB" },
    { first: "Gabriel", last: "Suazó", pos: "LB" },
    { first: "Mikkél", last: "Desler", pos: "RB" },
    { first: "Vincent", last: "Sierro", pos: "CM" },
    { first: "Stijn", last: "Spierings", pos: "DM" },
    { first: "Cristián", last: "Cásseres", pos: "CM" },
    { first: "Aron", last: "Donnúm", pos: "RW" },
    { first: "Yann", last: "Gboho", pos: "AM" },
    { first: "Frank", last: "Magrí", pos: "ST" },
    { first: "Joshua", last: "King", pos: "ST" },
    { first: "Zakaria", last: "Aboukhlál", pos: "RW" },
    { first: "Shavy", last: "Babícka", pos: "LW" },
  ],
  "Reimes": [
    { first: "Yehvann", last: "Diouf", pos: "GK" },
    { first: "Aymeríc", last: "Gillot", pos: "GK" },
    { first: "Sergi", last: "Akiéme", pos: "LB" },
    { first: "Yunis", last: "Abdelhamíd", pos: "CB" },
    { first: "Emmanuel", last: "Agbadoú", pos: "CB" },
    { first: "Maxíme", last: "Busi", pos: "RB" },
    { first: "Thibault", last: "De Smet", pos: "LB" },
    { first: "Marshall", last: "Munetsí", pos: "CM" },
    { first: "Valentín", last: "Atangana", pos: "DM" },
    { first: "Amir", last: "Richardsón", pos: "CM" },
    { first: "Junya", last: "Itó", pos: "RW" },
    { first: "Keito", last: "Nakamúra", pos: "LW" },
    { first: "Mohámed", last: "Daramý", pos: "AM" },
    { first: "Oumár", last: "Diakité", pos: "ST" },
    { first: "Teddy", last: "Teumá", pos: "AM" },
    { first: "Mamadóu", last: "Diakhón", pos: "RW" },
  ],
  "Le Havra": [
    { first: "Mory", last: "Diaw", pos: "GK" },
    { first: "Arthur", last: "Desmas", pos: "GK" },
    { first: "Arouna", last: "Sangante", pos: "CB" },
    { first: "Étienne", last: "Youté", pos: "CB" },
    { first: "Gautier", last: "Lloris", pos: "CB" },
    { first: "Yoann", last: "Salmiér", pos: "RB" },
    { first: "Christopher", last: "Operí", pos: "LB" },
    { first: "Daler", last: "Kuzyaév", pos: "CM" },
    { first: "Rassoul", last: "Ndiaye", pos: "DM" },
    { first: "Yassíne", last: "Kechtá", pos: "AM" },
    { first: "Abdoulaye", last: "Touré", pos: "CM" },
    { first: "Issa", last: "Soumaré", pos: "RW" },
    { first: "Simon", last: "Ebonóg", pos: "AM" },
    { first: "André", last: "Ayew", pos: "ST" },
    { first: "Josué", last: "Casimír", pos: "ST" },
    { first: "Steve", last: "Ngoura", pos: "ST" },
  ],
  "Auxerra": [
    { first: "Donovan", last: "Léon", pos: "GK" },
    { first: "Théo", last: "De Percin", pos: "GK" },
    { first: "Paul", last: "Joly", pos: "RB" },
    { first: "Jubal", last: "Da Silva", pos: "CB" },
    { first: "Clément", last: "Akpa", pos: "CB" },
    { first: "Sinaly", last: "Diomandé", pos: "CB" },
    { first: "Gideon", last: "Mensáh", pos: "LB" },
    { first: "Lassine", last: "Sinayoko", pos: "RW" },
    { first: "Gaëtan", last: "Perrín", pos: "AM" },
    { first: "Hamed", last: "Traorée", pos: "CM" },
    { first: "Elisha", last: "Owusú", pos: "DM" },
    { first: "Kévin", last: "Danois", pos: "CM" },
    { first: "Rayan", last: "Raveloson", pos: "DM" },
    { first: "Mamadou", last: "Sangaré", pos: "CM" },
    { first: "Danay", last: "Sinama-Pongolle", pos: "ST" },
    { first: "Théo", last: "Bair", pos: "ST" },
  ],

  // ===================== Ligue Deux =====================
  "Saint-Etiana": [
    { first: "Gautier", last: "Larsonneúr", pos: "GK" },
    { first: "Brice", last: "Maúbleu", pos: "GK" },
    { first: "Yvann", last: "Macón", pos: "RB" },
    { first: "Dylan", last: "Batubinsíka", pos: "CB" },
    { first: "Mickaël", last: "Nadé", pos: "CB" },
    { first: "Anthony", last: "Briançón", pos: "CB" },
    { first: "Yunis", last: "Abdelhamíd", pos: "CB" },
    { first: "Pierre", last: "Ekwah", pos: "DM" },
    { first: "Florián", last: "Tardieu", pos: "CM" },
    { first: "Aïmen", last: "Moueffek", pos: "CM" },
    { first: "Lucas", last: "Stassín", pos: "ST" },
    { first: "Zuriko", last: "Davitashvíli", pos: "LW" },
    { first: "Irvín", last: "Cardóna", pos: "ST" },
    { first: "Ben", last: "Old", pos: "AM" },
    { first: "Augustíne", last: "Boakye", pos: "RW" },
    { first: "Ibrahím", last: "Sissoko", pos: "ST" },
  ],
  "Bordeux": [
    { first: "Yanis", last: "Lagrange", pos: "GK" },
    { first: "Lucas", last: "Cardóso", pos: "GK" },
    { first: "Marcelín", last: "Bilá", pos: "CB" },
    { first: "Pegguy", last: "Lacroíx", pos: "CB" },
    { first: "Adrien", last: "Bongiovánni", pos: "CM" },
    { first: "Braldevelopement", last: "Mbacké", pos: "RB" },
    { first: "Israël", last: "Ekenge", pos: "LB" },
    { first: "Andréas", last: "Hountondjí", pos: "ST" },
    { first: "Junior", last: "Mwanga", pos: "DM" },
    { first: "Tom", last: "Lacoux", pos: "CM" },
    { first: "Yoann", last: "Barbet", pos: "CB" },
    { first: "Alberth", last: "Elis", pos: "ST" },
    { first: "Mamadou", last: "Loum", pos: "DM" },
    { first: "Junior", last: "Onana", pos: "DM" },
    { first: "Aliou", last: "Badji", pos: "ST" },
    { first: "Sékou", last: "Mara", pos: "ST" },
  ],
  "Metze": [
    { first: "Alexandre", last: "Oukidjá", pos: "GK" },
    { first: "Jonathan", last: "Fischer", pos: "GK" },
    { first: "Matthieu", last: "Udól", pos: "LB" },
    { first: "Koffi", last: "Kouaó", pos: "CB" },
    { first: "Sadibou", last: "Sané", pos: "CB" },
    { first: "Maxime", last: "Colín", pos: "RB" },
    { first: "Fali", last: "Candé", pos: "CB" },
    { first: "Joseph", last: "N'Duquidi", pos: "DM" },
    { first: "Boubakár", last: "Traorée", pos: "CM" },
    { first: "Cheikh", last: "Sabaly", pos: "AM" },
    { first: "Gauthier", last: "Hein", pos: "AM" },
    { first: "Habib", last: "Dialló", pos: "ST" },
    { first: "Georges", last: "Mikautadzé", pos: "ST" },
    { first: "Idrissa", last: "Gueye", pos: "RW" },
    { first: "Morgan", last: "Bokelé", pos: "DM" },
    { first: "Lamine", last: "Camará", pos: "CM" },
  ],
  "Lorienne": [
    { first: "Yvon", last: "Mvogó", pos: "GK" },
    { first: "Vito", last: "Mannóne", pos: "GK" },
    { first: "Théo", last: "Le Bris", pos: "RB" },
    { first: "Montassar", last: "Talbí", pos: "CB" },
    { first: "Bonké", last: "Innocent", pos: "DM" },
    { first: "Igor", last: "Silva", pos: "CB" },
    { first: "Isaak", last: "Touré", pos: "CB" },
    { first: "Laurent", last: "Abergel", pos: "CM" },
    { first: "Tom", last: "Lacoux", pos: "CM" },
    { first: "Joël", last: "Abu Hanná", pos: "LB" },
    { first: "Eli", last: "Junior Krouptský", pos: "RW" },
    { first: "Pablo", last: "Pagis", pos: "ST" },
    { first: "Mohamed", last: "Bamba", pos: "ST" },
    { first: "Aiyegun", last: "Tosín", pos: "ST" },
    { first: "Romaín", last: "Faivre", pos: "AM" },
    { first: "Sambóu", last: "Soumanó", pos: "LW" },
  ],
  "Caenn": [
    { first: "Anthony", last: "Mandréa", pos: "GK" },
    { first: "Yannick", last: "Loemba", pos: "GK" },
    { first: "Emmanuel", last: "Ntim", pos: "RB" },
    { first: "Jonathan", last: "Rivierez", pos: "CB" },
    { first: "Alexandre", last: "Mendý", pos: "CB" },
    { first: "Norman", last: "Bassette", pos: "ST" },
    { first: "Hugo", last: "Vandermersch", pos: "LB" },
    { first: "Brahim", last: "Traorée", pos: "CM" },
    { first: "Daouda", last: "Wéidmann", pos: "DM" },
    { first: "Jean-Baptiste", last: "Gorby", pos: "CM" },
    { first: "Yoann", last: "Court", pos: "AM" },
    { first: "Rymel", last: "Diaby", pos: "ST" },
    { first: "Godson", last: "Kyeremeh", pos: "RW" },
    { first: "Alexandre", last: "Mendý", pos: "ST" },
    { first: "Mathias", last: "Aútret", pos: "AM" },
    { first: "Bilal", last: "Brahimí", pos: "LW" },
  ],
  "Guingampe": [
    { first: "Enzo", last: "Basílio", pos: "GK" },
    { first: "Moïse", last: "Adilehoú", pos: "GK" },
    { first: "Donatien", last: "Gomis", pos: "RB" },
    { first: "Maxime", last: "Le Marchand", pos: "CB" },
    { first: "Léo", last: "Saint-Pé", pos: "CB" },
    { first: "Jérémy", last: "Livolant", pos: "RW" },
    { first: "Sami", last: "Diakassan", pos: "LB" },
    { first: "Yannis", last: "Mvogó", pos: "DM" },
    { first: "Baïla", last: "Dialló", pos: "CM" },
    { first: "Brian", last: "Koffi", pos: "RW" },
    { first: "Enzó", last: "Bartolí", pos: "AM" },
    { first: "Théo", last: "Valls", pos: "CM" },
    { first: "Gédéon", last: "Kalulú", pos: "RB" },
    { first: "Mathias", last: "Phaëton", pos: "ST" },
    { first: "Alimami", last: "Gory", pos: "ST" },
    { first: "Louis", last: "Mafouta", pos: "ST" },
  ],
  "Grenoblo": [
    { first: "Brice", last: "Maúbleu", pos: "GK" },
    { first: "Loïc", last: "Boniju", pos: "GK" },
    { first: "Manuel", last: "Perez", pos: "RB" },
    { first: "Joseph", last: "Mendes", pos: "CB" },
    { first: "Néstor", last: "Djengoué", pos: "CB" },
    { first: "Jessy", last: "Benét", pos: "AM" },
    { first: "Adrien", last: "Monfray", pos: "LB" },
    { first: "Loris", last: "Néry", pos: "RB" },
    { first: "Théo", last: "Sainte-Luce", pos: "CM" },
    { first: "Antoine", last: "Valério", pos: "DM" },
    { first: "Mickaël", last: "Biron", pos: "ST" },
    { first: "Benjamín", last: "Bouchouari", pos: "CM" },
    { first: "Yanis", last: "Boukamír", pos: "AM" },
    { first: "Joris", last: "Correa", pos: "RW" },
    { first: "Maxime", last: "Spano", pos: "ST" },
    { first: "Adrien", last: "Gausseran", pos: "LW" },
  ],
  "Amienne": [
    { first: "Régis", last: "Gurtnér", pos: "GK" },
    { first: "Yann", last: "Boula", pos: "GK" },
    { first: "Émile", last: "Pino", pos: "RB" },
    { first: "Nicholas", last: "Opoku", pos: "CB" },
    { first: "Formosé", last: "Mendý", pos: "CB" },
    { first: "Owusú", last: "Kwabena", pos: "LB" },
    { first: "Avranas", last: "Antoine", pos: "RB" },
    { first: "Théo", last: "Leoni", pos: "DM" },
    { first: "Mamadou", last: "Fofaná", pos: "CM" },
    { first: "Esaïe", last: "Lukónga", pos: "AM" },
    { first: "Ousmane", last: "Kamissoko", pos: "CM" },
    { first: "Louis", last: "Mafouta", pos: "ST" },
    { first: "Aliou", last: "Baldé", pos: "RW" },
    { first: "Wilson", last: "Samaké", pos: "LW" },
    { first: "Romaín", last: "Del Castillo", pos: "AM" },
    { first: "Adam", last: "Oudjaní", pos: "ST" },
  ],
  "Bastia": [
    { first: "Johny", last: "Plácido", pos: "GK" },
    { first: "Mathéo", last: "Raspedjini", pos: "GK" },
    { first: "Christophe", last: "Vincent", pos: "RB" },
    { first: "Dominique", last: "Guidi", pos: "CB" },
    { first: "Migouel", last: "Alfarela", pos: "ST" },
    { first: "Sébastien", last: "Salles-Lamonge", pos: "RB" },
    { first: "Tom", last: "Ducrocq", pos: "DM" },
    { first: "Benjamín", last: "Santellí", pos: "RW" },
    { first: "Mehdi", last: "Chahirí", pos: "AM" },
    { first: "Florián", last: "Bohnert", pos: "LB" },
    { first: "Lucas", last: "Spano", pos: "AM" },
    { first: "Jean-Philippe", last: "Krasso", pos: "ST" },
    { first: "Roméo", last: "Vandersmissen", pos: "CM" },
    { first: "Carl", last: "Coumé", pos: "CB" },
    { first: "Sasá", last: "Magagna", pos: "RW" },
    { first: "Nicolás", last: "Janvier", pos: "CM" },
  ],
  "Pau Bearn": [
    { first: "Alexandre", last: "Olliero", pos: "GK" },
    { first: "Théo", last: "Guivarch", pos: "GK" },
    { first: "Quentín", last: "Daubín", pos: "RB" },
    { first: "Erempamo", last: "Maron", pos: "CB" },
    { first: "Wakaso", last: "Mubarak", pos: "DM" },
    { first: "Charles", last: "Boli", pos: "RW" },
    { first: "Mike", last: "Sylla", pos: "LB" },
    { first: "Steeve", last: "Beusnard", pos: "RB" },
    { first: "Henri", last: "Saivét", pos: "AM" },
    { first: "Antoine", last: "Batisse", pos: "CB" },
    { first: "Lucas", last: "Mendès", pos: "CB" },
    { first: "Victor", last: "Lobry", pos: "CM" },
    { first: "Jérémy", last: "Choplin", pos: "CB" },
    { first: "Mons", last: "Bassoúma", pos: "AM" },
    { first: "Idrissa", last: "Cissé", pos: "ST" },
    { first: "Aldo", last: "Kalulú", pos: "ST" },
  ],
  "Rodeze": [
    { first: "Lucas", last: "Dias", pos: "GK" },
    { first: "Adrien", last: "Lebeau", pos: "GK" },
    { first: "Jérémy", last: "Vachoux", pos: "GK" },
    { first: "Lucas", last: "Buadés", pos: "RW" },
    { first: "Bastien", last: "Sénac", pos: "RB" },
    { first: "Maxime", last: "Barthelmé", pos: "CM" },
    { first: "Killian", last: "Corredor", pos: "RW" },
    { first: "Mathieu", last: "Cafaró", pos: "AM" },
    { first: "Lucas", last: "Hernándes", pos: "CB" },
    { first: "Florent", last: "Hanin", pos: "CB" },
    { first: "Pierre-Yves", last: "Hamel", pos: "ST" },
    { first: "Naïm", last: "Adem", pos: "CM" },
    { first: "Marvín", last: "Sénaya", pos: "RB" },
    { first: "Joris", last: "Chougrani", pos: "ST" },
    { first: "Grejohn", last: "Kyei", pos: "ST" },
    { first: "Aurélien", last: "Joachím", pos: "ST" },
  ],
  "Annecie": [
    { first: "Mory", last: "Diaw", pos: "GK" },
    { first: "Thomás", last: "Callens", pos: "GK" },
    { first: "Vincent", last: "Pajot", pos: "DM" },
    { first: "Anthony", last: "Belmonté", pos: "LB" },
    { first: "Florent", last: "Hanin", pos: "CB" },
    { first: "Loïc", last: "Néstor", pos: "CB" },
    { first: "Cheikh", last: "Niasse", pos: "DM" },
    { first: "Clément", last: "Vidál", pos: "CB" },
    { first: "Émile", last: "Spinello", pos: "RB" },
    { first: "Stéphane", last: "Magnánelli", pos: "AM" },
    { first: "César", last: "Coumé", pos: "CM" },
    { first: "Sébastien", last: "Wuthrích", pos: "RW" },
    { first: "Théo", last: "Salmin", pos: "LW" },
    { first: "Anthony", last: "Roncaglía", pos: "ST" },
    { first: "Jérémy", last: "Sopalsky", pos: "ST" },
    { first: "Yohan", last: "Demoncy", pos: "AM" },
  ],
  "Laval Stade": [
    { first: "Anthony", last: "Maisonniál", pos: "GK" },
    { first: "Maxime", last: "Hautboís", pos: "GK" },
    { first: "Yannick", last: "Loemba", pos: "RW" },
    { first: "Bryan", last: "Goncalves", pos: "CB" },
    { first: "Jordan", last: "Adéoti", pos: "DM" },
    { first: "Klisman", last: "Cake", pos: "CB" },
    { first: "Florent", last: "Lasné", pos: "LB" },
    { first: "Geoffray", last: "Durbant", pos: "RB" },
    { first: "Achille", last: "Ankér", pos: "CM" },
    { first: "Joël", last: "Tchamí", pos: "DM" },
    { first: "Roberto", last: "Bordín", pos: "AM" },
    { first: "Gabriel", last: "Lacroíx", pos: "RW" },
    { first: "Stéphane", last: "Diarrá", pos: "RW" },
    { first: "Téji", last: "Dieng", pos: "ST" },
    { first: "Daouda", last: "Guindo", pos: "ST" },
    { first: "Mbehdy", last: "Guezoulí", pos: "ST" },
  ],
  "Dunquerke": [
    { first: "Yahia", last: "Foferá", pos: "GK" },
    { first: "Léo", last: "Pétrot", pos: "LB" },
    { first: "Gaétan", last: "Robaíl", pos: "RW" },
    { first: "Florent", last: "Sanchéz", pos: "CB" },
    { first: "Vincent", last: "Hébert", pos: "GK" },
    { first: "Florian", last: "Boharné", pos: "CB" },
    { first: "Walid", last: "Loukrí", pos: "DM" },
    { first: "Maxime", last: "Hautboís", pos: "GK" },
    { first: "Aboubakár", last: "Camará", pos: "CM" },
    { first: "Mehdi", last: "Boutaríne", pos: "RB" },
    { first: "Théo", last: "Roborel", pos: "CM" },
    { first: "Salim", last: "Ben Seghír", pos: "AM" },
    { first: "Tim", last: "Songo'o", pos: "ST" },
    { first: "Léo", last: "Castán", pos: "AM" },
    { first: "Ryan", last: "Daoudí", pos: "RW" },
    { first: "Kwasi", last: "Wriedt", pos: "ST" },
  ],
  "Troyas": [
    { first: "Sebastián", last: "Cibóis", pos: "GK" },
    { first: "Gauthier", last: "Gallón", pos: "GK" },
    { first: "Yoann", last: "Salmiér", pos: "CB" },
    { first: "Adil", last: "Tahrat", pos: "CB" },
    { first: "Abdú", last: "Conté", pos: "LB" },
    { first: "Tristán", last: "Dingomé", pos: "CM" },
    { first: "Wilson", last: "Odobert", pos: "RW" },
    { first: "Rominigué", last: "Kouamé", pos: "DM" },
    { first: "Sékou", last: "Sidibé", pos: "CM" },
    { first: "Jaurés", last: "Assoumoú", pos: "AM" },
    { first: "Maxime", last: "Barthelmé", pos: "AM" },
    { first: "Mama", last: "Baldé", pos: "ST" },
    { first: "Yasser", last: "Larouci", pos: "LB" },
    { first: "Thierno", last: "Baldé", pos: "RB" },
    { first: "Andréas", last: "Bruus", pos: "RB" },
    { first: "Renaúd", last: "Ripart", pos: "ST" },
  ],
  "Clermonte": [
    { first: "Mory", last: "Diaw", pos: "GK" },
    { first: "Ouparine", last: "Djoco", pos: "GK" },
    { first: "Florent", last: "Ogiér", pos: "CB" },
    { first: "Alidú", last: "Seidu", pos: "RB" },
    { first: "Maximé", last: "Gonalons", pos: "DM" },
    { first: "Néto", last: "Borges", pos: "LB" },
    { first: "Cédric", last: "Hountondjí", pos: "CB" },
    { first: "Yohann", last: "Magnín", pos: "CM" },
    { first: "Johán", last: "Gastién", pos: "DM" },
    { first: "Jim", last: "Allevinah", pos: "RW" },
    { first: "Muhammed", last: "Cham", pos: "AM" },
    { first: "Aiman", last: "Maurér", pos: "CM" },
    { first: "Komnen", last: "Andrié", pos: "ST" },
    { first: "Grejohn", last: "Kyei", pos: "ST" },
    { first: "Gabriel", last: "Boursíer", pos: "RB" },
    { first: "Bilal", last: "Boutobba", pos: "AM" },
  ],
};
