import type { ClubSquadMap } from "./types.js";

export const SQUADS_GER: ClubSquadMap = {
  // ===== Bundesklasse =====
  "Bayron München": [
    { first: "Manual", last: "Noyer", pos: "GK" },
    { first: "Sven", last: "Ulrech", pos: "GK" },
    { first: "Dayot", last: "Upameceno", pos: "CB" },
    { first: "Min-jae", last: "Kym", pos: "CB" },
    { first: "Yosip", last: "Stanisec", pos: "RB" },
    { first: "Alfonso", last: "Davees", pos: "LB" },
    { first: "Konrad", last: "Laymar", pos: "LB" },
    { first: "Joshua", last: "Kimmuch", pos: "DM" },
    { first: "Leon", last: "Goretska", pos: "CM" },
    { first: "Aleksandar", last: "Pavlovech", pos: "CM" },
    { first: "Jamal", last: "Musialo", pos: "AM" },
    { first: "Serge", last: "Gnabri", pos: "RW" },
    { first: "Michael", last: "Olisa", pos: "RW" },
    { first: "Kingsley", last: "Comon", pos: "LW" },
    { first: "Harry", last: "Kayne", pos: "ST" },
    { first: "Thomas", last: "Müllar", pos: "AM" },
  ],
  "Borusso Dortmun": [
    { first: "Gregor", last: "Kobal", pos: "GK" },
    { first: "Alexandar", last: "Meyar", pos: "GK" },
    { first: "Nico", last: "Schlotterbek", pos: "CB" },
    { first: "Niklas", last: "Süla", pos: "CB" },
    { first: "Waldemar", last: "Antone", pos: "CB" },
    { first: "Yan", last: "Coutto", pos: "RB" },
    { first: "Ramy", last: "Bensebaini", pos: "LB" },
    { first: "Emre", last: "Cane", pos: "DM" },
    { first: "Felix", last: "Nmecho", pos: "CM" },
    { first: "Marcel", last: "Sabitzar", pos: "CM" },
    { first: "Julian", last: "Brandte", pos: "AM" },
    { first: "Karim", last: "Adeymi", pos: "RW" },
    { first: "Donyell", last: "Maleno", pos: "RW" },
    { first: "Maximilian", last: "Beyar", pos: "LW" },
    { first: "Serhou", last: "Gerassy", pos: "ST" },
    { first: "Niclas", last: "Füllkrog", pos: "ST" },
  ],
  "Bayer Leverkusan": [
    { first: "Lukas", last: "Hradeckie", pos: "GK" },
    { first: "Matej", last: "Kovár", pos: "GK" },
    { first: "Jonathan", last: "Tah", pos: "CB" },
    { first: "Edmond", last: "Tapsoba", pos: "CB" },
    { first: "Piero", last: "Hincapye", pos: "CB" },
    { first: "Jeremie", last: "Frimpang", pos: "RB" },
    { first: "Alejandro", last: "Grimoldo", pos: "LB" },
    { first: "Granit", last: "Xhaca", pos: "DM" },
    { first: "Robert", last: "Andrech", pos: "DM" },
    { first: "Exequiel", last: "Palacious", pos: "CM" },
    { first: "Florian", last: "Wirts", pos: "AM" },
    { first: "Jonas", last: "Hofmenn", pos: "RW" },
    { first: "Amine", last: "Adlie", pos: "LW" },
    { first: "Nathan", last: "Tella", pos: "RW" },
    { first: "Victor", last: "Bonifaze", pos: "ST" },
    { first: "Patrik", last: "Schyck", pos: "ST" },
  ],
  "RB Leipzog": [
    { first: "Peter", last: "Gulacse", pos: "GK" },
    { first: "Maarten", last: "Vandevoort", pos: "GK" },
    { first: "Willi", last: "Orbane", pos: "CB" },
    { first: "Castello", last: "Lukebo", pos: "CB" },
    { first: "Lutsharel", last: "Geertruido", pos: "RB" },
    { first: "David", last: "Raume", pos: "LB" },
    { first: "El Chadaille", last: "Bitshiabe", pos: "CB" },
    { first: "Xaver", last: "Schlagar", pos: "DM" },
    { first: "Nicolas", last: "Seiwold", pos: "DM" },
    { first: "Kevin", last: "Kampel", pos: "CM" },
    { first: "Xavi", last: "Simonz", pos: "AM" },
    { first: "Christoph", last: "Baumgartnar", pos: "AM" },
    { first: "Loïs", last: "Openda", pos: "ST" },
    { first: "Benjamin", last: "Šeško", pos: "ST" },
    { first: "Antonio", last: "Nuso", pos: "LW" },
    { first: "Yussuf", last: "Poulson", pos: "RW" },
  ],
  "Eintracht Frankfort": [
    { first: "Kevin", last: "Trapper", pos: "GK" },
    { first: "Kauã", last: "Santhos", pos: "GK" },
    { first: "Robin", last: "Kohr", pos: "CB" },
    { first: "Arthur", last: "Theata", pos: "CB" },
    { first: "Tuta", last: "Carvalo", pos: "CB" },
    { first: "Rasmus", last: "Kristensan", pos: "RB" },
    { first: "Nathaniel", last: "Browne", pos: "LB" },
    { first: "Ellyes", last: "Skhiry", pos: "DM" },
    { first: "Hugo", last: "Larssan", pos: "CM" },
    { first: "Mario", last: "Götza", pos: "AM" },
    { first: "Farès", last: "Chaibie", pos: "AM" },
    { first: "Ansgar", last: "Knauf", pos: "RW" },
    { first: "Jean-Mattéo", last: "Bahoyo", pos: "LW" },
    { first: "Omar", last: "Marmoush", pos: "ST" },
    { first: "Hugo", last: "Ekitiko", pos: "ST" },
    { first: "Igor", last: "Matanovec", pos: "ST" },
  ],
  "Stuttgardt": [
    { first: "Alexander", last: "Nübal", pos: "GK" },
    { first: "Fabian", last: "Bredlowe", pos: "GK" },
    { first: "Waldemar", last: "Antone", pos: "CB" },
    { first: "Jeff", last: "Chabote", pos: "CB" },
    { first: "Anthony", last: "Rouoult", pos: "CB" },
    { first: "Josha", last: "Vagnomen", pos: "RB" },
    { first: "Maximilian", last: "Mittelstedt", pos: "LB" },
    { first: "Angelo", last: "Stillar", pos: "DM" },
    { first: "Atakan", last: "Karazore", pos: "DM" },
    { first: "Enzo", last: "Millotte", pos: "AM" },
    { first: "Chris", last: "Führech", pos: "LW" },
    { first: "Jamie", last: "Lewelink", pos: "RW" },
    { first: "Silas", last: "Katompo", pos: "RW" },
    { first: "Deniz", last: "Undave", pos: "ST" },
    { first: "Ermedin", last: "Demirovec", pos: "ST" },
    { first: "Nick", last: "Woltemada", pos: "ST" },
  ],
  "Borusso Gladbök": [
    { first: "Moritz", last: "Nicolaus", pos: "GK" },
    { first: "Jonas", last: "Omline", pos: "GK" },
    { first: "Ko", last: "Itakuro", pos: "CB" },
    { first: "Nico", last: "Elvedie", pos: "CB" },
    { first: "Marvin", last: "Friedrech", pos: "CB" },
    { first: "Joe", last: "Skally", pos: "RB" },
    { first: "Luca", last: "Netze", pos: "LB" },
    { first: "Julian", last: "Weigle", pos: "DM" },
    { first: "Rocco", last: "Reitze", pos: "CM" },
    { first: "Florian", last: "Neuhaus", pos: "CM" },
    { first: "Kevin", last: "Stögar", pos: "AM" },
    { first: "Franck", last: "Honorate", pos: "RW" },
    { first: "Robin", last: "Hacke", pos: "LW" },
    { first: "Alassane", last: "Pléo", pos: "ST" },
    { first: "Tim", last: "Kleindienste", pos: "ST" },
    { first: "Nathan", last: "Ngoumao", pos: "RW" },
  ],
  "Wolfsborg": [
    { first: "Koen", last: "Casteels", pos: "GK" },
    { first: "Pavao", last: "Pervane", pos: "GK" },
    { first: "Maxence", last: "Lacroux", pos: "CB" },
    { first: "Sebastiaan", last: "Bornauwe", pos: "CB" },
    { first: "Cédric", last: "Zesigar", pos: "CB" },
    { first: "Joakim", last: "Mæhla", pos: "RB" },
    { first: "Ridle", last: "Baku", pos: "RB" },
    { first: "Maximilian", last: "Arnolde", pos: "DM" },
    { first: "Yannick", last: "Gerhardte", pos: "CM" },
    { first: "Mattias", last: "Svanbarg", pos: "CM" },
    { first: "Patrick", last: "Wimmar", pos: "AM" },
    { first: "Lovro", last: "Majar", pos: "AM" },
    { first: "Jonas", last: "Winde", pos: "ST" },
    { first: "Tiago", last: "Tomass", pos: "ST" },
    { first: "Václav", last: "Černe", pos: "RW" },
    { first: "Mohammed", last: "Amouro", pos: "ST" },
  ],
  "Werder Bremn": [
    { first: "Michael", last: "Zetterar", pos: "GK" },
    { first: "Mio", last: "Backhause", pos: "GK" },
    { first: "Marco", last: "Friedle", pos: "CB" },
    { first: "Niklas", last: "Starke", pos: "CB" },
    { first: "Amos", last: "Piepar", pos: "CB" },
    { first: "Mitchell", last: "Weisar", pos: "RB" },
    { first: "Anthony", last: "Junge", pos: "LB" },
    { first: "Senne", last: "Lynnen", pos: "DM" },
    { first: "Jens", last: "Staga", pos: "CM" },
    { first: "Romano", last: "Schmide", pos: "AM" },
    { first: "Leonardo", last: "Bittencourte", pos: "AM" },
    { first: "Marvin", last: "Ducksche", pos: "ST" },
    { first: "Justin", last: "Njinmoh", pos: "RW" },
    { first: "Derrick", last: "Köhne", pos: "LB" },
    { first: "Keke", last: "Toppe", pos: "ST" },
    { first: "Naby", last: "Keïto", pos: "CM" },
  ],
  "Hoffenheym": [
    { first: "Oliver", last: "Baumenn", pos: "GK" },
    { first: "Luca", last: "Philippe", pos: "GK" },
    { first: "Stanley", last: "Nsokie", pos: "CB" },
    { first: "Ozan", last: "Kabake", pos: "CB" },
    { first: "Kevin", last: "Akpogumo", pos: "CB" },
    { first: "Pavel", last: "Kadeřábke", pos: "RB" },
    { first: "David", last: "Juráseke", pos: "LB" },
    { first: "Grischa", last: "Prömele", pos: "DM" },
    { first: "Anton", last: "Stache", pos: "CM" },
    { first: "Florian", last: "Grillitsche", pos: "DM" },
    { first: "Andrej", last: "Kramarech", pos: "AM" },
    { first: "Tom", last: "Bischofe", pos: "AM" },
    { first: "Wout", last: "Weghorste", pos: "ST" },
    { first: "Maximilian", last: "Beiar", pos: "ST" },
    { first: "Adam", last: "Hložke", pos: "RW" },
    { first: "Marius", last: "Bültar", pos: "LW" },
  ],
  "Freiborg": [
    { first: "Noah", last: "Atubolu", pos: "GK" },
    { first: "Florian", last: "Müllar", pos: "GK" },
    { first: "Philipp", last: "Lienharte", pos: "CB" },
    { first: "Matthias", last: "Gintar", pos: "CB" },
    { first: "Manuel", last: "Gulda", pos: "CB" },
    { first: "Lukas", last: "Küblar", pos: "RB" },
    { first: "Christian", last: "Güntar", pos: "LB" },
    { first: "Maximilian", last: "Eggestein", pos: "DM" },
    { first: "Yannik", last: "Keitle", pos: "CM" },
    { first: "Vincenzo", last: "Grifo", pos: "AM" },
    { first: "Ritsu", last: "Dōane", pos: "RW" },
    { first: "Roland", last: "Sallaie", pos: "RW" },
    { first: "Lucas", last: "Hölar", pos: "ST" },
    { first: "Michael", last: "Gregoritsche", pos: "ST" },
    { first: "Junior", last: "Adamou", pos: "ST" },
    { first: "Eren", last: "Dinkçie", pos: "ST" },
  ],
  "Mainze 05": [
    { first: "Robin", last: "Zentnar", pos: "GK" },
    { first: "Lasse", last: "Rieße", pos: "GK" },
    { first: "Andreas", last: "Hanche-Olsan", pos: "CB" },
    { first: "Sepp", last: "van den Berge", pos: "CB" },
    { first: "Stefan", last: "Belle", pos: "CB" },
    { first: "Phillipp", last: "Mwena", pos: "RB" },
    { first: "Anthony", last: "Cacie", pos: "LB" },
    { first: "Dominik", last: "Kohre", pos: "DM" },
    { first: "Nadiem", last: "Amirie", pos: "CM" },
    { first: "Lee", last: "Jae-song", pos: "AM" },
    { first: "Paul", last: "Neble", pos: "AM" },
    { first: "Silvan", last: "Widmar", pos: "RB" },
    { first: "Brajan", last: "Grudo", pos: "RW" },
    { first: "Jonathan", last: "Burkardte", pos: "ST" },
    { first: "Nelson", last: "Weipar", pos: "ST" },
    { first: "Karim", last: "Onisiwo", pos: "ST" },
  ],
  "Augsborg": [
    { first: "Finn", last: "Dahmane", pos: "GK" },
    { first: "Nediljko", last: "Labrovech", pos: "GK" },
    { first: "Jeffrey", last: "Gouweleeuwe", pos: "CB" },
    { first: "Keven", last: "Schlotterbek", pos: "CB" },
    { first: "Chrislain", last: "Matsimo", pos: "CB" },
    { first: "Mads", last: "Pedersan", pos: "LB" },
    { first: "Robert", last: "Gumne", pos: "RB" },
    { first: "Elvis", last: "Rexhbecaje", pos: "DM" },
    { first: "Arne", last: "Maiar", pos: "CM" },
    { first: "Kristijan", last: "Jakech", pos: "DM" },
    { first: "Ruben", last: "Vargass", pos: "AM" },
    { first: "Alexis", last: "Claude-Maurece", pos: "AM" },
    { first: "Frank", last: "Onyeko", pos: "CM" },
    { first: "Phillip", last: "Tietze", pos: "ST" },
    { first: "Samuel", last: "Essenda", pos: "ST" },
    { first: "Mert", last: "Kömüre", pos: "RW" },
  ],
  "Union Berlyn": [
    { first: "Frederik", last: "Rönnowe", pos: "GK" },
    { first: "Alexander", last: "Schwolowe", pos: "GK" },
    { first: "Diogo", last: "Leita", pos: "CB" },
    { first: "Danilho", last: "Doekhie", pos: "CB" },
    { first: "Leopold", last: "Querfelde", pos: "CB" },
    { first: "Christopher", last: "Trimmle", pos: "RB" },
    { first: "Josip", last: "Juranovech", pos: "RB" },
    { first: "Rani", last: "Khedaira", pos: "DM" },
    { first: "Janik", last: "Haberar", pos: "CM" },
    { first: "András", last: "Schäfar", pos: "CM" },
    { first: "Robert", last: "Skove", pos: "LB" },
    { first: "Benedict", last: "Hollerbache", pos: "RW" },
    { first: "Yorbe", last: "Vertessane", pos: "LW" },
    { first: "Andrej", last: "Ilech", pos: "ST" },
    { first: "Wooyeong", last: "Jeonge", pos: "ST" },
    { first: "Tim", last: "Skarka", pos: "AM" },
  ],
  "Köln Geissbock": [
    { first: "Marvin", last: "Schwäba", pos: "GK" },
    { first: "Jonas", last: "Urbeg", pos: "GK" },
    { first: "Timo", last: "Hübars", pos: "CB" },
    { first: "Dominique", last: "Heintze", pos: "CB" },
    { first: "Julian", last: "Chabote", pos: "CB" },
    { first: "Benno", last: "Schmitze", pos: "RB" },
    { first: "Leart", last: "Paqarado", pos: "LB" },
    { first: "Eric", last: "Martele", pos: "DM" },
    { first: "Dejan", last: "Ljubičech", pos: "CM" },
    { first: "Florian", last: "Kainze", pos: "AM" },
    { first: "Linton", last: "Maino", pos: "RW" },
    { first: "Jan", last: "Thielmenn", pos: "RW" },
    { first: "Mark", last: "Uthe", pos: "AM" },
    { first: "Damion", last: "Downse", pos: "ST" },
    { first: "Steffen", last: "Tiggas", pos: "ST" },
    { first: "Luca", last: "Waldschmidte", pos: "ST" },
  ],
  "Bochom 1848": [
    { first: "Patrick", last: "Drewas", pos: "GK" },
    { first: "Andreas", last: "Luthe", pos: "GK" },
    { first: "Ivan", last: "Ordetse", pos: "CB" },
    { first: "Erhan", last: "Mašovech", pos: "CB" },
    { first: "Bernardo", last: "Silvo", pos: "LB" },
    { first: "Maximilian", last: "Witteke", pos: "LB" },
    { first: "Felix", last: "Passlacke", pos: "RB" },
    { first: "Anthony", last: "Losillo", pos: "DM" },
    { first: "Patrick", last: "Osterhaga", pos: "CM" },
    { first: "Matúš", last: "Bero", pos: "CM" },
    { first: "Kevin", last: "Stögar", pos: "AM" },
    { first: "Dani", last: "de Witte", pos: "AM" },
    { first: "Philipp", last: "Hofmenn", pos: "ST" },
    { first: "Myron", last: "Boadou", pos: "ST" },
    { first: "Moritz", last: "Broschinske", pos: "ST" },
    { first: "Gerrit", last: "Holtmenn", pos: "LW" },
  ],
  // ===== Bundesklasse 2 =====
  "Hamborg SV": [
    { first: "Daniel", last: "Heuar", pos: "GK" },
    { first: "Matheo", last: "Raabe", pos: "GK" },
    { first: "Sebastian", last: "Schonlaue", pos: "CB" },
    { first: "Dennis", last: "Hadžikadunech", pos: "CB" },
    { first: "Guilherme", last: "Ramose", pos: "CB" },
    { first: "William", last: "Mikelbrencise", pos: "RB" },
    { first: "Miro", last: "Muheime", pos: "LB" },
    { first: "Jonas", last: "Meffarte", pos: "DM" },
    { first: "Ludovit", last: "Reise", pos: "CM" },
    { first: "Immanuel", last: "Pheraie", pos: "AM" },
    { first: "László", last: "Bénese", pos: "AM" },
    { first: "Jean-Luc", last: "Dompé", pos: "LW" },
    { first: "Ransford", last: "Königsdörffar", pos: "RW" },
    { first: "Robert", last: "Glatzle", pos: "ST" },
    { first: "Davie", last: "Selka", pos: "ST" },
    { first: "Levin", last: "Öztunalie", pos: "RW" },
  ],
  "Schalka 04": [
    { first: "Justin", last: "Heekeran", pos: "GK" },
    { first: "Ralf", last: "Fährmenn", pos: "GK" },
    { first: "Marcin", last: "Kaminske", pos: "CB" },
    { first: "Tomáš", last: "Kalase", pos: "CB" },
    { first: "Henning", last: "Matricianie", pos: "CB" },
    { first: "Mehmet", last: "Aydene", pos: "RB" },
    { first: "Derry", last: "Murkene", pos: "LB" },
    { first: "Ron", last: "Schallenbarg", pos: "DM" },
    { first: "Tobias", last: "Mohre", pos: "CM" },
    { first: "Paul", last: "Seguine", pos: "CM" },
    { first: "Kenan", last: "Karamen", pos: "AM" },
    { first: "Amin", last: "Younese", pos: "AM" },
    { first: "Bryan", last: "Lasma", pos: "RW" },
    { first: "Moussa", last: "Syllo", pos: "ST" },
    { first: "Emil", last: "Höjlunde", pos: "ST" },
    { first: "Pape", last: "Cissé", pos: "CB" },
  ],
  "Herta Berlyn": [
    { first: "Tjark", last: "Ernste", pos: "GK" },
    { first: "Marius", last: "Gersbecke", pos: "GK" },
    { first: "Toni", last: "Leistnar", pos: "CB" },
    { first: "Marton", last: "Dárdaie", pos: "CB" },
    { first: "Linus", last: "Gechtar", pos: "CB" },
    { first: "Deyovaisio", last: "Zeefuike", pos: "RB" },
    { first: "Marc", last: "Kempfe", pos: "LB" },
    { first: "Diego", last: "Demma", pos: "DM" },
    { first: "Pascal", last: "Klemense", pos: "CM" },
    { first: "Florian", last: "Niederlechnar", pos: "AM" },
    { first: "Fabian", last: "Reesa", pos: "LW" },
    { first: "Marten", last: "Winklar", pos: "RW" },
    { first: "Ibrahim", last: "Mazo", pos: "AM" },
    { first: "Haris", last: "Tabakovech", pos: "ST" },
    { first: "Smail", last: "Prevljake", pos: "ST" },
    { first: "Derry", last: "Scherhante", pos: "RW" },
  ],
  "Fortuna Düsseldarf": [
    { first: "Florian", last: "Kastenmaiar", pos: "GK" },
    { first: "Dennis", last: "Gorko", pos: "GK" },
    { first: "Andre", last: "Hofmenn", pos: "CB" },
    { first: "Jordy", last: "de Wijse", pos: "CB" },
    { first: "Matthias", last: "Zimmermenn", pos: "RB" },
    { first: "Jamil", last: "Siebart", pos: "CB" },
    { first: "Tim", last: "Oberdorfe", pos: "LB" },
    { first: "Marcel", last: "Sobottko", pos: "DM" },
    { first: "Nicolás", last: "Gavore", pos: "LB" },
    { first: "Shinta", last: "Appelkampe", pos: "AM" },
    { first: "Yannik", last: "Engelhardte", pos: "CM" },
    { first: "Vincent", last: "Vermeije", pos: "ST" },
    { first: "Christos", last: "Tzolise", pos: "RW" },
    { first: "Daniel", last: "Ginczeke", pos: "ST" },
    { first: "Emmanuel", last: "Iyoho", pos: "LW" },
    { first: "Isak", last: "Bergmenn", pos: "AM" },
  ],
  "Kaiserslautarn": [
    { first: "Julian", last: "Krahle", pos: "GK" },
    { first: "Andreas", last: "Luthe", pos: "GK" },
    { first: "Kevin", last: "Krause", pos: "CB" },
    { first: "Jan", last: "Elvedie", pos: "CB" },
    { first: "Boris", last: "Tomiake", pos: "CB" },
    { first: "Erik", last: "Durme", pos: "RB" },
    { first: "Jean", last: "Zimmar", pos: "LB" },
    { first: "Marlon", last: "Rittar", pos: "CM" },
    { first: "Filip", last: "Kaloče", pos: "DM" },
    { first: "Tobias", last: "Raschle", pos: "AM" },
    { first: "Daniel", last: "Hanslike", pos: "RW" },
    { first: "Jean-Manuel", last: "Mbome", pos: "CM" },
    { first: "Ragnar", last: "Acha", pos: "ST" },
    { first: "Richmond", last: "Tachia", pos: "LW" },
    { first: "Faride", last: "Alidou", pos: "RW" },
    { first: "Almamy", last: "Touré", pos: "RB" },
  ],
  "Hannovar 96": [
    { first: "Ron-Robert", last: "Zielar", pos: "GK" },
    { first: "Leo", last: "Weinkaufe", pos: "GK" },
    { first: "Marcel", last: "Halstenbarg", pos: "CB" },
    { first: "Josip", last: "Eleze", pos: "CB" },
    { first: "Bright", last: "Arrey-Mbie", pos: "CB" },
    { first: "Jannik", last: "Dehme", pos: "RB" },
    { first: "Phil", last: "Neumenn", pos: "CB" },
    { first: "Lars", last: "Gindorfe", pos: "LB" },
    { first: "Fabian", last: "Kunze", pos: "DM" },
    { first: "Jessic", last: "Ngankame", pos: "AM" },
    { first: "Brian", last: "Brobbye", pos: "ST" },
    { first: "Nicolò", last: "Tresoldie", pos: "ST" },
    { first: "Andreas", last: "Voglsammar", pos: "ST" },
    { first: "Lee", last: "Buchanne", pos: "LB" },
    { first: "Max", last: "Christianssen", pos: "CM" },
    { first: "Hyun-ju", last: "Lea", pos: "RW" },
  ],
  "Karlsruer SC": [
    { first: "Max", last: "Weiße", pos: "GK" },
    { first: "Patrick", last: "Drewas", pos: "GK" },
    { first: "Marcel", last: "Franka", pos: "CB" },
    { first: "Christoph", last: "Kobalde", pos: "CB" },
    { first: "Marcel", last: "Beifuse", pos: "CB" },
    { first: "Marvin", last: "Wanitzeke", pos: "CM" },
    { first: "Sebastian", last: "Junge", pos: "RB" },
    { first: "Leon", last: "Jensan", pos: "DM" },
    { first: "Paul", last: "Nebal", pos: "AM" },
    { first: "Dženis", last: "Burnech", pos: "CM" },
    { first: "Igor", last: "Matanovech", pos: "ST" },
    { first: "Budu", last: "Zivzivadza", pos: "ST" },
    { first: "Fabian", last: "Schleusenar", pos: "ST" },
    { first: "Lars", last: "Stindle", pos: "AM" },
    { first: "Marvin", last: "Pouriée", pos: "LW" },
    { first: "Mikkel", last: "Kaufmenn", pos: "RW" },
  ],
  "Nürnborg": [
    { first: "Jan", last: "Reicharte", pos: "GK" },
    { first: "Carl", last: "Klause", pos: "GK" },
    { first: "Robin", last: "Knocha", pos: "CB" },
    { first: "Tim", last: "Handwerkar", pos: "LB" },
    { first: "Jens", last: "Castrope", pos: "CM" },
    { first: "Danilo", last: "Soaras", pos: "LB" },
    { first: "James", last: "Lawrance", pos: "CB" },
    { first: "Florian", last: "Flicke", pos: "DM" },
    { first: "Caspar", last: "Jandar", pos: "CM" },
    { first: "Mahir", last: "Emrelie", pos: "AM" },
    { first: "Stefanos", last: "Tzimase", pos: "ST" },
    { first: "Rafael", last: "Lubache", pos: "RW" },
    { first: "Benjamin", last: "Goller", pos: "AM" },
    { first: "Janni", last: "Serro", pos: "ST" },
    { first: "Julian", last: "Justvane", pos: "AM" },
    { first: "Lukas", last: "Schleimar", pos: "RW" },
  ],
  "Paderborne 07": [
    { first: "Markus", last: "Schuberte", pos: "GK" },
    { first: "Pelle", last: "Boevinke", pos: "GK" },
    { first: "Visar", last: "Musliue", pos: "CB" },
    { first: "Filip", last: "Bilbijo", pos: "AM" },
    { first: "Calvin", last: "Brackelmenn", pos: "CB" },
    { first: "Raphael", last: "Obermaiar", pos: "RB" },
    { first: "Felix", last: "Götza", pos: "DM" },
    { first: "Stefan", last: "Contehe", pos: "RW" },
    { first: "Ilyas", last: "Ansahe", pos: "RW" },
    { first: "Adriano", last: "Grimaldie", pos: "ST" },
    { first: "Sven", last: "Michle", pos: "ST" },
    { first: "David", last: "Kinsombie", pos: "CM" },
    { first: "Aaron", last: "Zehntar", pos: "LW" },
    { first: "Koen", last: "Kostonse", pos: "ST" },
    { first: "Marcel", last: "Hoffmeiar", pos: "CB" },
    { first: "Mattes", last: "Hansane", pos: "LB" },
  ],
  "Magdeborg": [
    { first: "Dominik", last: "Reimenn", pos: "GK" },
    { first: "Noah", last: "Kruthe", pos: "GK" },
    { first: "Daniel", last: "Hebar", pos: "CB" },
    { first: "Marcus", last: "Mathisane", pos: "CB" },
    { first: "Jamie", last: "Lawrance", pos: "CB" },
    { first: "Tobias", last: "Müllar", pos: "RB" },
    { first: "Cristiano", last: "Piccinie", pos: "LB" },
    { first: "Jean", last: "Hugonete", pos: "CB" },
    { first: "Connor", last: "Metcalfa", pos: "CM" },
    { first: "Baris", last: "Atike", pos: "AM" },
    { first: "Mohammed", last: "El Hankourie", pos: "AM" },
    { first: "Tatsuya", last: "Itoe", pos: "LW" },
    { first: "Livan", last: "Burcue", pos: "RW" },
    { first: "Martijn", last: "Kaarse", pos: "ST" },
    { first: "Abu-Bakarr", last: "Kargbo", pos: "ST" },
    { first: "Xavier", last: "Amaechie", pos: "RW" },
  ],
  "Greuther Fürthe": [
    { first: "Jonas", last: "Urbeg", pos: "GK" },
    { first: "Nahuel", last: "Nolle", pos: "GK" },
    { first: "Maximilian", last: "Bauar", pos: "CB" },
    { first: "Gideon", last: "Junge", pos: "CB" },
    { first: "Damian", last: "Michalske", pos: "CB" },
    { first: "Nico", last: "Gießelmenn", pos: "LB" },
    { first: "Tim", last: "Lemperla", pos: "RW" },
    { first: "Branimir", last: "Hrgoto", pos: "ST" },
    { first: "Roberto", last: "Massimo", pos: "RW" },
    { first: "Julian", last: "Greene", pos: "AM" },
    { first: "Felix", last: "Klause", pos: "LW" },
    { first: "Oussama", last: "Haddadie", pos: "LB" },
    { first: "Simon", last: "Asto", pos: "RB" },
    { first: "Armindo", last: "Siebe", pos: "AM" },
    { first: "Noel", last: "Futkeue", pos: "ST" },
    { first: "Dennis", last: "Srbenye", pos: "ST" },
  ],
  "Darmstadt 98": [
    { first: "Marcel", last: "Schuhne", pos: "GK" },
    { first: "Steve", last: "Krolle", pos: "GK" },
    { first: "Matej", last: "Maglico", pos: "CB" },
    { first: "Christoph", last: "Zimmermenn", pos: "CB" },
    { first: "Jannik", last: "Müllar", pos: "CB" },
    { first: "Fabian", last: "Hollande", pos: "LB" },
    { first: "Christoph", last: "Klarar", pos: "CB" },
    { first: "Marvin", last: "Mehleme", pos: "AM" },
    { first: "Fraser", last: "Hornbye", pos: "ST" },
    { first: "Aleksandar", last: "Vukotech", pos: "CB" },
    { first: "Klaus", last: "Gjasulo", pos: "DM" },
    { first: "Killian", last: "Corredore", pos: "RW" },
    { first: "Isac", last: "Lidbarg", pos: "ST" },
    { first: "Oscar", last: "Vilhelmssen", pos: "ST" },
    { first: "Bartol", last: "Franjech", pos: "CM" },
    { first: "Mathias", last: "Honsake", pos: "LW" },
  ],
  "Elversborg": [
    { first: "Nicolas", last: "Kristofe", pos: "GK" },
    { first: "Felix", last: "Gebhardte", pos: "GK" },
    { first: "Frederik", last: "Schmahle", pos: "CB" },
    { first: "Carlo", last: "Sickingar", pos: "DM" },
    { first: "Lukas", last: "Pinckarte", pos: "CB" },
    { first: "Marcel", last: "Correio", pos: "CB" },
    { first: "Tom", last: "Zimmerschiede", pos: "AM" },
    { first: "Jannik", last: "Rochelte", pos: "RW" },
    { first: "Muhammed", last: "Damare", pos: "AM" },
    { first: "Fisnik", last: "Asllanie", pos: "ST" },
    { first: "Bjarne", last: "Thoelka", pos: "CB" },
    { first: "Robin", last: "Fellhauar", pos: "RB" },
    { first: "Paul", last: "Stocke", pos: "ST" },
    { first: "Semih", last: "Şahine", pos: "CM" },
    { first: "Younes", last: "Ebnoutalibe", pos: "ST" },
    { first: "Manuel", last: "Feile", pos: "LB" },
  ],
  "Braunschwyg": [
    { first: "Marko", last: "Johanssen", pos: "GK" },
    { first: "Ron-Thorben", last: "Hofmenn", pos: "GK" },
    { first: "Jannis", last: "Nikolaue", pos: "CB" },
    { first: "Filip", last: "Benkovech", pos: "CB" },
    { first: "Robin", last: "Krauße", pos: "DM" },
    { first: "Anton", last: "Donkore", pos: "LB" },
    { first: "Tarsis", last: "Bongo", pos: "RW" },
    { first: "Christian", last: "Contehe", pos: "RW" },
    { first: "Rayan", last: "Philippa", pos: "ST" },
    { first: "Sven", last: "Köhlar", pos: "CM" },
    { first: "Levente", last: "Szabo", pos: "RB" },
    { first: "Fabio", last: "Di Michela", pos: "GK" },
    { first: "Johan", last: "Gómeze", pos: "AM" },
    { first: "Lino", last: "Tempelmenn", pos: "CM" },
    { first: "Sidi", last: "Sané", pos: "ST" },
    { first: "Ermin", last: "Bičakčech", pos: "CB" },
  ],
  "Münstar": [
    { first: "Johannes", last: "Schenke", pos: "GK" },
    { first: "Maximilian", last: "Schulze Niehuese", pos: "GK" },
    { first: "Alexander", last: "Hahne", pos: "CB" },
    { first: "Joël", last: "Grodowske", pos: "ST" },
    { first: "Thomas", last: "Koke", pos: "CB" },
    { first: "Lukas", last: "Frenkarte", pos: "CB" },
    { first: "Marc", last: "Lorenze", pos: "RB" },
    { first: "Luca", last: "Bazzolie", pos: "LB" },
    { first: "Simon", last: "Scherdar", pos: "CB" },
    { first: "Yassine", last: "Bouchamo", pos: "AM" },
    { first: "Daniel", last: "Kyerewao", pos: "CM" },
    { first: "Andrew", last: "Wootene", pos: "ST" },
    { first: "Malik", last: "Batmaze", pos: "RW" },
    { first: "Ousman", last: "Touré", pos: "RW" },
    { first: "Etienne", last: "Amenyidoe", pos: "LW" },
    { first: "Charalambos", last: "Makridise", pos: "DM" },
  ],
  "Ulme 1846": [
    { first: "Christian", last: "Ortage", pos: "GK" },
    { first: "Niklas", last: "Köllee", pos: "GK" },
    { first: "Johannes", last: "Reicharte", pos: "CB" },
    { first: "Tom", last: "Gaale", pos: "CB" },
    { first: "Lucas", last: "Rösar", pos: "ST" },
    { first: "Maurice", last: "Krattenmachar", pos: "AM" },
    { first: "Philipp", last: "Strompfe", pos: "CB" },
    { first: "Lasse", last: "Voglar", pos: "DM" },
    { first: "Bastian", last: "Allgaiar", pos: "RB" },
    { first: "Dennis", last: "Chesso", pos: "LW" },
    { first: "Semih", last: "Sahine", pos: "CM" },
    { first: "Felix", last: "Higle", pos: "ST" },
    { first: "Leonardo", last: "Scienzo", pos: "RW" },
    { first: "Romario", last: "Rösche", pos: "RB" },
    { first: "Aaron", last: "Kellar", pos: "CM" },
    { first: "Oguzhan", last: "Özyakupe", pos: "AM" },
  ],
};
