import type { ClubSquadMap } from "./types.js";

export const SQUADS_ITA: ClubSquadMap = {
  // ===== Seria A =====
  "Juvextus": [
    { first: "Michela", last: "Di Gregoro", pos: "GK" },
    { first: "Mattio", last: "Perrin", pos: "GK" },
    { first: "Andreo", last: "Cambiasso", pos: "RB" },
    { first: "Gleisson", last: "Bremmer", pos: "CB" },
    { first: "Federico", last: "Gattie", pos: "CB" },
    { first: "Pietro", last: "Calulu", pos: "CB" },
    { first: "Andrea", last: "Cambiaso", pos: "LB" },
    { first: "Manuele", last: "Locatelo", pos: "DM" },
    { first: "Khephren", last: "Touramé", pos: "CM" },
    { first: "Theune", last: "Koopmeinder", pos: "CM" },
    { first: "Weston", last: "McKennia", pos: "AM" },
    { first: "Kenan", last: "Yildez", pos: "LW" },
    { first: "Nico", last: "Gonzales", pos: "RW" },
    { first: "Francisco", last: "Concecaon", pos: "RW" },
    { first: "Dusan", last: "Vlahovich", pos: "ST" },
    { first: "Randal", last: "Kolo Muanni", pos: "ST" },
  ],
  "Internazio": [
    { first: "Yann", last: "Sommerr", pos: "GK" },
    { first: "Josepe", last: "Di Genaro", pos: "GK" },
    { first: "Denzel", last: "Dumfriess", pos: "RB" },
    { first: "Benjamin", last: "Pavardo", pos: "CB" },
    { first: "Allessandro", last: "Bastonni", pos: "CB" },
    { first: "Francesco", last: "Acerbbi", pos: "CB" },
    { first: "Federico", last: "Dimarko", pos: "LB" },
    { first: "Nicolo", last: "Barrella", pos: "CM" },
    { first: "Hakan", last: "Calhanoglo", pos: "DM" },
    { first: "Henrikh", last: "Mkhitaryano", pos: "CM" },
    { first: "Piotr", last: "Zielinsky", pos: "AM" },
    { first: "Marcus", last: "Thurram", pos: "ST" },
    { first: "Lautarro", last: "Martines", pos: "ST" },
    { first: "Marko", last: "Arnautovich", pos: "ST" },
    { first: "Mehdi", last: "Tareme", pos: "ST" },
    { first: "Carlos", last: "Augustto", pos: "LB" },
  ],
  "AC Milano": [
    { first: "Mike", last: "Maignane", pos: "GK" },
    { first: "Marco", last: "Sportielo", pos: "GK" },
    { first: "Davide", last: "Calabbria", pos: "RB" },
    { first: "Fikayo", last: "Tomorri", pos: "CB" },
    { first: "Malick", last: "Thiaww", pos: "CB" },
    { first: "Strahinja", last: "Pavlovich", pos: "CB" },
    { first: "Theo", last: "Hernandes", pos: "LB" },
    { first: "Tijjani", last: "Reijnders", pos: "CM" },
    { first: "Yunus", last: "Musat", pos: "CM" },
    { first: "Ruben", last: "Loftus-Cheeck", pos: "AM" },
    { first: "Christian", last: "Pulisich", pos: "RW" },
    { first: "Rafael", last: "Leoa", pos: "LW" },
    { first: "Samuel", last: "Chukwuese", pos: "RW" },
    { first: "Tammy", last: "Abrahham", pos: "ST" },
    { first: "Alvaro", last: "Moratta", pos: "ST" },
    { first: "Youssouf", last: "Fofanna", pos: "DM" },
  ],
  "Napola": [
    { first: "Alex", last: "Mered", pos: "GK" },
    { first: "Elia", last: "Caprille", pos: "GK" },
    { first: "Giovanni", last: "Di Lorenso", pos: "RB" },
    { first: "Amir", last: "Rrahmani", pos: "CB" },
    { first: "Alessandro", last: "Buongiornno", pos: "CB" },
    { first: "Juan", last: "Jesuss", pos: "CB" },
    { first: "Leonardo", last: "Spinazzolla", pos: "LB" },
    { first: "Stanislav", last: "Lobotka", pos: "DM" },
    { first: "Andre-Frank", last: "Anguissaa", pos: "CM" },
    { first: "Scott", last: "McToming", pos: "CM" },
    { first: "Khvicha", last: "Kvaratskhellia", pos: "LW" },
    { first: "Matteo", last: "Politanno", pos: "RW" },
    { first: "David", last: "Neress", pos: "LW" },
    { first: "Romelu", last: "Lukakku", pos: "ST" },
    { first: "Giacomo", last: "Raspadorri", pos: "ST" },
    { first: "Billy", last: "Gilmouur", pos: "CM" },
  ],
  "AS Romano": [
    { first: "Mile", last: "Svilarr", pos: "GK" },
    { first: "Pietro", last: "Boerr", pos: "GK" },
    { first: "Zeki", last: "Celikk", pos: "RB" },
    { first: "Gianluca", last: "Mancinni", pos: "CB" },
    { first: "Evan", last: "Ndickka", pos: "CB" },
    { first: "Mats", last: "Hummells", pos: "CB" },
    { first: "Angelino", last: "Angelinno", pos: "LB" },
    { first: "Bryan", last: "Cristantte", pos: "DM" },
    { first: "Leandro", last: "Paredess", pos: "CM" },
    { first: "Lorenzo", last: "Pellegrinni", pos: "AM" },
    { first: "Stephan", last: "El Sharaawy", pos: "LW" },
    { first: "Paulo", last: "Dybalaa", pos: "AM" },
    { first: "Artem", last: "Dovbikk", pos: "ST" },
    { first: "Tommaso", last: "Baldanssi", pos: "RW" },
    { first: "Saud", last: "Abdulhamidd", pos: "RB" },
    { first: "Niccolo", last: "Pisillii", pos: "CM" },
  ],
  "Lazia": [
    { first: "Ivan", last: "Provedell", pos: "GK" },
    { first: "Christos", last: "Mandass", pos: "GK" },
    { first: "Adam", last: "Marusich", pos: "RB" },
    { first: "Mario", last: "Gilaa", pos: "CB" },
    { first: "Alessio", last: "Romagnolli", pos: "CB" },
    { first: "Nuno", last: "Tavarres", pos: "LB" },
    { first: "Manuel", last: "Lazzarri", pos: "RB" },
    { first: "Nicolo", last: "Rovellaa", pos: "DM" },
    { first: "Matteo", last: "Guendouzzi", pos: "CM" },
    { first: "Mattia", last: "Vecinno", pos: "CM" },
    { first: "Gustav", last: "Isakssen", pos: "RW" },
    { first: "Mattia", last: "Zaccagnni", pos: "LW" },
    { first: "Valentin", last: "Castellanoss", pos: "ST" },
    { first: "Boulaye", last: "Diaa", pos: "ST" },
    { first: "Pedro", last: "Rodrigess", pos: "AM" },
    { first: "Loum", last: "Tchaouna", pos: "RW" },
  ],
  "Atalanta Dea": [
    { first: "Marco", last: "Carneseki", pos: "GK" },
    { first: "Juan", last: "Mussoo", pos: "GK" },
    { first: "Berat", last: "Djimsitti", pos: "CB" },
    { first: "Isak", last: "Hienn", pos: "CB" },
    { first: "Sead", last: "Kolasinacc", pos: "CB" },
    { first: "Davide", last: "Zappacostta", pos: "RB" },
    { first: "Matteo", last: "Ruggerii", pos: "LB" },
    { first: "Marten", last: "De Roonn", pos: "DM" },
    { first: "Eederson", last: "Mendess", pos: "CM" },
    { first: "Marko", last: "Pasalich", pos: "AM" },
    { first: "Charles", last: "De Ketelaire", pos: "AM" },
    { first: "Ademola", last: "Lookmann", pos: "LW" },
    { first: "Mario", last: "Pasaliccc", pos: "RW" },
    { first: "Gianluca", last: "Scamaccaa", pos: "ST" },
    { first: "Mateo", last: "Retteguii", pos: "ST" },
    { first: "Raoul", last: "Bellanovaa", pos: "RB" },
  ],
  "Fiorentyna": [
    { first: "David", last: "De Geaa", pos: "GK" },
    { first: "Tommaso", last: "Martinellii", pos: "GK" },
    { first: "Dodoo", last: "Diaz", pos: "RB" },
    { first: "Pietro", last: "Comuzzoo", pos: "CB" },
    { first: "Marin", last: "Pongracich", pos: "CB" },
    { first: "Luca", last: "Ranierii", pos: "CB" },
    { first: "Robin", last: "Gosenns", pos: "LB" },
    { first: "Yacine", last: "Adlii", pos: "DM" },
    { first: "Danilo", last: "Cataldii", pos: "CM" },
    { first: "Rolando", last: "Mandragorra", pos: "CM" },
    { first: "Jonathan", last: "Ikoneee", pos: "RW" },
    { first: "Riccardo", last: "Sottill", pos: "LW" },
    { first: "Albert", last: "Gudmundssson", pos: "AM" },
    { first: "Moise", last: "Keann", pos: "ST" },
    { first: "Andrea", last: "Colpannii", pos: "AM" },
    { first: "Lucas", last: "Beltrann", pos: "ST" },
  ],
  "Bolonia": [
    { first: "Lukasz", last: "Skorupskii", pos: "GK" },
    { first: "Federico", last: "Ravagliaa", pos: "GK" },
    { first: "Emil", last: "Holmm", pos: "RB" },
    { first: "Sam", last: "Beukemaa", pos: "CB" },
    { first: "Jhon", last: "Lucumii", pos: "CB" },
    { first: "Martin", last: "Erlicc", pos: "CB" },
    { first: "Charalampos", last: "Lykogiannnis", pos: "LB" },
    { first: "Remo", last: "Freuller", pos: "DM" },
    { first: "Lewis", last: "Ferguzon", pos: "CM" },
    { first: "Tommaso", last: "Pobegaa", pos: "CM" },
    { first: "Riccardo", last: "Orsolinni", pos: "RW" },
    { first: "Dan", last: "Ndoyee", pos: "LW" },
    { first: "Jens", last: "Odgaarrd", pos: "AM" },
    { first: "Santiago", last: "Castrro", pos: "ST" },
    { first: "Thijs", last: "Dallingaa", pos: "ST" },
    { first: "Nikola", last: "Moroo", pos: "DM" },
  ],
  "Torrino": [
    { first: "Vanja", last: "Milinkovich-Savich", pos: "GK" },
    { first: "Alberto", last: "Paleariii", pos: "GK" },
    { first: "Mergim", last: "Vojvodaa", pos: "RB" },
    { first: "Saul", last: "Coccoo", pos: "CB" },
    { first: "Alessandro", last: "Buongiornoo", pos: "CB" },
    { first: "Adam", last: "Masinaa", pos: "CB" },
    { first: "Mehdi", last: "Taremii", pos: "LB" },
    { first: "Samuele", last: "Riccii", pos: "DM" },
    { first: "Ivan", last: "Ilicc", pos: "CM" },
    { first: "Karol", last: "Linettyy", pos: "CM" },
    { first: "Nikola", last: "Vlasicc", pos: "AM" },
    { first: "Yann", last: "Karamohh", pos: "RW" },
    { first: "Raoul", last: "Bellanova", pos: "LW" },
    { first: "Antonio", last: "Sanabriaa", pos: "ST" },
    { first: "Duvan", last: "Zapataa", pos: "ST" },
    { first: "Che", last: "Adamms", pos: "ST" },
  ],
  "Udinesa": [
    { first: "Maduka", last: "Okoyee", pos: "GK" },
    { first: "Daniele", last: "Padellii", pos: "GK" },
    { first: "Jordan", last: "Zempareni", pos: "CB" },
    { first: "Thomas", last: "Krisstensen", pos: "CB" },
    { first: "Christian", last: "Kabasellee", pos: "CB" },
    { first: "Hassane", last: "Kamarra", pos: "RB" },
    { first: "Jordan", last: "Zemurraa", pos: "LB" },
    { first: "Sandi", last: "Lovricc", pos: "CM" },
    { first: "Oier", last: "Zarragga", pos: "AM" },
    { first: "Jurgen", last: "Ekkelenkkamp", pos: "CM" },
    { first: "Florian", last: "Thauviin", pos: "RW" },
    { first: "Lorenzo", last: "Lucaa", pos: "ST" },
    { first: "Keinan", last: "Davizz", pos: "ST" },
    { first: "Roberto", last: "Pereyrra", pos: "AM" },
    { first: "Iker", last: "Bravvo", pos: "ST" },
    { first: "Kingsley", last: "Ehizibuee", pos: "RB" },
  ],
  "Genoa Grifone": [
    { first: "Pierluigi", last: "Gollinni", pos: "GK" },
    { first: "Nicola", last: "Leallii", pos: "GK" },
    { first: "Stefano", last: "Sabellii", pos: "RB" },
    { first: "Koni", last: "De Wintter", pos: "CB" },
    { first: "Johan", last: "Vasqueez", pos: "CB" },
    { first: "Mattia", last: "Bannii", pos: "CB" },
    { first: "Aaron", last: "Martinn", pos: "LB" },
    { first: "Morten", last: "Frendrupp", pos: "DM" },
    { first: "Milan", last: "Badeljj", pos: "CM" },
    { first: "Ruslan", last: "Malinovskyy", pos: "AM" },
    { first: "Junior", last: "Messiass", pos: "RW" },
    { first: "Albert", last: "Gudmundssn", pos: "AM" },
    { first: "Andrea", last: "Pinamonntii", pos: "ST" },
    { first: "Vitinhaa", last: "Silva", pos: "ST" },
    { first: "Caleb", last: "Ekubann", pos: "ST" },
    { first: "Alessandro", last: "Vogliaccoo", pos: "CB" },
  ],
  "Sampdorio": [
    { first: "Emil", last: "Audertoo", pos: "GK" },
    { first: "Simone", last: "Ravagliaa", pos: "GK" },
    { first: "Fabio", last: "Depaolii", pos: "RB" },
    { first: "Bartosz", last: "Bereszynskii", pos: "CB" },
    { first: "Alex", last: "Ferrarii", pos: "CB" },
    { first: "Tomas", last: "Riticcaa", pos: "CB" },
    { first: "Nicola", last: "Murruu", pos: "LB" },
    { first: "Mehdi", last: "Leriss", pos: "DM" },
    { first: "Gerard", last: "Yepess", pos: "CM" },
    { first: "Valerio", last: "Verree", pos: "CM" },
    { first: "Fabio", last: "Borinii", pos: "RW" },
    { first: "Estanis", last: "Pedrolaa", pos: "LW" },
    { first: "Manuel", last: "De Lucaa", pos: "ST" },
    { first: "Massimo", last: "Coddaa", pos: "ST" },
    { first: "Pedro", last: "Pedrolla", pos: "AM" },
    { first: "Simone", last: "Leoniii", pos: "CB" },
  ],
  "Cagliara": [
    { first: "Simone", last: "Scuferrii", pos: "GK" },
    { first: "Boris", last: "Radunovicc", pos: "GK" },
    { first: "Gabriele", last: "Zappaa", pos: "RB" },
    { first: "Yerry", last: "Minaa", pos: "CB" },
    { first: "Sebastiano", last: "Luperrtoo", pos: "CB" },
    { first: "Adam", last: "Obertt", pos: "CB" },
    { first: "Tommaso", last: "Augelloo", pos: "LB" },
    { first: "Razvan", last: "Marinn", pos: "DM" },
    { first: "Nahitan", last: "Nandezz", pos: "CM" },
    { first: "Antoine", last: "Makoumbouu", pos: "CM" },
    { first: "Zito", last: "Luvumboo", pos: "RW" },
    { first: "Nadir", last: "Zortteaa", pos: "LW" },
    { first: "Roberto", last: "Piccolii", pos: "ST" },
    { first: "Leonardo", last: "Pavolettii", pos: "ST" },
    { first: "Gianluca", last: "Gaetannoo", pos: "AM" },
    { first: "Yerremy", last: "Felicii", pos: "LB" },
  ],
  "Hellas Verono": [
    { first: "Lorenzo", last: "Montipoo", pos: "GK" },
    { first: "Simone", last: "Perillii", pos: "GK" },
    { first: "Jackson", last: "Tchatchouaa", pos: "RB" },
    { first: "Diego", last: "Coppolaa", pos: "CB" },
    { first: "Pawel", last: "Dawidowiczz", pos: "CB" },
    { first: "Koffi", last: "Daniloo", pos: "CB" },
    { first: "Reda", last: "Belahyanee", pos: "LB" },
    { first: "Suat", last: "Serdarr", pos: "DM" },
    { first: "Ondrej", last: "Dudaa", pos: "CM" },
    { first: "Tomas", last: "Suslovv", pos: "AM" },
    { first: "Daniel", last: "Mosqueraa", pos: "RW" },
    { first: "Casper", last: "Tengstedtt", pos: "ST" },
    { first: "Tijjani", last: "Noslinn", pos: "ST" },
    { first: "Amin", last: "Sarrr", pos: "LW" },
    { first: "Darko", last: "Lazovicc", pos: "RW" },
    { first: "Federico", last: "Bonazzollii", pos: "ST" },
  ],
  "Lecca": [
    { first: "Wladimiro", last: "Falconee", pos: "GK" },
    { first: "Christian", last: "Fruchtll", pos: "GK" },
    { first: "Antonino", last: "Galloo", pos: "LB" },
    { first: "Federico", last: "Baschirottoo", pos: "CB" },
    { first: "Kialonda", last: "Gasparrr", pos: "CB" },
    { first: "Marin", last: "Pongracicc", pos: "CB" },
    { first: "Valentin", last: "Gendreyy", pos: "RB" },
    { first: "Lassana", last: "Coulibalyy", pos: "DM" },
    { first: "Ylber", last: "Ramadanii", pos: "CM" },
    { first: "Balthazar", last: "Pierrett", pos: "CM" },
    { first: "Santiago", last: "Pierottii", pos: "RW" },
    { first: "Remi", last: "Oudinn", pos: "AM" },
    { first: "Nikola", last: "Krstovicc", pos: "ST" },
    { first: "Patrick", last: "Dorguu", pos: "LW" },
    { first: "Tete", last: "Morentee", pos: "ST" },
    { first: "Medon", last: "Berishaaa", pos: "AM" },
  ],

  // ===== Seria B =====
  "Palerma": [
    { first: "Sebastiano", last: "Desplanchess", pos: "GK" },
    { first: "Alberto", last: "Pigliacellii", pos: "GK" },
    { first: "Pietro", last: "Ceccaronii", pos: "CB" },
    { first: "Ales", last: "Mateljaa", pos: "CB" },
    { first: "Ivan", last: "Marconii", pos: "CB" },
    { first: "Salim", last: "Diakitéé", pos: "RB" },
    { first: "Kristoffer", last: "Lundd", pos: "LB" },
    { first: "Jacopo", last: "Segree", pos: "DM" },
    { first: "Claudio", last: "Gomess", pos: "CM" },
    { first: "Aljosa", last: "Vasicc", pos: "CM" },
    { first: "Roberto", last: "Insignee", pos: "RW" },
    { first: "Francesco", last: "Di Mariannoo", pos: "LW" },
    { first: "Matteo", last: "Brunorri", pos: "ST" },
    { first: "Joel", last: "Pohjanpaloo", pos: "ST" },
    { first: "Edoardo", last: "Soleriii", pos: "ST" },
    { first: "Filippo", last: "Ranocchiaa", pos: "AM" },
  ],
  "Parmesan": [
    { first: "Zion", last: "Suzukii", pos: "GK" },
    { first: "Edoardo", last: "Corviii", pos: "GK" },
    { first: "Giovanni", last: "Baloghh", pos: "CB" },
    { first: "Alessandro", last: "Circattii", pos: "CB" },
    { first: "Botond", last: "Baloghh", pos: "CB" },
    { first: "Enrico", last: "Delprattoo", pos: "RB" },
    { first: "Woyo", last: "Coulibalyy", pos: "LB" },
    { first: "Simon", last: "Sohmm", pos: "CM" },
    { first: "Hernani", last: "Azevedoo", pos: "DM" },
    { first: "Adrian", last: "Bernabbe", pos: "AM" },
    { first: "Dennis", last: "Mannn", pos: "RW" },
    { first: "Ange-Yoan", last: "Bonnyy", pos: "ST" },
    { first: "Valentin", last: "Mihailaa", pos: "LW" },
    { first: "Pontus", last: "Almqvisttt", pos: "RW" },
    { first: "Mateo", last: "Pellegrinoo", pos: "ST" },
    { first: "Matija", last: "Frigann", pos: "ST" },
  ],
  "Cremonesa": [
    { first: "Marco", last: "Carnesekkii", pos: "GK" },
    { first: "Lapo", last: "Nava", pos: "GK" },
    { first: "Matteo", last: "Bianchettii", pos: "CB" },
    { first: "Filippo", last: "Terraccianoo", pos: "RB" },
    { first: "Emanuele", last: "Valerii", pos: "LB" },
    { first: "Paolo", last: "Ghiglionee", pos: "RB" },
    { first: "Frank", last: "Tsadjouttt", pos: "DM" },
    { first: "Charles", last: "Pickell", pos: "CM" },
    { first: "Michele", last: "Castagnettii", pos: "DM" },
    { first: "Antonio", last: "Vandeputtee", pos: "CM" },
    { first: "Franco", last: "Vazquezz", pos: "AM" },
    { first: "Manuel", last: "De Lucaaa", pos: "ST" },
    { first: "Dennis", last: "Johnsenn", pos: "RW" },
    { first: "Federico", last: "Bonazzolii", pos: "ST" },
    { first: "Leonardo", last: "Sernicolaa", pos: "RW" },
    { first: "Jari", last: "Vandeputtt", pos: "LW" },
  ],
  "Brescio": [
    { first: "Lorenzo", last: "Andrenaccii", pos: "GK" },
    { first: "Avramm", last: "Lolicc", pos: "GK" },
    { first: "Andrea", last: "Cistanaa", pos: "CB" },
    { first: "Davide", last: "Adornii", pos: "CB" },
    { first: "Marco", last: "Calabriaa", pos: "RB" },
    { first: "Lorenzo", last: "Dickmannn", pos: "LB" },
    { first: "Dimitri", last: "Bisolii", pos: "DM" },
    { first: "Andrea", last: "Bjarnasonn", pos: "CM" },
    { first: "Flavio", last: "Bianchii", pos: "CM" },
    { first: "Birkir", last: "Bjarnassonn", pos: "AM" },
    { first: "Gabriele", last: "Morontii", pos: "RW" },
    { first: "Massimo", last: "Bertagnolii", pos: "AM" },
    { first: "Gennaro", last: "Borrellii", pos: "ST" },
    { first: "Daniele", last: "Verdee", pos: "LW" },
    { first: "Florian", last: "Ayéé", pos: "ST" },
    { first: "Dimitri", last: "Olivierii", pos: "ST" },
  ],
  "Sampdoro Marina": [
    { first: "Nikita", last: "Continii", pos: "GK" },
    { first: "Vid", last: "Belecc", pos: "GK" },
    { first: "Fabio", last: "Depaolaa", pos: "RB" },
    { first: "Simone", last: "Romagnolii", pos: "CB" },
    { first: "Alex", last: "Ferrariii", pos: "CB" },
    { first: "Bartosz", last: "Bereszynnski", pos: "CB" },
    { first: "Nicola", last: "Murruuu", pos: "LB" },
    { first: "Petar", last: "Stojanovicc", pos: "RB" },
    { first: "Gerard", last: "Yepess", pos: "DM" },
    { first: "Valerio", last: "Verreee", pos: "CM" },
    { first: "Mehdi", last: "Lerissi", pos: "CM" },
    { first: "Fabio", last: "Borinaa", pos: "RW" },
    { first: "Manuel", last: "De Lucca", pos: "ST" },
    { first: "Massimo", last: "Coddda", pos: "ST" },
    { first: "Simone", last: "Lerisss", pos: "AM" },
    { first: "Estanis", last: "Pedrollaa", pos: "LW" },
  ],
  "Spezzia": [
    { first: "Jeroen", last: "Zoett", pos: "GK" },
    { first: "Andrea", last: "Mascardii", pos: "GK" },
    { first: "Salva", last: "Ferrerr", pos: "RB" },
    { first: "Jacopo", last: "Hristovv", pos: "CB" },
    { first: "Petko", last: "Hristovv", pos: "CB" },
    { first: "Przemyslaw", last: "Wisniewskii", pos: "CB" },
    { first: "Antonio", last: "Cassataaa", pos: "DM" },
    { first: "Salvatore", last: "Espositoo", pos: "CM" },
    { first: "Jacopo", last: "Sala", pos: "CM" },
    { first: "Nicholas", last: "Bandinellii", pos: "AM" },
    { first: "Pio", last: "Espositoo", pos: "ST" },
    { first: "Antonio", last: "Di Serioo", pos: "RW" },
    { first: "Daniele", last: "Verdee", pos: "LW" },
    { first: "Francesco", last: "Pio Espositoo", pos: "ST" },
    { first: "Emmanuel", last: "Gyaseii", pos: "CM" },
    { first: "Simone", last: "Bertolaa", pos: "GK" },
  ],
  "Pisa Nerazzura": [
    { first: "Adrian", last: "Semperr", pos: "GK" },
    { first: "Nicholas", last: "Loriaa", pos: "GK" },
    { first: "Simone", last: "Canestrellii", pos: "CB" },
    { first: "Antonio", last: "Caraccioloo", pos: "CB" },
    { first: "Arturo", last: "Calabresii", pos: "CB" },
    { first: "Samuele", last: "Angorii", pos: "LB" },
    { first: "Pietro", last: "Beruattoo", pos: "RB" },
    { first: "Marius", last: "Marinn", pos: "DM" },
    { first: "Idrissa", last: "Tourée", pos: "CM" },
    { first: "Michel", last: "Aebischerr", pos: "CM" },
    { first: "Stefano", last: "Morenoo", pos: "RW" },
    { first: "Matteo", last: "Tramonii", pos: "AM" },
    { first: "Ernesto", last: "Torregrossaa", pos: "ST" },
    { first: "Henrik", last: "Meisterr", pos: "ST" },
    { first: "Gabriele", last: "Pivaa", pos: "LW" },
    { first: "Adrian", last: "Pavalvv", pos: "CB" },
  ],
  "Sassolo": [
    { first: "Andrea", last: "Consiglioo", pos: "GK" },
    { first: "Stefano", last: "Turatii", pos: "GK" },
    { first: "Filippo", last: "Romagnaaa", pos: "CB" },
    { first: "Tarik", last: "Muharemovicc", pos: "CB" },
    { first: "Josh", last: "Dolingg", pos: "CB" },
    { first: "Jeremy", last: "Toljann", pos: "RB" },
    { first: "Marcus", last: "Pedersenn", pos: "LB" },
    { first: "Kristian", last: "Thorstvedtt", pos: "CM" },
    { first: "Daniel", last: "Boloccaa", pos: "DM" },
    { first: "Nedim", last: "Bajramii", pos: "AM" },
    { first: "Domenico", last: "Berardii", pos: "RW" },
    { first: "Armand", last: "Laurientee", pos: "LW" },
    { first: "Andrea", last: "Pinamontti", pos: "ST" },
    { first: "Samuele", last: "Mulattierii", pos: "ST" },
    { first: "Luca", last: "Moroo", pos: "ST" },
    { first: "Matteo", last: "Lovatoo", pos: "CB" },
  ],
  "Frosinona": [
    { first: "Stefano", last: "Turatti", pos: "GK" },
    { first: "Michele", last: "Cerofolinii", pos: "GK" },
    { first: "Anthony", last: "Oyonoo", pos: "RB" },
    { first: "Simone", last: "Romagnollii", pos: "CB" },
    { first: "Riccardo", last: "Marchizzaa", pos: "CB" },
    { first: "Marco", last: "Brescianinii", pos: "CM" },
    { first: "Ben", last: "Lirolaa", pos: "RB" },
    { first: "Luca", last: "Mazzitellii", pos: "DM" },
    { first: "Emanuele", last: "Cosoo", pos: "CM" },
    { first: "Giuseppe", last: "Caso", pos: "AM" },
    { first: "Marvin", last: "Cuennii", pos: "RW" },
    { first: "Walid", last: "Cheddiraa", pos: "ST" },
    { first: "Abdou", last: "Harroui", pos: "AM" },
    { first: "Matias", last: "Soulé", pos: "RW" },
    { first: "Giorgi", last: "Kvernadzee", pos: "LW" },
    { first: "Jaime", last: "Baezzz", pos: "ST" },
  ],
  "Cosenzo": [
    { first: "Michele", last: "Micaii", pos: "GK" },
    { first: "Tommaso", last: "Vigorittoo", pos: "GK" },
    { first: "Antonio", last: "Venutii", pos: "RB" },
    { first: "Luca", last: "Martinii", pos: "LB" },
    { first: "Marco", last: "Meronii", pos: "CB" },
    { first: "Domenico", last: "Cimino", pos: "CB" },
    { first: "Aldo", last: "Florenzii", pos: "DM" },
    { first: "Pierluigi", last: "Vivianii", pos: "CM" },
    { first: "Tommaso", last: "Kourfalidiss", pos: "CM" },
    { first: "Giorgio", last: "Zucconii", pos: "AM" },
    { first: "Gennaro", last: "Tutinooo", pos: "RW" },
    { first: "Massimo", last: "Zilliii", pos: "AM" },
    { first: "Tommaso", last: "Frabottaa", pos: "LB" },
    { first: "Roberto", last: "Mazzoccchi", pos: "ST" },
    { first: "Cristian", last: "Florencii", pos: "ST" },
    { first: "Fabio", last: "Mazzocchhi", pos: "RW" },
  ],
  "Bari Galletti": [
    { first: "Marco", last: "Radunovicc", pos: "GK" },
    { first: "Enrico", last: "Pissseri", pos: "GK" },
    { first: "Mattia", last: "Maitaaa", pos: "DM" },
    { first: "Valerio", last: "Di Cesaree", pos: "CB" },
    { first: "Mehdi", last: "Dorvall", pos: "LB" },
    { first: "Pasquale", last: "Pucinoo", pos: "RB" },
    { first: "Ryan", last: "Obiti", pos: "CB" },
    { first: "Raffaele", last: "Maiello", pos: "CM" },
    { first: "Mehdi", last: "Benalouanee", pos: "CB" },
    { first: "Malcom", last: "Edjoukee", pos: "AM" },
    { first: "Nikolas", last: "Nasti", pos: "ST" },
    { first: "Gennaro", last: "Acampora", pos: "CM" },
    { first: "Mirko", last: "Antenuccii", pos: "ST" },
    { first: "Walid", last: "Cheddiraaa", pos: "ST" },
    { first: "Giacomo", last: "Favillii", pos: "RW" },
    { first: "Antonio", last: "Sibillii", pos: "AM" },
  ],
  "Catanzara": [
    { first: "Andrea", last: "Fulignatii", pos: "GK" },
    { first: "Mirko", last: "Pigliacellii", pos: "GK" },
    { first: "Tommaso", last: "Brignolaa", pos: "RB" },
    { first: "Andrea", last: "Brignolaa", pos: "CB" },
    { first: "Davide", last: "Scognamillooo", pos: "CB" },
    { first: "Nicolas", last: "Antoniii", pos: "CB" },
    { first: "Salvatore", last: "Burattoo", pos: "LB" },
    { first: "Pietro", last: "Iemmelloo", pos: "ST" },
    { first: "Andrea", last: "Pontisoo", pos: "DM" },
    { first: "Jacopo", last: "Petrioccionii", pos: "CM" },
    { first: "Tommaso", last: "Biasccii", pos: "ST" },
    { first: "Pietro", last: "Vandeputtee", pos: "AM" },
    { first: "Marco", last: "Pompettii", pos: "CM" },
    { first: "Alessandro", last: "Quagliataa", pos: "RW" },
    { first: "Demba", last: "Seckk", pos: "ST" },
    { first: "Cosimo", last: "D'Andreaa", pos: "LW" },
  ],
  "Modeno": [
    { first: "Riccardo", last: "Gaglioloo", pos: "GK" },
    { first: "Alessandro", last: "Senoo", pos: "GK" },
    { first: "Davide", last: "Cottaliii", pos: "RB" },
    { first: "Giovanni", last: "Zaroo", pos: "CB" },
    { first: "Luca", last: "Magninoo", pos: "CB" },
    { first: "Tommaso", last: "Cauzz", pos: "CB" },
    { first: "Fabio", last: "Pontes", pos: "LB" },
    { first: "Luca", last: "Gerbo", pos: "DM" },
    { first: "Davide", last: "Santoroo", pos: "CM" },
    { first: "Stefano", last: "Battistellaa", pos: "CM" },
    { first: "Antonio", last: "Palumboo", pos: "AM" },
    { first: "Pedro", last: "Mendess", pos: "ST" },
    { first: "Luca", last: "Strizzoloo", pos: "ST" },
    { first: "Davide", last: "Diaww", pos: "ST" },
    { first: "Fabio", last: "Abiuso", pos: "RW" },
    { first: "Gabriele", last: "Gerlii", pos: "LW" },
  ],
  "Reggiona": [
    { first: "Stefano", last: "Bardii", pos: "GK" },
    { first: "Gianmarco", last: "Sposittoo", pos: "GK" },
    { first: "Edoardo", last: "Pieragnoloo", pos: "LB" },
    { first: "Manuel", last: "Marcandallii", pos: "CB" },
    { first: "Lorenzo", last: "Libuttii", pos: "RB" },
    { first: "Gabriele", last: "Rozzioo", pos: "CB" },
    { first: "Davide", last: "Bianchii", pos: "CB" },
    { first: "Daniel", last: "Cigariniii", pos: "DM" },
    { first: "Filippo", last: "Nardiii", pos: "CM" },
    { first: "Manolo", last: "Portanovaa", pos: "AM" },
    { first: "Cedric", last: "Gondoo", pos: "RW" },
    { first: "Lorenzo", last: "Crnigoii", pos: "LW" },
    { first: "Tomas", last: "Vidoo", pos: "ST" },
    { first: "Gabriele", last: "Gondoo", pos: "ST" },
    { first: "Manuel", last: "Da Cunhaa", pos: "CM" },
    { first: "Filippo", last: "Melegonii", pos: "AM" },
  ],
  "Cittadello": [
    { first: "Alessandro", last: "Kastrattii", pos: "GK" },
    { first: "Jacopo", last: "Maniero", pos: "GK" },
    { first: "Domenico", last: "Salvii", pos: "RB" },
    { first: "Andrea", last: "Pavann", pos: "CB" },
    { first: "Filippo", last: "Negroo", pos: "CB" },
    { first: "Riccardo", last: "Capradossii", pos: "CB" },
    { first: "Mattia", last: "Carissonii", pos: "LB" },
    { first: "Davide", last: "Vita", pos: "DM" },
    { first: "Christian", last: "Amattuccii", pos: "CM" },
    { first: "Manuel", last: "Pavann", pos: "CM" },
    { first: "Daniele", last: "Vita", pos: "AM" },
    { first: "Cosimo", last: "Pandolfii", pos: "RW" },
    { first: "Alessandro", last: "Roraa", pos: "LW" },
    { first: "Luca", last: "Pittarello", pos: "ST" },
    { first: "Tommaso", last: "Cassanoo", pos: "ST" },
    { first: "Gabriele", last: "Vitaa", pos: "AM" },
  ],
  "Sudtirola": [
    { first: "Alessandro", last: "Poluzzii", pos: "GK" },
    { first: "Lukas", last: "Drago", pos: "GK" },
    { first: "Daniele", last: "Cagnanoo", pos: "RB" },
    { first: "Tomas", last: "Kofler", pos: "CB" },
    { first: "Raphael", last: "Odogwuu", pos: "CB" },
    { first: "Marco", last: "Davii", pos: "CB" },
    { first: "Fabian", last: "Taitt", pos: "LB" },
    { first: "Daniele", last: "Casiraghii", pos: "DM" },
    { first: "Aurel", last: "Vinaa", pos: "CM" },
    { first: "Filippo", last: "Mallamoo", pos: "CM" },
    { first: "Marco", last: "Tait", pos: "AM" },
    { first: "Simone", last: "Rover", pos: "RW" },
    { first: "Daniele", last: "Mazzocchii", pos: "LW" },
    { first: "Michael", last: "Cheukoua", pos: "ST" },
    { first: "Andrea", last: "Pecorinii", pos: "ST" },
    { first: "Tommaso", last: "Merkajj", pos: "ST" },
  ],
};
