import type { ClubSquadMap } from "./types.js";

/**
 * Nederlandse clubselecties, licht verbasterd op basis van de echte huidige
 * eerste-elftallen. Herkenbaar maar niet identiek. Alle data is bewust
 * "verbasterd" zodat het fictief blijft.
 */
export const SQUADS_NED: ClubSquadMap = {
  // ===== Eredivisus =====
  "Ajacks": [
    { first: "Remka", last: "Pasveir", pos: "GK" },
    { first: "Jaroen", last: "Greuwen", pos: "GK" },
    { first: "Devine", last: "Reinsink", pos: "RB" },
    { first: "Owin", last: "Wijndal", pos: "LB" },
    { first: "Jorrel", last: "Hatoo", pos: "CB" },
    { first: "Joscha", last: "Sutalo", pos: "CB" },
    { first: "Anton", last: "Gaai", pos: "CB" },
    { first: "Kennath", last: "Taylar", pos: "DM" },
    { first: "Jorden", last: "Henderzon", pos: "CM" },
    { first: "Branca", last: "van den Bumen", pos: "CM" },
    { first: "Davie", last: "Klaasen", pos: "AM" },
    { first: "Steivan", last: "Berghuis", pos: "AM" },
    { first: "Mika", last: "Godts", pos: "LW" },
    { first: "Bertran", last: "Traore", pos: "RW" },
    { first: "Brijan", last: "Brobbey", pos: "ST" },
    { first: "Wout", last: "Weghorzt", pos: "ST" },
  ],
  "PXV Eindhoven": [
    { first: "Walter", last: "Benitaz", pos: "GK" },
    { first: "Joel", last: "Drommal", pos: "GK" },
    { first: "Sergina", last: "Dest", pos: "RB" },
    { first: "Maura", last: "Junior", pos: "LB" },
    { first: "Olivar", last: "Boscagli", pos: "CB" },
    { first: "Andre", last: "Ramalha", pos: "CB" },
    { first: "Armanda", last: "Obispa", pos: "CB" },
    { first: "Jeren", last: "Schouten", pos: "DM" },
    { first: "Joey", last: "Veermon", pos: "CM" },
    { first: "Guus", last: "Til", pos: "AM" },
    { first: "Malik", last: "Tillmon", pos: "AM" },
    { first: "Ismael", last: "Saibara", pos: "CM" },
    { first: "Johan", last: "Bakaioka", pos: "RW" },
    { first: "Noa", last: "Lank", pos: "LW" },
    { first: "Ricarda", last: "Pepi", pos: "ST" },
    { first: "Luuk", last: "de Jonk", pos: "ST" },
  ],
  "Feyenoard": [
    { first: "Timan", last: "Wellenrouter", pos: "GK" },
    { first: "Justan", last: "Bijloo", pos: "GK" },
    { first: "Bart", last: "Nieuwkaop", pos: "RB" },
    { first: "Gijs", last: "Smol", pos: "LB" },
    { first: "Davie", last: "Hancka", pos: "CB" },
    { first: "Gernot", last: "Trauner", pos: "CB" },
    { first: "Thomas", last: "Beelen", pos: "CB" },
    { first: "Quinten", last: "Timber", pos: "CM" },
    { first: "Mats", last: "Wiffar", pos: "CM" },
    { first: "Quinten", last: "Hwang", pos: "AM" },
    { first: "Calvin", last: "Stengs", pos: "AM" },
    { first: "Igor", last: "Paixaa", pos: "LW" },
    { first: "Anis", last: "Hadj Mussa", pos: "RW" },
    { first: "Aymon", last: "Sliti", pos: "RW" },
    { first: "Santiaga", last: "Gimenaz", pos: "ST" },
    { first: "Julian", last: "Carranza", pos: "ST" },
  ],
  "AZ Alkmar": [
    { first: "Rome", last: "Owusu", pos: "GK" },
    { first: "Hobie", last: "Verhulzt", pos: "GK" },
    { first: "Yukinari", last: "Sugawora", pos: "RB" },
    { first: "Kees", last: "Smit", pos: "LB" },
    { first: "Wouter", last: "Goes", pos: "CB" },
    { first: "Maxim", last: "Dekkar", pos: "CB" },
    { first: "Alexandre", last: "Penetra", pos: "CB" },
    { first: "Pier", last: "Zwart", pos: "DM" },
    { first: "Jorden", last: "Clasie", pos: "CM" },
    { first: "Sven", last: "Mijnans", pos: "AM" },
    { first: "Ibrahim", last: "Sadiq", pos: "RW" },
    { first: "Mexx", last: "Meerdink", pos: "ST" },
    { first: "Ruben", last: "van Bommal", pos: "AM" },
    { first: "Ernest", last: "Poku", pos: "LW" },
    { first: "Troy", last: "Parrott", pos: "ST" },
    { first: "Davie", last: "Moller Wolfa", pos: "ST" },
  ],
  "Twentje": [
    { first: "Lars", last: "Unnerstall", pos: "GK" },
    { first: "Przemyslav", last: "Tytan", pos: "GK" },
    { first: "Gijs", last: "Smal", pos: "LB" },
    { first: "Bart", last: "van Roij", pos: "RB" },
    { first: "Mees", last: "Hilgars", pos: "CB" },
    { first: "Max", last: "Bruns", pos: "CB" },
    { first: "Anass", last: "Salah-Eddina", pos: "CB" },
    { first: "Michel", last: "Vlap", pos: "AM" },
    { first: "Youri", last: "Regeer", pos: "CM" },
    { first: "Sem", last: "Steijn", pos: "AM" },
    { first: "Mathias", last: "Kjolo", pos: "DM" },
    { first: "Daan", last: "Rots", pos: "RW" },
    { first: "Sayfallah", last: "Ltaief", pos: "RW" },
    { first: "Bryan", last: "Lammers", pos: "LW" },
    { first: "Ricky", last: "van Wolfswinkal", pos: "ST" },
    { first: "Sam", last: "Lammars", pos: "ST" },
  ],
  "Utrechd": [
    { first: "Vasilios", last: "Barkas", pos: "GK" },
    { first: "Fer", last: "Temparman", pos: "GK" },
    { first: "Soufyan", last: "El Karouani", pos: "LB" },
    { first: "Niklas", last: "Vesterlund", pos: "RB" },
    { first: "Mike", last: "van der Hoorn", pos: "CB" },
    { first: "Nick", last: "Viergevar", pos: "CB" },
    { first: "Souffian", last: "El Faouzi", pos: "CB" },
    { first: "Can", last: "Bozdogan", pos: "DM" },
    { first: "Miguel", last: "Rodriguaz", pos: "CM" },
    { first: "Oliver", last: "Antman", pos: "RW" },
    { first: "Yoann", last: "Cathlina", pos: "AM" },
    { first: "Isac", last: "Lidberg", pos: "ST" },
    { first: "David", last: "Min", pos: "LW" },
    { first: "Alonzo", last: "Engwanda", pos: "DM" },
    { first: "Sebastiaan", last: "Bornauw", pos: "CB" },
    { first: "Victor", last: "Janker", pos: "ST" },
  ],
  "Spartoo Rotterdam": [
    { first: "Niklas", last: "Olij", pos: "GK" },
    { first: "Okay", last: "Yokuslu", pos: "DM" },
    { first: "Bart", last: "Vriends", pos: "CB" },
    { first: "Mike", last: "Eerdhuizen", pos: "CB" },
    { first: "Shurandy", last: "Sambo", pos: "RB" },
    { first: "Tobias", last: "Lauritzen", pos: "ST" },
    { first: "Pelle", last: "Clemant", pos: "ST" },
    { first: "Charles-Andreas", last: "Brym", pos: "RW" },
    { first: "Joshua", last: "Kitolano", pos: "CM" },
    { first: "Vito", last: "van Crooy", pos: "AM" },
    { first: "Koki", last: "Saito", pos: "LW" },
    { first: "Metinho", last: "Ferrara", pos: "CM" },
    { first: "Nick", last: "Olij Jr", pos: "LB" },
    { first: "Aaron", last: "Meijars", pos: "CB" },
    { first: "Yann", last: "Aurel Bisseck", pos: "CB" },
    { first: "Dico", last: "Koppars", pos: "GK" },
  ],
  "Heerenveem": [
    { first: "Andries", last: "Noppert", pos: "GK" },
    { first: "Mickey", last: "van der Hart", pos: "GK" },
    { first: "Thom", last: "Haye", pos: "CM" },
    { first: "Pawel", last: "Bochniewicz", pos: "CB" },
    { first: "Dave", last: "Klein", pos: "CB" },
    { first: "Sven", last: "van Beek", pos: "CB" },
    { first: "Marco", last: "Rente", pos: "RB" },
    { first: "Milan", last: "van Ewijk", pos: "RB" },
    { first: "Levi", last: "Smans", pos: "ST" },
    { first: "Osame", last: "Sahraoui", pos: "LW" },
    { first: "Nils", last: "Roseler", pos: "CB" },
    { first: "Simon", last: "Olsson", pos: "CM" },
    { first: "Luuk", last: "Brouwars", pos: "AM" },
    { first: "Ion", last: "Nicolaescu", pos: "ST" },
    { first: "Daniel", last: "Karlsbakk", pos: "ST" },
    { first: "Tobias", last: "Klysner", pos: "RW" },
  ],
  "Vitessa": [
    { first: "Eloy", last: "Room", pos: "GK" },
    { first: "Jeroen", last: "Houwen", pos: "GK" },
    { first: "Kacper", last: "Kozlowski", pos: "CM" },
    { first: "Million", last: "Manhoef", pos: "RW" },
    { first: "Said", last: "Bakari", pos: "RB" },
    { first: "Carlens", last: "Arcus", pos: "RB" },
    { first: "Mohamed", last: "Sankoh", pos: "ST" },
    { first: "Kacper", last: "Kostorz", pos: "ST" },
    { first: "Jorrel", last: "Hato Jr", pos: "CB" },
    { first: "Melle", last: "Meulensteen", pos: "CB" },
    { first: "Nils", last: "Saether", pos: "LB" },
    { first: "Sondre", last: "Tronstad", pos: "DM" },
    { first: "Kacper", last: "Trelowski", pos: "GK" },
    { first: "Damian", last: "van der Haar", pos: "AM" },
    { first: "Boris", last: "Lambert", pos: "LW" },
    { first: "Tijani", last: "Reijnders Jr", pos: "CM" },
  ],
  "Go Ahead Eagels": [
    { first: "Jeffrey", last: "de Lange", pos: "GK" },
    { first: "Jari", last: "de Busser", pos: "GK" },
    { first: "Mats", last: "Deijl", pos: "RB" },
    { first: "Gerrit", last: "Nauber", pos: "CB" },
    { first: "Jasper", last: "Schendelaar", pos: "GK" },
    { first: "Bobby", last: "Adekanye", pos: "RW" },
    { first: "Mathis", last: "Suray", pos: "RW" },
    { first: "Victor", last: "Edvardsen", pos: "ST" },
    { first: "Oliver", last: "Edvardsen", pos: "ST" },
    { first: "Finn", last: "Stokkers", pos: "ST" },
    { first: "Philippe", last: "Rommens", pos: "CM" },
    { first: "Evert", last: "Linthorst", pos: "CM" },
    { first: "Sylla", last: "Sow", pos: "ST" },
    { first: "Joris", last: "Kramer", pos: "CB" },
    { first: "Enric", last: "Llansana", pos: "DM" },
    { first: "Calvin", last: "Twisk", pos: "LB" },
  ],
  "NEC Nijmegan": [
    { first: "Robin", last: "Roefs", pos: "GK" },
    { first: "Jasper", last: "Cilliessen", pos: "GK" },
    { first: "Bram", last: "Nuytinck", pos: "CB" },
    { first: "Calvin", last: "Verdonk", pos: "LB" },
    { first: "Philip", last: "Mwene", pos: "RB" },
    { first: "Brayann", last: "Lokonga", pos: "DM" },
    { first: "Dirk", last: "Proper", pos: "CM" },
    { first: "Kodai", last: "Sano", pos: "CM" },
    { first: "Sontje", last: "Hansen", pos: "RW" },
    { first: "Vivaldo", last: "Semedo", pos: "LW" },
    { first: "Koki", last: "Ogawara", pos: "ST" },
    { first: "Bryan", last: "Linssen", pos: "ST" },
    { first: "Ivan", last: "Marquez", pos: "CB" },
    { first: "Lasse", last: "Schone", pos: "CM" },
    { first: "Mees", last: "Hoedemakers", pos: "DM" },
    { first: "Tjaronn", last: "Chery", pos: "AM" },
  ],
  "Sittard Forton": [
    { first: "Faruk", last: "Can Genc", pos: "GK" },
    { first: "Ivor", last: "Pandur", pos: "GK" },
    { first: "Rodrigo", last: "Guth", pos: "CB" },
    { first: "Alessio", last: "da Cruz", pos: "RW" },
    { first: "Tijjani", last: "Noslin", pos: "ST" },
    { first: "Kaan", last: "Caliskaner", pos: "ST" },
    { first: "Inigo", last: "Cordoba", pos: "AM" },
    { first: "Justin", last: "Lonwijk", pos: "CM" },
    { first: "Ryan", last: "Flamingo", pos: "CB" },
    { first: "Ivan", last: "Illichev", pos: "GK" },
    { first: "Gergo", last: "Kocsis", pos: "DM" },
    { first: "Dimitris", last: "Rallis", pos: "CM" },
    { first: "Burak", last: "Yilmaz Jr", pos: "ST" },
    { first: "Bilal", last: "Ould-Chikh", pos: "LW" },
    { first: "Emil", last: "Hansson", pos: "RW" },
    { first: "George", last: "Cox", pos: "LB" },
  ],
  "Heraclus": [
    { first: "Fabian", last: "de Keijzer", pos: "GK" },
    { first: "Michael", last: "Brouwer", pos: "GK" },
    { first: "Mats", last: "Knoester", pos: "CB" },
    { first: "Jizz", last: "Hornkamp", pos: "ST" },
    { first: "Bryan", last: "Limbombe", pos: "RW" },
    { first: "Justin", last: "Hoogma", pos: "CB" },
    { first: "Anas", last: "Ouahim", pos: "AM" },
    { first: "Brian", last: "de Keersmaecker", pos: "CM" },
    { first: "Thomas", last: "Bruns", pos: "DM" },
    { first: "Marco", last: "Rente Jr", pos: "RB" },
    { first: "Luca", last: "de la Torre", pos: "CM" },
    { first: "Mauro", last: "Junior Jr", pos: "LB" },
    { first: "Emmanuel", last: "Antwi", pos: "CB" },
    { first: "Sven", last: "Sonnenberg", pos: "CB" },
    { first: "Naci", last: "Unuvar", pos: "AM" },
    { first: "Jamie", last: "Jacobs", pos: "ST" },
  ],
  "PEX Zwolle": [
    { first: "Jasper", last: "Schendelar", pos: "GK" },
    { first: "Mike", last: "Hauptmeijer", pos: "GK" },
    { first: "Bram", last: "van Polen", pos: "RB" },
    { first: "Davy", last: "van den Berg", pos: "CB" },
    { first: "Younes", last: "Namli", pos: "AM" },
    { first: "Rav", last: "van den Berg", pos: "CB" },
    { first: "Thomas", last: "van den Belt", pos: "CM" },
    { first: "Nick", last: "Fichtinger", pos: "DM" },
    { first: "Anselmo", last: "Garcia MacNulty", pos: "CB" },
    { first: "Lennart", last: "Thy", pos: "ST" },
    { first: "Koki", last: "Yonekura", pos: "RB" },
    { first: "Dean", last: "Huiberts", pos: "ST" },
    { first: "Sam", last: "Kersten", pos: "CB" },
    { first: "Younes", last: "Taha", pos: "AM" },
    { first: "Daniel", last: "van Kaam", pos: "CM" },
    { first: "Ferdy", last: "Druijf", pos: "ST" },
  ],
  "Wagening Groningen": [
    { first: "Etienne", last: "Vaessen", pos: "GK" },
    { first: "Mo", last: "El Hankouri", pos: "AM" },
    { first: "Marco", last: "Rente Sr", pos: "RB" },
    { first: "Wessel", last: "Kuhn", pos: "RB" },
    { first: "Marvin", last: "Peersman", pos: "LB" },
    { first: "Thom", last: "van Bergen", pos: "RW" },
    { first: "Romano", last: "Postema", pos: "ST" },
    { first: "Brynjolfur", last: "Willumsson", pos: "ST" },
    { first: "Luciano", last: "Valente", pos: "CM" },
    { first: "Leandro", last: "Bacuna", pos: "DM" },
    { first: "Dave", last: "Kwakman", pos: "CB" },
    { first: "Thijmen", last: "Blokzijl", pos: "CB" },
    { first: "Stije", last: "Resink", pos: "CB" },
    { first: "Jorg", last: "Schreuders", pos: "CM" },
    { first: "Younes", last: "Taha Jr", pos: "LW" },
    { first: "Tijmen", last: "Kuipers", pos: "GK" },
  ],
  "Willim II": [
    { first: "Connor", last: "van den Berg", pos: "GK" },
    { first: "Robbin", last: "Ruiter", pos: "GK" },
    { first: "Jeremy", last: "Bokila", pos: "ST" },
    { first: "Kyan", last: "Vaesen", pos: "ST" },
    { first: "Cisse", last: "Sandra", pos: "AM" },
    { first: "Jizz", last: "Hornkamp Jr", pos: "ST" },
    { first: "Max", last: "Svensson", pos: "RW" },
    { first: "Jesse", last: "Bosch", pos: "CM" },
    { first: "Rui", last: "Mendes", pos: "ST" },
    { first: "Elton", last: "Kabangu", pos: "LW" },
    { first: "Kacper", last: "Kostorz Jr", pos: "ST" },
    { first: "Thomas", last: "Robinet", pos: "ST" },
    { first: "Jorn", last: "Brondeel", pos: "GK" },
    { first: "Aliou", last: "Balde", pos: "RW" },
    { first: "Jordens", last: "Peters", pos: "CB" },
    { first: "Ringo", last: "Meerveld", pos: "CM" },
  ],

  // ===== Eerste Divisus =====
  "Den Haag ADU": [
    { first: "Hugo", last: "Wentges", pos: "GK" },
    { first: "Luuk", last: "Koopmans", pos: "GK" },
    { first: "Daryl", last: "van Mieghem", pos: "RW" },
    { first: "Steven", last: "van der Heijden", pos: "DM" },
    { first: "Thomas", last: "Verheijdt", pos: "ST" },
    { first: "Sebastian", last: "Pasquali", pos: "AM" },
    { first: "Robin", last: "Schouten", pos: "CM" },
    { first: "Stije", last: "Spierings", pos: "DM" },
    { first: "Bilal", last: "Ould-Chikh Jr", pos: "LW" },
    { first: "Eric", last: "Oelschlagel", pos: "GK" },
    { first: "Boyd", last: "Lucassen", pos: "CB" },
    { first: "Joeri", last: "Schroijen", pos: "CB" },
    { first: "Toby", last: "Lokin", pos: "RB" },
    { first: "Henk", last: "Bos", pos: "LB" },
    { first: "Samuele", last: "Mulattieri", pos: "ST" },
    { first: "Rashaan", last: "Fernandes", pos: "AM" },
  ],
  "Roda JK": [
    { first: "Xavier", last: "Mous", pos: "GK" },
    { first: "Bram", last: "Castro", pos: "GK" },
    { first: "Dylan", last: "Vente", pos: "ST" },
    { first: "Sam", last: "Hendriks", pos: "ST" },
    { first: "Mees", last: "Rijks", pos: "CM" },
    { first: "Dani", last: "van den Heuvel", pos: "GK" },
    { first: "Walid", last: "Ould-Chikh", pos: "RW" },
    { first: "Kevin", last: "van Kippersluis", pos: "AM" },
    { first: "Patrick", last: "Pflucke", pos: "LW" },
    { first: "Anco", last: "Jansen", pos: "AM" },
    { first: "Tom", last: "van de Looi", pos: "CM" },
    { first: "Roy", last: "Kuijpers", pos: "ST" },
    { first: "Lars", last: "Nieuwpoort", pos: "CB" },
    { first: "Calvin", last: "Sombroek", pos: "CB" },
    { first: "Jan", last: "Lammers", pos: "RB" },
    { first: "Mart", last: "Remans", pos: "LB" },
  ],
  "De Graafschop": [
    { first: "Hidde", last: "Jurjus", pos: "GK" },
    { first: "Nigel", last: "Bertrams", pos: "GK" },
    { first: "Ralf", last: "Seuntjens", pos: "AM" },
    { first: "Jasper", last: "van Heertum", pos: "DM" },
    { first: "Devin", last: "Haen", pos: "CB" },
    { first: "Joey", last: "Konings", pos: "ST" },
    { first: "Basar", last: "Onal", pos: "RW" },
    { first: "Rio", last: "Hillen", pos: "LB" },
    { first: "Sven", last: "Nieuwpoort", pos: "CB" },
    { first: "Daniel", last: "Cuijpers", pos: "CM" },
    { first: "Philip", last: "Brittijn", pos: "LW" },
    { first: "Jasper", last: "Schuurman", pos: "ST" },
    { first: "Mo", last: "Hamdaoui", pos: "AM" },
    { first: "Toine", last: "van Huizen", pos: "CB" },
    { first: "Giovanni", last: "Korte", pos: "RW" },
    { first: "Elmo", last: "Lieftink", pos: "DM" },
  ],
  "Eindhovan FC": [
    { first: "Ruud", last: "Swinkels", pos: "GK" },
    { first: "Nigel", last: "Bertrams Jr", pos: "GK" },
    { first: "Joey", last: "Sleegers", pos: "RW" },
    { first: "Naoufal", last: "Bannis", pos: "ST" },
    { first: "Mart", last: "Remans Jr", pos: "ST" },
    { first: "Collin", last: "Seedorf", pos: "RB" },
    { first: "Branco", last: "van den Boomen", pos: "AM" },
    { first: "Dylan", last: "Seys", pos: "RW" },
    { first: "Mickey", last: "van Diemen", pos: "CM" },
    { first: "Evan", last: "Rottier", pos: "LB" },
    { first: "Kevin", last: "Felida", pos: "LW" },
    { first: "Charles", last: "Velvin", pos: "GK" },
    { first: "Jasper", last: "Dahlhaus", pos: "DM" },
    { first: "Rio", last: "den Haag", pos: "CB" },
    { first: "Lance", last: "Duijvestijn", pos: "AM" },
    { first: "Tom", last: "Boere", pos: "ST" },
  ],
  "Volendamm": [
    { first: "Mio", last: "Backhaus", pos: "GK" },
    { first: "Filip", last: "Stankovic", pos: "GK" },
    { first: "Daryl", last: "van Mieghem Jr", pos: "RW" },
    { first: "Bilal", last: "Ould-Chikh Sr", pos: "LW" },
    { first: "Gaetano", last: "Oristanio", pos: "AM" },
    { first: "Robert", last: "Muhren", pos: "ST" },
    { first: "Henk", last: "Veerman", pos: "ST" },
    { first: "Damon", last: "Mirani", pos: "CB" },
    { first: "Brian", last: "Plat", pos: "CM" },
    { first: "Garino", last: "Brako", pos: "RW" },
    { first: "Lequincio", last: "Zeefuik", pos: "RW" },
    { first: "Micky", last: "van de Ven", pos: "CB" },
    { first: "Bilal", last: "Ould-Chikh III", pos: "LW" },
    { first: "Carel", last: "Eiting", pos: "CM" },
    { first: "Derry", last: "John Murkin", pos: "LB" },
    { first: "Datro", last: "Fofana", pos: "ST" },
  ],
  "Cambuur Leeuward": [
    { first: "Sonny", last: "Stevens", pos: "GK" },
    { first: "Pieter", last: "Bos", pos: "GK" },
    { first: "Robert", last: "Muhren Jr", pos: "ST" },
    { first: "Issa", last: "Kallon", pos: "RW" },
    { first: "Mees", last: "Hoedemakers Jr", pos: "DM" },
    { first: "Milan", last: "Smit", pos: "ST" },
    { first: "Roberts", last: "Uldrikis", pos: "ST" },
    { first: "Jamie", last: "Jacobs Jr", pos: "ST" },
    { first: "Marvin", last: "Peersman Jr", pos: "LB" },
    { first: "Mitchel", last: "Paulissen", pos: "CM" },
    { first: "Alex", last: "Bangura", pos: "LB" },
    { first: "Tom", last: "Boere Jr", pos: "ST" },
    { first: "Maxime", last: "Gunst", pos: "RB" },
    { first: "Erik", last: "Schouten", pos: "CB" },
    { first: "Lars", last: "Hutten", pos: "ST" },
    { first: "Kevin", last: "van Kippersluis Jr", pos: "AM" },
  ],
  "Helmond Sportu": [
    { first: "Stijn", last: "van Gassel", pos: "GK" },
    { first: "Mike", last: "Havekotte", pos: "GK" },
    { first: "Jordy", last: "Thomassen", pos: "RW" },
    { first: "Karim", last: "Loukili", pos: "AM" },
    { first: "Lance", last: "Duijvestijn Jr", pos: "RW" },
    { first: "Brian", last: "De Keersmaecker Jr", pos: "CM" },
    { first: "Stan", last: "Maas", pos: "RB" },
    { first: "Boyd", last: "Lucassen Jr", pos: "CB" },
    { first: "Quinten", last: "Schram", pos: "GK" },
    { first: "Orhan", last: "Dzepar", pos: "DM" },
    { first: "Tarik", last: "Tissoudali", pos: "LW" },
    { first: "Daniel", last: "Crowley", pos: "AM" },
    { first: "Roy", last: "Kuijpers Jr", pos: "ST" },
    { first: "Mikkel", last: "Hyllgaardt", pos: "CB" },
    { first: "Floris", last: "Hesselink", pos: "LB" },
    { first: "Saliou", last: "Guisse", pos: "ST" },
  ],
  "MVV Maastrycht": [
    { first: "Romain", last: "Matthys", pos: "GK" },
    { first: "Tristan", last: "Peersman", pos: "GK" },
    { first: "Koen", last: "Kostons", pos: "ST" },
    { first: "Senne", last: "Brits", pos: "AM" },
    { first: "Joeri", last: "Schroijen Jr", pos: "CB" },
    { first: "Mart", last: "Remans III", pos: "ST" },
    { first: "Ozgur", last: "Aktas", pos: "RW" },
    { first: "Nick", last: "Venema", pos: "ST" },
    { first: "Sven", last: "Blummel", pos: "CM" },
    { first: "Daniel", last: "Maderner", pos: "ST" },
    { first: "Anthony", last: "van den Hurk", pos: "ST" },
    { first: "Tom", last: "Beugelsdijk", pos: "CB" },
    { first: "Joeri", last: "Poelmans", pos: "LB" },
    { first: "Mart", last: "Lieder", pos: "ST" },
    { first: "Yannick", last: "Leliendal", pos: "RB" },
    { first: "Lance", last: "Duijvestijn III", pos: "RW" },
  ],
  "VVV Venloo": [
    { first: "Jorrit", last: "Smeets", pos: "GK" },
    { first: "Delano", last: "van Crooij", pos: "GK" },
    { first: "Nils", last: "Roseler Jr", pos: "CB" },
    { first: "Sven", last: "Braken", pos: "ST" },
    { first: "Roman", last: "Palmtag", pos: "RB" },
    { first: "Florian", last: "Pick", pos: "LW" },
    { first: "Tobias", last: "Pachonik", pos: "RB" },
    { first: "Vito", last: "van Crooij Jr", pos: "AM" },
    { first: "Christian", last: "Kum", pos: "DM" },
    { first: "Simon", last: "Janssen", pos: "CM" },
    { first: "Jafar", last: "Arias", pos: "ST" },
    { first: "Joery", last: "de Kamps", pos: "CM" },
    { first: "Khalid", last: "Karami", pos: "RB" },
    { first: "Lennard", last: "Hartjes", pos: "CB" },
    { first: "Tim", last: "Receveur", pos: "RW" },
    { first: "Danny", last: "Post", pos: "AM" },
  ],
  "Excelsiar": [
    { first: "Stijn", last: "van Gassel Jr", pos: "GK" },
    { first: "Calvin", last: "Raatsie", pos: "GK" },
    { first: "Marouan", last: "Azarkan", pos: "RW" },
    { first: "Couhaib", last: "Driouech", pos: "RW" },
    { first: "Redouan", last: "El Yaakoubi", pos: "CB" },
    { first: "Siebe", last: "Horemans", pos: "RB" },
    { first: "Sven", last: "Nieuwpoort Jr", pos: "CB" },
    { first: "Reagan", last: "Pereira", pos: "AM" },
    { first: "Kenzo", last: "Goudmijn", pos: "CM" },
    { first: "Casper", last: "Widell", pos: "DM" },
    { first: "Troy", last: "Parrott Jr", pos: "ST" },
    { first: "Noah", last: "Naujoks", pos: "ST" },
    { first: "Serge", last: "Fortunatus", pos: "ST" },
    { first: "Julian", last: "Baas", pos: "CM" },
    { first: "Mike", last: "van Duinen", pos: "ST" },
    { first: "Lazaros", last: "Lamprou", pos: "LW" },
  ],
  "Den Bosh": [
    { first: "Wouter", last: "van der Steen", pos: "GK" },
    { first: "Tom", last: "Heerkens", pos: "GK" },
    { first: "Ryan", last: "Trotman", pos: "CB" },
    { first: "Danny", last: "Verbeek", pos: "AM" },
    { first: "Jizz", last: "Hornkamp III", pos: "ST" },
    { first: "Stije", last: "Resink Jr", pos: "CB" },
    { first: "Sekou", last: "Sylla", pos: "ST" },
    { first: "Rodin", last: "Tomas", pos: "GK" },
    { first: "Romano", last: "Postema Jr", pos: "ST" },
    { first: "Joey", last: "Konings Jr", pos: "RW" },
    { first: "Kevin", last: "Felida Jr", pos: "LW" },
    { first: "Brian", last: "De Kogel", pos: "CM" },
    { first: "Lars", last: "Hutten Jr", pos: "ST" },
    { first: "Marlon", last: "Frey", pos: "DM" },
    { first: "Bart", last: "Meijers", pos: "RB" },
    { first: "Stan", last: "Maas Jr", pos: "LB" },
  ],
  "Telstor": [
    { first: "Ronald", last: "Koeman Jr", pos: "GK" },
    { first: "Joey", last: "Roggeveen", pos: "GK" },
    { first: "Glynor", last: "Plet", pos: "ST" },
    { first: "Kaj", last: "Ramsteijn", pos: "CB" },
    { first: "Andries", last: "Jonker", pos: "DM" },
    { first: "Buster", last: "Tengstedt", pos: "ST" },
    { first: "Kjell", last: "Knops", pos: "CB" },
    { first: "Tarik", last: "Evre", pos: "RW" },
    { first: "Rein", last: "van Helden", pos: "AM" },
    { first: "Mo", last: "Hamdaoui Jr", pos: "AM" },
    { first: "Ozgur", last: "Aktas Jr", pos: "RW" },
    { first: "Aleksander", last: "Stankov", pos: "CM" },
    { first: "Cyriel", last: "Dessers Jr", pos: "ST" },
    { first: "Bryan", last: "Smeets", pos: "CM" },
    { first: "Anass", last: "Ahannach", pos: "LW" },
    { first: "Riad", last: "Bajic", pos: "ST" },
  ],
  "Dordrechd": [
    { first: "Nigel", last: "Bertrams III", pos: "GK" },
    { first: "Liam", last: "Bossin", pos: "GK" },
    { first: "Michael", last: "Parkes", pos: "CB" },
    { first: "Toine", last: "van Huizen Jr", pos: "CB" },
    { first: "Lukas", last: "Kruckel", pos: "AM" },
    { first: "Hicham", last: "Acheffay", pos: "RW" },
    { first: "Aleksandar", last: "Stevanovic", pos: "ST" },
    { first: "Anthony", last: "van den Hurk Jr", pos: "ST" },
    { first: "Devran", last: "Kurt", pos: "RB" },
    { first: "Noah", last: "Naujoks Jr", pos: "ST" },
    { first: "Romano", last: "Postema III", pos: "ST" },
    { first: "Sho", last: "Sasaki", pos: "CM" },
    { first: "Karol", last: "Mets", pos: "CB" },
    { first: "Stije", last: "Spierings Jr", pos: "DM" },
    { first: "Mees", last: "Bakker", pos: "LB" },
    { first: "Bilal", last: "Bayazit", pos: "GK" },
  ],
  "Emmen FC": [
    { first: "Mickey", last: "van der Hart Jr", pos: "GK" },
    { first: "Eric", last: "Oelschlagel Jr", pos: "GK" },
    { first: "Jasin", last: "Recic", pos: "DM" },
    { first: "Ole", last: "Romeny", pos: "ST" },
    { first: "Rui", last: "Mendes Jr", pos: "ST" },
    { first: "Jeremy", last: "Antonisse", pos: "RW" },
    { first: "Mark", last: "Diemers", pos: "AM" },
    { first: "Kasper", last: "Kusk", pos: "RW" },
    { first: "Jari", last: "Vlak", pos: "AM" },
    { first: "Lance", last: "Duijvestijn IV", pos: "LW" },
    { first: "Damil", last: "Dankerlui", pos: "RB" },
    { first: "Keziah", last: "Veendorp", pos: "LB" },
    { first: "Miguel", last: "Araujo Jr", pos: "CB" },
    { first: "Jasper", last: "Schuurman Jr", pos: "CB" },
    { first: "Richairo", last: "Zivkovic", pos: "ST" },
    { first: "Peter", last: "van Ooijen", pos: "CM" },
  ],
  "Oss TOP": [
    { first: "Norbert", last: "Alblas", pos: "GK" },
    { first: "Stan", last: "Spaen", pos: "GK" },
    { first: "Lyon", last: "Doumbia", pos: "DM" },
    { first: "Justin", last: "Mathieu", pos: "ST" },
    { first: "Cas", last: "Odenthal", pos: "CB" },
    { first: "Anas", last: "Tahiri", pos: "AM" },
    { first: "Romano", last: "Postema IV", pos: "ST" },
    { first: "Tom", last: "Boere III", pos: "ST" },
    { first: "Kay", last: "Tejan", pos: "ST" },
    { first: "Jearl", last: "Margaritha", pos: "RW" },
    { first: "Daniel", last: "Maderner Jr", pos: "ST" },
    { first: "Rio", last: "Hillen Jr", pos: "LB" },
    { first: "Sven", last: "Blummel Jr", pos: "CM" },
    { first: "Bart", last: "Meijers Jr", pos: "RB" },
    { first: "Jordy", last: "Thomassen Jr", pos: "RW" },
    { first: "Joeri", last: "de Kamps Jr", pos: "CM" },
  ],
  "Jong Utrechd": [
    { first: "Fern", last: "Temparman Jr", pos: "GK" },
    { first: "Calvin", last: "Raatsie Jr", pos: "GK" },
    { first: "Hidde", last: "ter Avest", pos: "RB" },
    { first: "Damon", last: "Mirani Jr", pos: "CB" },
    { first: "Rome", last: "Owusu Jr", pos: "CB" },
    { first: "Alonzo", last: "Engwanda Jr", pos: "DM" },
    { first: "Tim", last: "Receveur Jr", pos: "CM" },
    { first: "Yoann", last: "Cathlina Jr", pos: "AM" },
    { first: "David", last: "Min Jr", pos: "LW" },
    { first: "Victor", last: "Janker Jr", pos: "ST" },
    { first: "Isac", last: "Lidberg Jr", pos: "ST" },
    { first: "Oliver", last: "Antman Jr", pos: "RW" },
    { first: "Kevin", last: "Schippers", pos: "CB" },
    { first: "Sander", last: "Vereijken", pos: "LB" },
    { first: "Daniel", last: "Brouwer", pos: "CM" },
    { first: "Marouan", last: "Azarkan Jr", pos: "AM" },
  ],
};
